SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BS_INDICATORS_RECALC_LOGS](
	[CALC_TIME] [datetime] NULL,
	[CALC_RESULTS] [ntext] NULL,
	[BS_LOGS_ID] [int] IDENTITY(1, 1)
)
ON [PRIMARY]
