SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HISTORIAASUNTOS](
	[CODIGO] [int] IDENTITY(1, 1),
	[CODIGONC] [int] NOT NULL,
	[CODIGOTAREA] [int] NULL,
	[USUARIO] [nvarchar](50) NULL,
	[FECHA] [datetime] NOT NULL,
	[DESCRIPCION] [nvarchar](1000) NOT NULL,
	[INFORME] [ntext] NULL,
	[SUBCLASS_UNIQUEID] [nvarchar](50) NULL,
	[SUBCLASS_RECORDID] [int] NULL,
	[ISSUE_STATUS] [tinyint] NULL
)
ON [PRIMARY]
