SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[IK_PEOPLE_HISTORY](
	[IK_PEOPLE_HISTORY_ID] [int] IDENTITY(1, 1),
	[IK_PEOPLE_ID] [int] NOT NULL,
	[IK_PEOPLE_HISTORY_DATE] [datetime] NOT NULL,
	[IK_PEOPLE_HISTORY_ENTRY] [nvarchar](1000) NOT NULL,
	[IK_PEOPLE_HISTORY_REPORT] [ntext] NULL,
	[IK_PEOPLE_HISTORY_USER] [nvarchar](50) NULL,
	[IK_PEOPLE_HISTORY_ENTRY_TYPE] [tinyint] NOT NULL
)
ON [PRIMARY]
