SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[IKUSERLOGS](
	[IKUSERLOGSID] [int] IDENTITY(1, 1),
	[INPUTDATE] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[URL] [nvarchar](300) NOT NULL,
	[IKPATHTEXT] [nvarchar](300) NOT NULL
)
ON [PRIMARY]
