SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[IKUSERLOGINS](
	[IKUSERLOGINSID] [int] IDENTITY(1, 1),
	[USERNAME] [nvarchar](50) NOT NULL,
	[USERID] [int] NOT NULL,
	[INPUTDATE] [datetime] NOT NULL,
	[USERIP] [nvarchar](200) NULL,
	[AUTMODE] [nvarchar](50) NOT NULL,
	[USERAGENT] [nvarchar](500) NOT NULL,
	[LOGINNAME] [nvarchar](50) NULL
)
ON [PRIMARY]
