SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaDestinatarios]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaDestinatarios] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaDestinatarios]
@error varchar(255)  OUTPUT,
   @vcCodigoTipoArchivo varchar(6)
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaDestinatarios
   *    *  Objetivo:       Consulta sobre los posibles destinatarios, de acuerdo al archivo a enviar.
   *    *  Autor Creación: Alvaro Acevedo S.
   *    *  Fecha Creación: 29/07/2010
   *    *
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        @vcCodigoTipoArchivo  Codigo tipo de archivo.
   *    *
   *    *  Salida:         @error                error de salida
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT DISTINCT i.cod_inst, i.nom_inst, c.cod_casi
      FROM 
         dbo.tblRelTipoArchivoUsuario  AS tau, 
         dbo.tblUsuario  AS u, 
         dbo.tbl_inst  AS i, 
         dbo.tbl_casi  AS c
      WHERE 
         tau.vcCodigoTipoArchivo = @vcCodigoTipoArchivo AND 
         tau.vcCodigoUsuario = u.vcCodigoUsuario AND 
         u.vcCodigoInstitucion = i.cod_inst AND 
         i.cod_inst = c.cod_inst
      ORDER BY i.cod_inst, c.cod_casi
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
