SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaPrivilegiosSFT3]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaPrivilegiosSFT3] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaPrivilegiosSFT3]
@error varchar(255)  OUTPUT
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaPrivilegiosSFT3
   *    *  Objetivo:       Consulta los privilegios del Sistema.
   *    *  Autor Creación: Alvaro Acevedo S.
   *    *  Fecha Creación: 15/09/2010
   *    *
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        No hay.
   *    *
   *    *  Salida:         @error          error de salida
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT p.vcDireccionHttp, rpp.vcCodigoPerfil
      FROM dbo.tblPrivilegio  AS p, dbo.tblRelPrivilegioPerfil  AS rpp
      WHERE p.vcCodigoPrivilegio = rpp.vcCodigoPrivilegio
      ORDER BY rpp.vcCodigoPerfil
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
