SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaDestinatarioEmail]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaDestinatarioEmail] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaDestinatarioEmail]
@error varchar(255)  OUTPUT,
   @vcCodigoInstitucion varchar(4),
   @vcCodigoTipoArchivo varchar(6)
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaDestinatarioEmail
   *    *  Objetivo:       Consulta sobre los posibles destinatarios, de acuerdo a la isntitucion y al archivo a enviar.
   *    *  Autor Creación: Andrea Zarabia V.
   *    *  Fecha Creación: 15/10/2010
   *   
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        @vcCodigoInstitucion      Codigo institucion.
   *    *                  @vcCodigoTipoArchivo      Codigo tipo de archivo.
   *    *
   *    *  Salida:         @error         error de salida
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT u.vcCodigoUsuario, u.vcNombreUsuario, u.vcDireccionEmail, u.vcCodigoInstitucion
      FROM dbo.tblUsuario  AS u, dbo.tblRelTipoArchivoUsuario  AS tau
      WHERE 
         u.vcCodigoInstitucion = @vcCodigoInstitucion AND 
         u.vcCodigoUsuario = tau.vcCodigoUsuario AND 
         tau.vcCodigoTipoArchivo = @vcCodigoTipoArchivo
      ORDER BY u.vcCodigoUsuario
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
