SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaUsuaTipoArchivo]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaUsuaTipoArchivo] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaUsuaTipoArchivo]
@error varchar(255)  OUTPUT,
   @vcCodigoTipoArchivo varchar(6)
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaTipoArchivoUsua
   *    *  Objetivo:       Consulta sobre los usuarios existentes para un tipo de archivo.
   *    *  Autor Creación: Andrea Zarabia.
   *    *  Fecha Creación: 08/11/2010
   *   
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        @vcCodigoTipoArchivo  Codigo de Archivo.
   *    *
   *    *  Salida:         @error                error de salida
   *    *
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN

      IF (@vcCodigoTipoArchivo = '')
         BEGIN
            SELECT tau.vcCodigoUsuario AS vcCodigoUsuario, u.vcCodigoInstitucion AS vcCodigoInstitucion, i.nom_inst AS vc_nom_inst, tau.vcCodigoTipoArchivo AS vcCodigoTipoArchivo
            FROM dbo.tblRelTipoArchivoUsuario  AS tau, dbo.tblUsuario  AS u, dbo.tbl_inst  AS i
            WHERE tau.vcCodigoUsuario = u.vcCodigoUsuario AND u.vcCodigoInstitucion = i.cod_inst
            ORDER BY i.nom_inst
         END
      ELSE 
         BEGIN
            SELECT tau.vcCodigoUsuario AS vcCodigoUsuario, u.vcCodigoInstitucion AS vcCodigoInstitucion, i.nom_inst AS vc_nom_inst, tau.vcCodigoTipoArchivo AS vcCodigoTipoArchivo
            FROM dbo.tblRelTipoArchivoUsuario  AS tau, dbo.tblUsuario  AS u, dbo.tbl_inst  AS i
            WHERE 
               tau.vcCodigoTipoArchivo = @vcCodigoTipoArchivo AND 
               tau.vcCodigoUsuario = u.vcCodigoUsuario AND 
               u.vcCodigoInstitucion = i.cod_inst
            ORDER BY i.nom_inst
         END

      IF @@ROWCOUNT < 1
         BEGIN

            SELECT @error = 'NO EXISTEN DATOS'

            RETURN 1

         END

      SELECT @error = ''

      RETURN 0

   END
GO
