SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[ik_NC_Corte_Evolucion_arbol]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_NC_Corte_Evolucion_arbol] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_NC_Corte_Evolucion_arbol]
(
	@corte nvarchar(400) = 'Loc_Type',
	@filtro_caracter nvarchar(400) = '*',
	@filtro_area nvarchar(400)= '*',
	@filtro_proceso nvarchar(400)= '*',
	@filtro_causa nvarchar(400)= '*',
	@filtro_requisito nvarchar(400)= '*'
)
AS
	SET NOCOUNT ON 

	if @corte is null or len(@corte)=0
	set @corte='Loc_Type'

	DECLARE @ASTERISCO NVARCHAR(400)
	SET @ASTERISCO = '*                                                                                                                                      '

	DECLARE @CARACTER NVARCHAR(400)
	if @filtro_caracter is null or len(@filtro_caracter)=0
	set @filtro_caracter=@ASTERISCO

	DECLARE @AREA NVARCHAR(400)
	if @filtro_area is null or len(@filtro_area)=0
	set @filtro_area=@ASTERISCO

	DECLARE @PROCESO NVARCHAR(400)
	if @filtro_proceso is null or len(@filtro_proceso)=0
	set @filtro_proceso=@ASTERISCO

	DECLARE @CAUSA NVARCHAR(400)
	if @filtro_causa is null or len(@filtro_causa)=0
	set @filtro_causa=@ASTERISCO

	DECLARE @REQUISITO NVARCHAR(400)
	if @filtro_requisito is null or len(@filtro_requisito)=0
	set @filtro_requisito=@ASTERISCO
	
---------------------------------------Causas------------------------------------------------------------------------			
	CREATE TABLE #TablaT (
		CODIGO int,	
		DESCRIPCION nvarchar(4000),
		DESC_NIVEL1 nvarchar(4000),
		DESC_NIVEL2 nvarchar(4000)
	)

	DECLARE @CODIGO int
	DECLARE @PADRE INT
	DECLARE @DESCRIPCION NVARCHAR(4000)
	DECLARE @CODIGOH int
	DECLARE @NOMBRE NVARCHAR(400)
	DECLARE @NIVEL INT

	INSERT INTO #TablaT(CODIGO, DESCRIPCION, DESC_NIVEL1, DESC_NIVEL2) 
	SELECT  CODIGO, DESCRIPCION , 'N/A'			, 'N/A'			FROM TBL_NCCC_CAUSAS WHERE NIVEL=3
	UNION
	SELECT	CODIGO, 'N/A'		, 'N/A'			, DESCRIPCION	FROM TBL_NCCC_CAUSAS WHERE NIVEL=2
	UNION
	SELECT	CODIGO, 'N/A'		, DESCRIPCION	, 'N/A'			FROM TBL_NCCC_CAUSAS WHERE NIVEL=1

	DECLARE CurNodos CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO
	FROM TBL_NCCC_CAUSAS
	WHERE NIVEL = 3
	open CurNodos
	fetch next from CurNodos into @CODIGO
	while @@FETCH_STATUS = 0
	begin				
		SELECT @DESCRIPCION = DESCRIPCION
		FROM TBL_NCCC_CAUSAS
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_CAUSAS WHERE CODIGO = @CODIGO)
		UPDATE #TablaT
		SET DESC_NIVEL2 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodos into @CODIGO
	end
	close CurNodos
	deallocate CurNodos

	DECLARE CurNodos CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO
	FROM TBL_NCCC_CAUSAS
	WHERE NIVEL = 2
	open CurNodos
	fetch next from CurNodos into @CODIGO
	while @@FETCH_STATUS = 0
	begin
		SELECT @DESCRIPCION = DESCRIPCION
		FROM TBL_NCCC_CAUSAS
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_CAUSAS WHERE CODIGO = @CODIGO)
		UPDATE #TablaT
		SET DESC_NIVEL1 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodos into @CODIGO
	end
	close CurNodos
	deallocate CurNodos
	DECLARE CurNodos CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO 
	FROM TBL_NCCC_CAUSAS
	WHERE NIVEL = 3
	Open CurNodos
	fetch next from CurNodos into @CODIGO
	while @@FETCH_STATUS = 0
	begin
		SELECT @DESCRIPCION = DESC_NIVEL1
		FROM #TablaT
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_CAUSAS WHERE CODIGO = @CODIGO)
		UPDATE #TablaT
		SET DESC_NIVEL1 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodos into @CODIGO
	end

---------------------------------------Requisitos Normativos------------------------------------------------------------------------
	CREATE TABLE #TablaReq (
		CODIGO int,	
		DESCRIPCION nvarchar(4000),
		DESC_NIVEL1 nvarchar(4000),
		DESC_NIVEL2 nvarchar(4000)
	)

	INSERT INTO #TablaReq(CODIGO, DESCRIPCION, DESC_NIVEL1, DESC_NIVEL2) 
	SELECT  CODIGO, DESCRIPCION , 'N/A'			, 'N/A'			FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE NIVEL=3
	UNION
	SELECT	CODIGO, 'N/A'		, 'N/A'			, DESCRIPCION	FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE NIVEL=2
	UNION
	SELECT	CODIGO, 'N/A'		, DESCRIPCION	, 'N/A'			FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE NIVEL=1

	DECLARE CurNodosReq CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO
	FROM TBL_NCCC_REQUISITOSNORMATIVOS
	WHERE NIVEL = 3
	open CurNodosReq
	fetch next from CurNodosReq into @CODIGO
	while @@FETCH_STATUS = 0
	begin				
		SELECT @DESCRIPCION = DESCRIPCION
		FROM TBL_NCCC_REQUISITOSNORMATIVOS
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE CODIGO = @CODIGO)
		UPDATE #TablaReq
		SET DESC_NIVEL2 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodosReq into @CODIGO
	end
	close CurNodosReq
	deallocate CurNodosReq

	DECLARE CurNodosReq CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO
	FROM TBL_NCCC_REQUISITOSNORMATIVOS
	WHERE NIVEL = 2
	open CurNodosReq
	fetch next from CurNodosReq into @CODIGO
	while @@FETCH_STATUS = 0
	begin
		SELECT @DESCRIPCION = DESCRIPCION
		FROM TBL_NCCC_REQUISITOSNORMATIVOS
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE CODIGO = @CODIGO)
		UPDATE #TablaReq
		SET DESC_NIVEL1 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodosReq into @CODIGO
	end
	close CurNodosReq
	deallocate CurNodosReq
	DECLARE CurNodosReq CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO 
	FROM TBL_NCCC_REQUISITOSNORMATIVOS
	WHERE NIVEL = 3
	Open CurNodosReq
	fetch next from CurNodosReq into @CODIGO
	while @@FETCH_STATUS = 0
	begin
		SELECT @DESCRIPCION = DESC_NIVEL1
		FROM #TablaReq
		WHERE CODIGO = (SELECT CODIGO_PADRE FROM TBL_NCCC_REQUISITOSNORMATIVOS WHERE CODIGO = @CODIGO)
		UPDATE #TablaReq
		SET DESC_NIVEL1 = @DESCRIPCION
		WHERE CODIGO = @CODIGO
		fetch next from CurNodosReq into @CODIGO
	end
--------------------------------------------------

	DECLARE @str nvarchar(4000)

	SELECT @str = ' '
	IF  (@corte = 'Loc_Type') OR (@corte = 'Loc_Category')
		SET @str = @str + ' SELECT V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2, V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3,  V_DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
							V_DESCRIPCION AS MATRIZ,
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
							FROM VAR_NOCONFORMIDADES_VIEW '


	IF  (@corte = 'Usr_CausaPrimerNivel')  
		SET @str = @str + 'SELECT  distinct #TablaT.DESC_NIVEL1 AS CAUSA1, V_DESCRIPCION AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3, V_DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
							V_DESCRIPCION AS MATRIZ,
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
			FROM VAR_NOCONFORMIDADES_VIEW
			LEFT OUTER JOIN VARCHILD_NCCC_CAUSAS 
			ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_CAUSAS.CODIGONC
			LEFT OUTER JOIN #TablaT ON VARCHILD_NCCC_CAUSAS.CODIGO_CAUSA = #TablaT.CODIGO  ' 

	IF  (@corte = 'Usr_CausaSegundoNivel') 
		SET @str = @str + ' SELECT distinct V_DESCRIPCION AS CAUSA1, #TablaT.DESC_NIVEL2 AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3,  V_DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F,
							V_DESCRIPCION AS MATRIZ, 
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
			FROM VAR_NOCONFORMIDADES_VIEW
			LEFT OUTER JOIN VARCHILD_NCCC_CAUSAS 
			ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_CAUSAS.CODIGONC
			LEFT OUTER JOIN #TablaT ON VARCHILD_NCCC_CAUSAS.CODIGO_CAUSA = #TablaT.CODIGO  ' 

	IF (@corte = 'Usr_CausaTercerNivel')
		SET @str = @str + ' SELECT distinct V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
								 #TablaT.DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3,  V_DESCRIPCION AS AREA,
								V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
								V_DESCRIPCION AS MATRIZ,
								V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
								CARACTER, FECHADETECCION, TIPONC
				FROM VAR_NOCONFORMIDADES_VIEW
				LEFT OUTER JOIN VARCHILD_NCCC_CAUSAS 
				ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_CAUSAS.CODIGONC
				LEFT OUTER JOIN #TablaT ON VARCHILD_NCCC_CAUSAS.CODIGO_CAUSA = #TablaT.CODIGO  ' 


	IF  (@corte = 'Usr_RequisitoPrimerNivel')  
		SET @str = @str + 'SELECT distinct #TablaReq.DESC_NIVEL1 AS REQ1, V_DESCRIPCION AS REQ2,
							V_DESCRIPCION AS REQ3, V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
							V_DESCRIPCION AS MATRIZ,
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
			FROM VAR_NOCONFORMIDADES_VIEW
			LEFT OUTER JOIN VARCHILD_NCCC_REQNORMATIVOS 
			ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_REQNORMATIVOS.CODIGONC
			LEFT OUTER JOIN #TablaReq ON VARCHILD_NCCC_REQNORMATIVOS.CODIGO_REQUISITO_NORMATIVO = #TablaReq.CODIGO  ' 

	IF  (@corte = 'Usr_RequisitoSegundoNivel') 
		SET @str = @str + ' SELECT distinct V_DESCRIPCION AS REQ1, #TablaReq.DESC_NIVEL2 AS REQ2,
							V_DESCRIPCION AS REQ3, V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F,
							V_DESCRIPCION AS MATRIZ, 
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
			FROM VAR_NOCONFORMIDADES_VIEW
			LEFT OUTER JOIN VARCHILD_NCCC_REQNORMATIVOS 
			ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_REQNORMATIVOS.CODIGONC
			LEFT OUTER JOIN #TablaReq ON VARCHILD_NCCC_REQNORMATIVOS.CODIGO_REQUISITO_NORMATIVO = #TablaReq.CODIGO  ' 

	IF (@corte = 'Usr_RequisitoTercerNivel')
		SET @str = @str + ' SELECT distinct V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2,
								 #TablaReq.DESCRIPCION AS REQ3, V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
								V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS AREA,
								V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
								V_DESCRIPCION AS MATRIZ,
								V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
								CARACTER, FECHADETECCION, TIPONC
				FROM VAR_NOCONFORMIDADES_VIEW
				LEFT OUTER JOIN VARCHILD_NCCC_REQNORMATIVOS 
				ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_REQNORMATIVOS.CODIGONC
				LEFT OUTER JOIN #TablaReq ON VARCHILD_NCCC_REQNORMATIVOS.CODIGO_REQUISITO_NORMATIVO = #TablaReq.CODIGO  '
				
				
	IF (@corte = 'Usr_AreaResponsable') 
		SET @str = @str + ' SELECT  V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3,  TBL_AREA_CAUSAS.DESCRIPCION AS AREA,
							V_DESCRIPCION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
							V_DESCRIPCION AS MATRIZ,
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
		FROM VAR_NOCONFORMIDADES_VIEW LEFT OUTER JOIN VARCHILD_NCCC_AREAS
		ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_AREAS.CODIGONC
		LEFT OUTER JOIN TBL_AREA_CAUSAS ON  VARCHILD_NCCC_AREAS.CODIGOAREA = TBL_AREA_CAUSAS.CODIGO '


	IF (@corte = 'Usr_Proceso') 
		SET @str = @str + '  SELECT V_DESCRIPCION AS CAUSA1, V_DESCRIPCION AS CAUSA2,
							V_DESCRIPCION AS CAUSA3, V_DESCRIPCION AS REQ1, V_DESCRIPCION AS REQ2, V_DESCRIPCION AS REQ3,  V_DESCRIPCION AS AREA,
							PROC_NODES.DESCRIPTION AS PROCESO, V_DESCRIPCION AS MATRIZ_C, V_DESCRIPCION AS MATRIZ_F, 
							V_DESCRIPCION AS MATRIZ,
							V_CODIGO, V_ESTADO, V_DESCRIPCION, V_CATEGORIADESC, VAR_NOCONFORMIDADES_VIEW.CODIGONC, 
							CARACTER, FECHADETECCION, TIPONC
			FROM VAR_NOCONFORMIDADES_VIEW LEFT OUTER JOIN VARCHILD_NCCC_PROCESOS 
			ON VAR_NOCONFORMIDADES_VIEW.CODIGONC = VARCHILD_NCCC_PROCESOS.CODIGONC
			LEFT OUTER JOIN PROC_NODES 
			ON  VARCHILD_NCCC_PROCESOS.CODIGO_PROCESO = PROC_NODES.PROC_NODESID '

--- ************ FILTROS ************ ---	

	SET @str = @str + ' WHERE 1=1 '

	IF (@filtro_caracter <> '*')
		SET @str = @str + ' AND VAR_NOCONFORMIDADES_VIEW.CARACTER = ' + @filtro_caracter

	IF (@filtro_area <> '*')
		SET @str = @str + ' AND VAR_NOCONFORMIDADES_VIEW.CODIGONC IN 
									( SELECT VARCHILD_NCCC_AREAS.CODIGONC
									  FROM VARCHILD_NCCC_AREAS
									  LEFT OUTER JOIN TBL_AREA_CAUSAS 
									  ON  VARCHILD_NCCC_AREAS.CODIGOAREA = TBL_AREA_CAUSAS.CODIGO  
									  WHERE TBL_AREA_CAUSAS.CODIGO IN (' + @filtro_area	+ ')
			
							) '

	IF (@filtro_proceso <> '*')
		SET @str = @str + ' AND VAR_NOCONFORMIDADES_VIEW.CODIGONC IN 
							(	SELECT VARCHILD_NCCC_PROCESOS.CODIGONC
								FROM VARCHILD_NCCC_PROCESOS 
								LEFT OUTER JOIN PROC_NODES 
								ON  VARCHILD_NCCC_PROCESOS.CODIGO_PROCESO = PROC_NODES.PROC_NODESID
								WHERE PROC_NODES.PROC_NODESID IN (' + @filtro_proceso + ')
							 ) '

	IF (@filtro_causa <> '*')
		SET @str = @str + ' AND VAR_NOCONFORMIDADES_VIEW.CODIGONC IN
							(
								SELECT CODIGONC
								FROM VARCHILD_NCCC_CAUSAS
								WHERE VARCHILD_NCCC_CAUSAS.CODIGO_CAUSA IN ( '+ @filtro_causa + ')
							)'	

	IF (@filtro_requisito <> '*')
		SET @str = @str + ' AND VAR_NOCONFORMIDADES_VIEW.CODIGONC IN
							(
								SELECT CODIGONC
								FROM VARCHILD_NCCC_REQNORMATIVOS
								WHERE VARCHILD_NCCC_REQNORMATIVOS.CODIGO_REQUISITO_NORMATIVO IN ( '+ @filtro_requisito + ') 
							)'

	EXEC (@str)
	RETURN
GO
