SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_usrIns_DocGroupsByPerm]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_usrIns_DocGroupsByPerm] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_usrIns_DocGroupsByPerm]
@CODIGOUSUARIO INT, 
@NIVELACCESO INT 
AS
BEGIN


   IF (@NIVELACCESO = -1)
      select DISTINCT  M.DESCRIPCION, M.CODIGO,
		CASE 
			WHEN L_PUEDENUEVOS=1 THEN M.CAMINO + ' (New Allowed)'
			ELSE M.CAMINO
		END AS CAMINO,
	'Images/OpenedFolder.gif' AS SMALLGIF ,M.ORDEN
		FROM TBL_CATEGORIASDOCUMENTOS M
      JOIN NCMODULESECURITYLEVELS P ON P.CODIGOTIPONC = M.CODIGO+300000
      WHERE CODIGOUSUARIO = @CODIGOUSUARIO
      ORDER BY M.ORDEN
   ELSE
      select DISTINCT  M.DESCRIPCION, M.CODIGO,
		CASE 
			WHEN L_PUEDENUEVOS=1 THEN M.CAMINO + ' (New Allowed)'
			ELSE M.CAMINO
		END AS CAMINO,
	'Images/OpenedFolder.gif' AS SMALLGIF ,M.ORDEN
		FROM TBL_CATEGORIASDOCUMENTOS M
      JOIN NCMODULESECURITYLEVELS P ON P.CODIGOTIPONC = M.CODIGO+300000
      WHERE NIVELACCESO = @NIVELACCESO AND CODIGOUSUARIO = @CODIGOUSUARIO
      ORDER BY M.ORDEN


END
GO
