SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_get_ruta_padre]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_get_ruta_padre] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
-- ik_get_ruta_padre 4
ALTER PROCEDURE [dbo].[ik_get_ruta_padre]
(@Nodopadre int)
AS
		
	CREATE TABLE #TablaT (
    CODIGO int,	
	NOMBRE nvarchar(400),
	DESCRIPCION nvarchar(4000)
  )

	DECLARE @CODIGON int
	DECLARE @PADRE INT
	DECLARE @DESCRIPCION NVARCHAR(4000)
	DECLARE @DESC NVARCHAR(400)
	DECLARE @NOMBRE NVARCHAR(400)

	DECLARE CurNodos CURSOR LOCAL FAST_FORWARD for 
	SELECT CODIGO
	FROM TBL_NCCC_CAUSAS 
	WHERE CODIGO_PADRE = @Nodopadre

    open CurNodos
	fetch next from CurNodos into @CODIGON

	DECLARE @CODIGO_FIRST_NODE INT
	SELECT 	@CODIGO_FIRST_NODE = CODIGO FROM TBL_NCCC_CAUSAS WHERE CODIGO_PADRE = -1
	
	while @@FETCH_STATUS = 0
	begin
	
		SELECT @PADRE = CODIGO_PADRE, @DESCRIPCION = DESCRIPCION, @NOMBRE = DESCRIPCION FROM TBL_NCCC_CAUSAS 
		WHERE CODIGO = @CODIGON

        WHILE (@PADRE <> @CODIGO_FIRST_NODE)
		BEGIN
			SELECT @DESC = DESCRIPCION FROM TBL_NCCC_CAUSAS WHERE CODIGO = @PADRE
			SET @DESCRIPCION = dbo.CONCAT3(@DESC, '\', @DESCRIPCION)
			SELECT @PADRE = CODIGO_PADRE  FROM TBL_NCCC_CAUSAS WHERE CODIGO = @PADRE
		END 

		INSERT INTO #TablaT(CODIGO, DESCRIPCION, NOMBRE) 
		VALUES (@CODIGON, @DESCRIPCION, @NOMBRE)
		fetch next from CurNodos into @CODIGON
	end

	close CurNodos
	deallocate CurNodos

declare @sqlst varchar(8000)
set @sqlst = ' SELECT * FROM #TablaT '

EXEC(@sqlst)
GO
