SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_docs_types_for_new]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_docs_types_for_new] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_docs_types_for_new]
(@CodUser int, @IKPDO int, @IKCAT int, @IKGLST nvarchar(500))
AS

/*Check if the user is an IS-KEY administrator or Document administrator*/
IF @IKCAT=4 OR @IKPDO=0 
BEGIN
	SELECT CODIGO,DESCRIPCION,dbo.CONCAT3(RTRIM(TIPO),': ',RTRIM(DESCRIPCION)) AS TIPO FROM TIPOSDOCUMENTOS ORDER BY TIPO
	RETURN
END

IF (@IKGLST IS NULL) OR (LTRIM(RTRIM(@IKGLST)) = '')
	BEGIN
		SELECT DISTINCT t.CODIGO,t.DESCRIPCION,dbo.CONCAT3(RTRIM(t.TIPO),': ',RTRIM(t.DESCRIPCION)) AS TIPO
			FROM  TIPOSDOCUMENTOS t 
			LEFT OUTER JOIN TBL_RESTRICTED_AM_DOCTYPES R ON t.CODIGO=R.DOCTYPEID 
			WHERE R.CODIGO IS NULL OR USERID=@CodUser
			ORDER BY TIPO
	END
ELSE
	BEGIN
	DECLARE @ALL varchar(500)
	DECLARE @SQL varchar(1000)
	SET @ALL = @IKGLST + ',' + LTRIM(STR(@CodUser))
	SET @SQL='SELECT DISTINCT t.CODIGO,t.DESCRIPCION,dbo.CONCAT3(RTRIM(t.TIPO),'': '',RTRIM(t.DESCRIPCION)) AS TIPO
			FROM  TIPOSDOCUMENTOS t 
			LEFT OUTER JOIN TBL_RESTRICTED_AM_DOCTYPES R ON t.CODIGO=R.DOCTYPEID 
			WHERE R.CODIGO IS NULL OR USERID IN (' + @ALL +') ORDER BY TIPO'
	EXEC(@SQL)
	END
RETURN
GO
