SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_svgsIds_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_svgsIds_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_svgsIds_withaccess]
(
		@BSPROCCAT int,
		@IKCAT int,
		@IKCDU int,
		@tmp_table nvarchar(500) = '#TMP_SVG_WITH_ACCESS_IDS',
		@L_RETURN_DATA int = 1
	)

AS

SET DATEFORMAT YMD

DECLARE @strSQL varchar(4000), @where varchar(100)


SELECT @strSQL =
CASE	
	WHEN  @IKCAT=0 OR @BSPROCCAT=2  THEN
		'SELECT BS_SVGID FROM VISTA_SVG_DRAWINGS WHERE 1=0' /*select nothing*/
	WHEN @IKCAT=4 OR @BSPROCCAT=0 THEN
		'SELECT BS_SVGID FROM VISTA_SVG_DRAWINGS' /*select all*/
	ELSE /*Select only allowed docs*/
		
		'SELECT BS_SVGID FROM (
		SELECT * FROM VISTA_SVG_DRAWINGS		
		WHERE BS_SVGID IN (SELECT BS_SVGID FROM VISTA_BS_SVG_OPTIONS WHERE SEC_LEVEL>0 AND USERID='+ LTRIM(STR(@IKCDU)) +')
		OR BS_SVGID IN (SELECT BS_SVGID FROM VISTA_BS_SVG_OPTIONS WHERE SEC_LEVEL>0 AND USERID IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO='+ LTRIM(STR(@IKCDU)) +'))
		) AS SEC
		' 

END		

BEGIN TRY
	EXEC ('TRUNCATE TABLE ' + @tmp_table + '; ' + 'INSERT INTO '+ @tmp_table + ' ' +  @strSQL)
END TRY
BEGIN CATCH	
END CATCH



IF @L_RETURN_DATA = 1
BEGIN
	EXEC (@strSQL)
END




RETURN
GO
