SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_doc_allgroups_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_doc_allgroups_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_doc_allgroups_withaccess]
(
		@IKPDO int,
		@IKCAT int,
		@IKCDU int,
		@PARAMETERS varchar(8000)='',
		@SORT nvarchar(100)='CATEGORIADOCUMENTO'
	)

AS

SET DATEFORMAT YMD

DECLARE @strDOC varchar(4000)

IF LEN(@PARAMETERS)=0 SET @PARAMETERS='1=1'

SELECT @strDOC =
CASE	
	WHEN  @IKCAT=0 OR @IKPDO=2  THEN
		'SELECT * FROM TBL_CATEGORIASDOCUMENTOS WHERE CODIGO = 0 '		 /*select nothing*/
	WHEN @IKCAT=4 OR @IKPDO=0 THEN
		'SELECT * FROM TBL_CATEGORIASDOCUMENTOS WHERE '
			
	ELSE /*Select only allowed docs groups*/
		'SELECT * FROM TBL_CATEGORIASDOCUMENTOS 
			WHERE 
			    CODIGO NOT IN (
				SELECT CODIGOTIPONC-300000 FROM NCMODULESECURITYLEVELS 
					WHERE NIVELACCESO=300011 
					AND CODIGOUSUARIO='+ CONVERT(nvarchar(5),@IKCDU) +') 
			AND (CODIGO NOT IN (
				SELECT CODIGOTIPONC-300000 FROM NCMODULESECURITYLEVELS 
				WHERE NIVELACCESO=300011 
				AND CODIGOUSUARIO IN (
					SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS 
					WHERE CODIGOUSUARIO='+ CONVERT(nvarchar(5),@IKCDU) +')) 
				OR CODIGO IN (
					SELECT CODIGOTIPONC-300000 FROM NCMODULESECURITYLEVELS 
					WHERE NIVELACCESO=300010 
					AND CODIGOUSUARIO='+ CONVERT(nvarchar(5),@IKCDU) +')) 
			AND ' 
	
END		


IF NOT (@IKCAT=0 OR @IKPDO=2)
BEGIN
	IF @sort <> ''
	BEGIN
		SET @sort = ' ORDER BY ' + @sort
	END
	ELSE
	BEGIN
		SET @sort = ' ORDER BY [CATEGORIADOCUMENTO]'
	END
END


EXEC (@strDOC+@parameters+@sort)

RETURN
GO
