SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_mt_DocsWithNews]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_mt_DocsWithNews] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_mt_DocsWithNews]
(
		@IKCDU INT,
		@STRORDER varchar(50) = 'DOCCODE',
		@L_RETURN_RECORDS tinyint=1
	)

AS
	SET NOCOUNT ON

DECLARE @COUNT INT

IF @STRORDER='' SET @STRORDER='DOCCODE'

CREATE TABLE #TMP_FOROS(CODIGOFORO int, MENSAJES int, URGENTES INT, ARCHIVOS INT, RECORDATORIOS INT, LASTNEW int)
	


	INSERT INTO #TMP_FOROS(CODIGOFORO , MENSAJES, URGENTES, ARCHIVOS, RECORDATORIOS) 
		SELECT IKFOROSNOVEDADES.CODIGOFORO, 
		SUM(CASE WHEN IKFOROSNOVEDADES.CODIGOTIPOPENDIENTE = 1 AND M.CODIGOUSUARIO!=@IKCDU THEN 1 ELSE 0 END) AS MENSAJES,  
		SUM(CASE WHEN IKFOROSNOVEDADES.CODIGOTIPOPENDIENTE = 1 AND GRADOURGENCIA=1 THEN 1 ELSE 0 END) AS URGENTES,  
		SUM(CASE WHEN IKFOROSNOVEDADES.CODIGOTIPOPENDIENTE = 2 THEN 1 ELSE 0 END) AS ARCHIVOS,
		SUM(CASE WHEN IKFOROSNOVEDADES.CODIGOTIPOPENDIENTE = 1 AND M.CODIGOUSUARIO=@IKCDU THEN 1 ELSE 0 END) AS RECORDATORIOS
	FROM IKFOROSNOVEDADES 
	LEFT JOIN IKFOROSMENSAJES M 
		ON M.CODIGO = IKFOROSNOVEDADES.CODIGOPENDIENTE 
	WHERE IKFOROSNOVEDADES.CODIGOUSUARIO=@IKCDU AND L_LEIDO=0
	GROUP BY IKFOROSNOVEDADES.CODIGOFORO


	
UPDATE #TMP_FOROS SET LASTNEW=
(SELECT TOP 1 CODIGO FROM IKFOROSNOVEDADES WHERE IKFOROSNOVEDADES.CODIGOFORO=#TMP_FOROS.CODIGOFORO AND CODIGOUSUARIO=@IKCDU ORDER BY CODIGO DESC)

	

SELECT *,

CASE 
		WHEN ISNULL(NMCANT,0) >0  AND ISNULL(NUCANT,0) >0  THEN CONVERT(varchar,NMCANT) + ' {LOC-Loc_Message_Messages}&nbsp;<span class="CaptionVariableNicObligatoria"  title="({LOC-Urgent})" >*</span>'  
		WHEN ISNULL(NMCANT,0) >0  THEN CONVERT(varchar,NMCANT) + ' {LOC-Loc_Message_Messages}'  
		ELSE ''
	END AS NEWMESSAGES,

	 
	CASE 
		WHEN ISNULL(NFCANT,0) > 0   THEN  '<BR>' + CONVERT(varchar,NFCANT) + ' {LOC-Loc_File_Files}'  
		ELSE ''
		
	END AS NEWFILES,

	CASE 
		WHEN ISNULL(NMCANT,0) >0 OR ISNULL(NFCANT,0) > 0  THEN '<BR>' + 
			CASE WHEN ISNULL(NUCANT,0) >0  AND ISNULL(NRCANT,0)>0 THEN CONVERT(varchar,NRCANT)+ ' {LOC-Loc_Reminders}&nbsp;<span class="CaptionVariableNicObligatoria" title="({LOC-Urgent})">*</span>'
				WHEN ISNULL(NRCANT,0)>0  THEN CONVERT(varchar,NRCANT) + ' {LOC-Loc_Reminders}'  
				ELSE ''
			END
		ELSE 
			CASE 
				WHEN ISNULL(NUCANT,0) >0  AND ISNULL(NRCANT,0)>0 THEN CONVERT(varchar,NRCANT)+ ' {LOC-Loc_Reminders}&nbsp;<span class="CaptionVariableNicObligatoria" title="({LOC-Urgent})">*</span>'
				WHEN ISNULL(NRCANT,0)>0 THEN CONVERT(varchar,NRCANT) + ' {LOC-Loc_Reminders}'  
				ELSE ''
			END
	END AS NEWREMINDERS,




CASE
	WHEN ESTADO=0 OR ESTADO=1 THEN 'Images\Doc_Development.gif'
	WHEN ESTADO=2 THEN 'Images\Doc_Current.gif'
	WHEN ESTADO=3 THEN 'Images\Doc_Obsolete.gif'
END AS DOCICON,

CASE
	WHEN ESTADO=0 OR ESTADO=1 THEN '{LOC-Loc_Development}'
	WHEN ESTADO=2 THEN '{LOC-Loc_Current}'
	WHEN ESTADO=3 THEN '{LOC-Loc_Obsolete}'
END AS LOCSTATUS


INTO #ITASKS
 FROM (
SELECT CODIGO AS DOCCODE, ESTADO , NOMBRE, CODIGOISO, C_REVISION, REVISION, CODIGOFORODESARROLLO, CODIGOFOROCRITICAS ,
NM.MENSAJES AS NMCANT , NM.ARCHIVOS AS NFCANT , NM.RECORDATORIOS AS NRCANT, NM.URGENTES AS NUCANT,
'{LOC-Loc_Forum_Development}' as FORUM,
'DOCDEVFORUM' AS FORUMVIEW

,
ISNULL(NM.LASTNEW,0) AS LASTNEW
,D.CODIGOFORODESARROLLO AS CODIGOFORO
	

FROM DOCUMENTOS D

LEFT JOIN #TMP_FOROS NM ON NM.CODIGOFORO=D.CODIGOFORODESARROLLO


WHERE (
	(ISNULL(NM.MENSAJES,0) >0) OR (ISNULL(NM.ARCHIVOS,0) > 0) OR (ISNULL(NM.RECORDATORIOS,0)> 0)  
	) 


UNION 


SELECT CODIGO AS DOCCODE, ESTADO , NOMBRE, CODIGOISO, C_REVISION, REVISION, CODIGOFORODESARROLLO, CODIGOFOROCRITICAS ,
NM.MENSAJES AS NMCANT , NM.ARCHIVOS AS NFCANT , NM.RECORDATORIOS AS NRCANT, NM.URGENTES AS NUCANT,
'{LOC-Loc_Critics}' as FORUM,
'DOCCRITFORUM' AS FORUMVIEW
	
,
ISNULL(NM.LASTNEW,0) AS LASTNEW
,D.CODIGOFOROCRITICAS AS CODIGOFORO

FROM DOCUMENTOS D

LEFT JOIN #TMP_FOROS NM ON NM.CODIGOFORO=D.CODIGOFOROCRITICAS



WHERE (
	(ISNULL(NM.MENSAJES,0) >0) OR (ISNULL(NM.ARCHIVOS,0) > 0) OR (ISNULL(NM.RECORDATORIOS,0)> 0)  
	) 



) AS ITASKS


ORDER BY
CASE 
	WHEN @STRORDER='CODIGO' THEN DOCCODE
END,
CASE 
	WHEN @STRORDER='NAME' THEN NOMBRE
	WHEN @STRORDER='CODIGOISO' THEN CODIGOISO
END



SET @COUNT= (SELECT @@ROWCOUNT)
IF (@L_RETURN_RECORDS=1)
BEGIN
	SELECT * FROM #ITASKS
END

DROP TABLE #TMP_FOROS
	
RETURN @COUNT
GO
