SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_BS_FORMULA]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_BS_FORMULA] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_BS_FORMULA]
(
	@BS_INDICATORSID int,
	@TIME_PERIOD int,
	@RV_FORMULA varchar(max),
	@PV_FORMULA varchar(max),
	@CS_INVOLVED_INDICATORS varchar(300),
	@SJOINS varchar(max),
	@SWHERE varchar(max)
	)
AS
/* 

Valid @BS_TimePeriods
Daily = 1
Weekly = 2
Monthly = 3
Quarterly = 4
Semester = 6
Annualy = 5

*/
SET NOCOUNT ON

SET DATEFORMAT ymd
SET DATEFIRST 7

CREATE TABLE #TEMP_INDICATOR (
PERIODO int,
PLANNED_VALUE float,
ACTUAL_VALUE float,
SRC_INDICATOR int
)

DECLARE @SQL varchar(max)
DECLARE @GROUP_EXP varchar(1000)
DECLARE @FECHA_EXP varchar(1000)

	
SET @GROUP_EXP = 'dbo.ik_bs_Periods_Grouping('+LTRIM(STR(@TIME_PERIOD))+', P.MSR_DATE)'
SET @FECHA_EXP = 'dbo.ik_bs_Periods_GroupExp_ToDate('+LTRIM(STR(@TIME_PERIOD))+',R1.PERIODO)'

SET @SQL = '
INSERT INTO #TEMP_INDICATOR
SELECT '+ @GROUP_EXP +' AS PERIOD,
	   SUM(P.MSR_PLANNED_VALUE) AS PLANNED_VALUE,
	   SUM(P.MSR_REAL_VALUE) AS ACTUAL_VALUE,
	   REL.REL_BS_INDICATORSID

FROM  BS_INDICATORSREL REL
  INNER JOIN BS_INDICATORSDATA P
  ON REL.REL_BS_INDICATORSID = P.BS_INDICATORSID

WHERE REL.BS_INDICATORSID='+LTRIM(STR(@BS_INDICATORSID))+' AND REL.REL_BS_INDICATORSID IN ('+@CS_INVOLVED_INDICATORS+')

GROUP BY REL.REL_BS_INDICATORSID,' + @GROUP_EXP

EXEC(@SQL)

SET @SQL = '
SELECT '
+@RV_FORMULA+' AS MSR_REAL_VALUE, '
+@PV_FORMULA+' AS MSR_PLANNED_VALUE, 
' + @FECHA_EXP + ' AS MSR_DATE

FROM #TEMP_INDICATOR R1
'+@SJOINS+'
WHERE 
'+@SWHERE

EXEC(@SQL)

DROP TABLE #TEMP_INDICATOR

RETURN
GO
