SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_documentsgroups_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_documentsgroups_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_documentsgroups_withaccess]
(
		@IKPDO int,
		@IKCAT int,
		@IKCDU int
	)

AS

DECLARE @strDOC varchar(4000)


SELECT @strDOC =
CASE	
	WHEN  @IKCAT=0 OR @IKPDO=2  THEN
		'SELECT DISTINCT CODIGOCATEGORIADOCUMENTO,CATEGORIADOCUMENTO,CAMINO FROM VISTA_DOCUMENTOSCATEGORIAS WHERE CODIGODOCUMENTO = 0 ORDER BY CATEGORIADOCUMENTO' /*select nothing*/
	WHEN @IKCAT=4 OR @IKPDO=0 THEN
		'SELECT DISTINCT CODIGOCATEGORIADOCUMENTO,CATEGORIADOCUMENTO,CAMINO FROM VISTA_DOCUMENTOSCATEGORIAS ORDER BY CAMINO'
	ELSE /*Select only allowed docs*/
		'SELECT DISTINCT CODIGOCATEGORIADOCUMENTO,CATEGORIADOCUMENTO,CAMINO FROM VISTA_DOCUMENTOSCATEGORIAS WHERE CODIGODOCUMENTO IN 
			(
			SELECT PERMISOSDOC.CODIGODOCUMENTO  FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO 
			WHERE 
				(DOCUMENTOS.ESTADO=2 AND PERMISOSDOC.NIVELACCESO > 300000 AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ') ' + 
				'OR (DOCUMENTOS.ESTADO=1 AND PERMISOSDOC.NIVELACCESO > 300002 AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ') ' + 

			' UNION

			SELECT PERMISOSDOC.CODIGODOCUMENTO FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO 
			JOIN WEBGROUPMEMBERS ON WEBGROUPMEMBERS.CODIGOGRUPO = PERMISOSDOC.CODIGOUSUARIO
			WHERE ((DOCUMENTOS.ESTADO=2 AND PERMISOSDOC.NIVELACCESO > 300000 AND WEBGROUPMEMBERS.CODIGOUSUARIO =  ' + LTRIM(STR(@IKCDU)) + ') ' + 
			' OR  (DOCUMENTOS.ESTADO=1 AND PERMISOSDOC.NIVELACCESO > 300002 AND WEBGROUPMEMBERS.CODIGOUSUARIO =  ' + LTRIM(STR(@IKCDU)) + ') ' + 
			')
			AND
				PERMISOSDOC.CODIGODOCUMENTO NOT IN 
				( SELECT CODIGODOCUMENTO FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO WHERE (DOCUMENTOS.ESTADO=2  AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ' AND NIVELACCESO=300000) OR (DOCUMENTOS.ESTADO=1  AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ' AND NIVELACCESO<300003))
			) ORDER BY CAMINO
			'	
		
END		


EXEC (@strDOC)

RETURN
GO
