SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_PersonsIds_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_PersonsIds_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_PersonsIds_withaccess]
(		
		@IKCDU int,
		@tmp_table nvarchar(500) = '#TMP_PERSONS_WITH_ACCESS_IDS'
	)

AS

SET NOCOUNT ON
SET DATEFORMAT YMD

DECLARE @IKCAT INT
SELECT @IKCAT=CATEGORIA FROM USUARIOS WHERE CODIGO=@IKCDU


BEGIN TRY
	DROP TABLE #TMP_PERSONS  
END TRY
BEGIN CATCH
END CATCH

CREATE TABLE #TMP_PERSONS (IKPERSONID INT)


IF @IKCAT=0   
BEGIN
	INSERT INTO #TMP_PERSONS(IKPERSONID)
	SELECT CODIGO FROM PERSONAS WHERE 1=0
END
ELSE IF  @IKCAT=4 
BEGIN
	INSERT INTO #TMP_PERSONS(IKPERSONID)
	SELECT CODIGO FROM PERSONAS
END
ELSE
BEGIN
		BEGIN TRY
			DROP TABLE #TMP_GROUPS
		END TRY
		BEGIN CATCH
		END CATCH

		BEGIN TRY
			DROP TABLE #TMP_SEC_LEVELS
		END TRY
		BEGIN CATCH
		END CATCH

		SELECT CODIGOGRUPO INTO #TMP_GROUPS FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO=@IKCDU
		SELECT CODIGOTIPONC, NIVELACCESO INTO #TMP_SEC_LEVELS FROM NCMODULESECURITYLEVELS WHERE CODIGOUSUARIO=@IKCDU AND NCMODULESECURITYLEVELS.CODIGOTIPONC=98
		INSERT INTO #TMP_SEC_LEVELS (CODIGOTIPONC, NIVELACCESO) SELECT CODIGOTIPONC, MAX(NIVELACCESO)  FROM NCMODULESECURITYLEVELS WHERE NCMODULESECURITYLEVELS.CODIGOTIPONC=98 AND CODIGOUSUARIO IN (SELECT CODIGOGRUPO FROM #TMP_GROUPS) AND NOT CODIGOTIPONC IN (SELECT CODIGOTIPONC FROM #TMP_SEC_LEVELS ) GROUP BY CODIGOTIPONC

		
		BEGIN TRY
			DROP TABLE #TMP_PERSONS_INVOLVED
		END TRY
		BEGIN CATCH
		END CATCH

		SELECT @IKCDU AS IKPERSONID INTO #TMP_PERSONS_INVOLVED
		



	INSERT INTO #TMP_PERSONS(IKPERSONID)
	SELECT PE.CODIGO FROM #TMP_SEC_LEVELS 
		JOIN PERSONAS PE ON 98=#TMP_SEC_LEVELS.CODIGOTIPONC 
		LEFT JOIN #TMP_PERSONS_INVOLVED ON #TMP_PERSONS_INVOLVED.IKPERSONID = PE.CODIGO
	WHERE 
		#TMP_SEC_LEVELS.NIVELACCESO > 0
		AND	((#TMP_SEC_LEVELS.NIVELACCESO=2 AND NOT #TMP_PERSONS_INVOLVED.IKPERSONID IS NULL) OR (#TMP_SEC_LEVELS.NIVELACCESO>2 ))
	ORDER BY CODIGOTIPONC, NIVELACCESO
END


EXEC ('INSERT INTO ' + @tmp_table + ' (IKPERSONID ) SELECT IKPERSONID FROM  #TMP_PERSONS')


RETURN
GO
