SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_bsindicators_4userinput]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_bsindicators_4userinput] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_bsindicators_4userinput]
(
		@parameters nvarchar(500) =  '', /*WHERE CONDITIONS WITHOUT WHERE CLAUSE*/
		@sort nvarchar(50), /*WITHOUT CLAUSE ORDER BY*/
		@BSPROCCAT int,
		@IKCAT int,
		@IKCDU int
	)

AS

DECLARE @strSQL varchar(4000)


SELECT @strSQL =
CASE	
	WHEN  @IKCAT=0 OR @BSPROCCAT=2  THEN
		'SELECT *, ''Images/bs_indicador.gif'' AS ICONOINDICADOR, ''I-'' + LTRIM(STR(BS_INDICATORSID)) + '' '' + LOCATION + '': '' + DESCRIPTION AS FULLDESCRIPTION FROM VISTA_BS_INDICATORS WHERE 1=0' /*select nothing*/
	WHEN @IKCAT=4 OR @BSPROCCAT=0 THEN
		'SELECT *, ''Images/bs_indicador.gif'' AS ICONOINDICADOR, ''I-'' + LTRIM(STR(BS_INDICATORSID)) + '' '' + LOCATION + '': '' + DESCRIPTION AS FULLDESCRIPTION  FROM VISTA_BS_INDICATORS' /*select all*/
	ELSE /*Select only allowed indicators*/
		
		'SELECT *, ''Images/bs_indicador.gif'' AS ICONOINDICADOR, ''I-'' + LTRIM(STR(BS_INDICATORSID)) + '' '' + LOCATION + '': '' + DESCRIPTION AS FULLDESCRIPTION  FROM (
		SELECT * FROM VISTA_BS_INDICATORS
		WHERE 
		BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM BS_INDICATORS WHERE RESP_USERID='+ LTRIM(STR(@IKCDU)) +') 
		 OR BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SEC_LEVEL=5 AND USERID='+ LTRIM(STR(@IKCDU)) +')
		 OR BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SEC_LEVEL=5 AND USERID IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO='+ LTRIM(STR(@IKCDU)) +'))
		) AS SEC
		' 

END		

IF NOT (@IKCAT=0 OR @BSPROCCAT=2)
BEGIN
	IF @parameters <> ''
	BEGIN
		SET @strSQL = @strSQL + ' WHERE ' + @parameters
	END

	IF @sort <> ''
	BEGIN
		SET @strSQL = @strSQL + ' ORDER BY ' + @sort
	END
	ELSE
	BEGIN
		SET @strSQL = @strSQL + ' ORDER BY [DESCRIPTION]'
	END
END


EXEC (@strSQL)

RETURN
GO
