SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_mt_BSIndicators]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_mt_BSIndicators] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_mt_BSIndicators]
(
		@IKCDU INT,
		@STRORDER varchar(50) 
	)

AS
	SET NOCOUNT ON

IF LEN(@STRORDER)=0
BEGIN
	SET @STRORDER='1'
END


DECLARE @IKCAT int
DECLARE @BSCAT int

SELECT 	@IKCAT=CATEGORIA, @BSCAT=PERMISOSBSPROC FROM USUARIOS WHERE CODIGO=@IKCDU

DECLARE @STRSQL VARCHAR(2000)


IF @IKCAT=0 OR @BSCAT=2
BEGIN
	SET @STRSQL='SELECT ''I-'' + LTRIM(STR(BS_INDICATORSID)) + '' '' + LOCATION + '': '' + DESCRIPTION AS FULLDESCRIPTION , LOCATION,  BS_INDICATORSID, [DESCRIPTION], TIME_PERIOD, I.CATEGORY
		FROM VISTA_BS_INDICATORS I
		WHERE 1=0'
		EXEC (@STRSQL)
		RETURN
END
	
IF @IKCAT=4 OR @BSCAT=0 
BEGIN
		SET @STRSQL='SELECT DISTINCT ''I-'' + LTRIM(STR(I.BS_INDICATORSID)) + '' '' + I.LOCATION + '': '' + I.[DESCRIPTION] AS FULLDESCRIPTION  ,LOCATION, I.BS_INDICATORSID, I.[DESCRIPTION], I.TIME_PERIOD, I.CATEGORY
		FROM VISTA_BS_INDICATORS I JOIN VISTA_BS_INDICATORS_OPTIONS O ON O.BS_INDICATORSID=I.BS_INDICATORSID
		WHERE L_ACTIVE=1 AND O.SHOWINMYTASKS=1
		AND (I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1 AND USERID= ' + STR(@IKCDU) + ')
		OR I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1 AND USERID IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO=' + STR(@IKCDU) + ')))
		ORDER BY ' + @STRORDER
		EXEC (@STRSQL)
		RETURN
END
ELSE
BEGIN
	SET @STRSQL='SELECT DISTINCT ''I-'' + LTRIM(STR(I.BS_INDICATORSID)) + '' '' + I.LOCATION + '': '' + I.[DESCRIPTION] AS FULLDESCRIPTION  ,LOCATION, I.BS_INDICATORSID, I.[DESCRIPTION], I.TIME_PERIOD, I.CATEGORY
		FROM VISTA_BS_INDICATORS I JOIN VISTA_BS_INDICATORS_OPTIONS O ON O.BS_INDICATORSID=I.BS_INDICATORSID
		WHERE L_ACTIVE=1 AND O.SHOWINMYTASKS=1
		AND (I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1  AND SEC_LEVEL>0 AND USERID= ' + STR(@IKCDU) + ')
		OR I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1  AND SEC_LEVEL>0 AND USERID IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO=' + STR(@IKCDU) + ')))
		AND (NOT I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SEC_LEVEL=0 AND USERID= ' + STR(@IKCDU) + '))
		ORDER BY ' + @STRORDER
		EXEC (@STRSQL)
		RETURN

/*
		SET @STRSQL='SELECT ''I-'' + LTRIM(STR(BS_INDICATORSID)) + '' '' + LOCATION + '': '' + DESCRIPTION AS FULLDESCRIPTION , LOCATION , BS_INDICATORSID, [DESCRIPTION], TIME_PERIOD,  I.CATEGORY
		FROM VISTA_BS_INDICATORS I		
		WHERE L_ACTIVE=1 AND I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1 AND SEC_LEVEL>0 AND USERID= ' + STR(@IKCDU) + ')
		OR I.BS_INDICATORSID IN (SELECT BS_INDICATORSID FROM VISTA_BS_INDICATORS_OPTIONS WHERE SHOWINMYTASKS=1 AND SEC_LEVEL>0 AND USERID IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO=' + STR(@IKCDU) + '))
		ORDER BY ' + @STRORDER
		EXEC @STRSQL
		RETURN 
*/
END





	
RETURN
GO
