SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_ForumSearchInvolded]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_ForumSearchInvolded] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_ForumSearchInvolded]
@TEXTOBUSQUEDA nvarchar(1000),
	@IKCDU int
AS
BEGIN
--BRANCHED PROC
	SET NOCOUNT ON;

DECLARE @strSQL nvarchar(4000);

SET @TEXTOBUSQUEDA=REPLACE(@TEXTOBUSQUEDA, '''', '''''');

CREATE TABLE #TMP ([KEY] INT, [RANK] INT );

SET @strSQL = dbo.CONCAT3('
INSERT INTO #TMP
SELECT [KEY], [RANK]  FROM FREETEXTTABLE (IKFOROSMENSAJES,*, ''' , @TEXTOBUSQUEDA , ''' )')

EXEC (@strSQL)

SELECT TOP 100
[RANK],
CODIGO,
CODIGO AS [KEY],
DESCRIPCION,
INSTRUCCIONES,
CASE
  WHEN NCPCODE IS NULL THEN ''
  ELSE dbo.CONCAT('N-' , LTRIM(STR(NCPCODE)))
END    AS NCPCODE,
CASE
  WHEN NCTCODE IS NULL THEN ''
  ELSE dbo.CONCAT('T-', LTRIM(STR(NCTCODE)))
END             AS NCTCODE,
CASE
  WHEN DOCCODE IS NULL THEN ''
  ELSE dbo.CONCAT('D-' , LTRIM(STR(DOCCODE)))
END             AS DOCCODE,
CASE
  WHEN IKACTIONID IS NULL THEN ''
  ELSE dbo.CONCAT('X-' , LTRIM(STR(IKACTIONID)))
END             AS IKACTIONID,
USUARIO,
FECHA,
URL_NCPCODE,
URL_FORUM,
URL_FORUMMESSAGE,
URL_TASK,
URL_DOC,
URL_IKACTION
FROM VISTA_IKFOROSSEARCHINVOLVED
JOIN #TMP TBLSEARCH ON  VISTA_IKFOROSSEARCHINVOLVED.CODIGO = TBLSEARCH.[KEY]
WHERE ((SUSCRIPTOR=@IKCDU  AND NOT DESCRIPCION LIKE '@SUR%') )
ORDER BY [RANK] DESC, CODIGO DESC;




END
GO
