SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_docs_groups_for_new]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_docs_groups_for_new] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_docs_groups_for_new]
(@CodUser int, @IKPDO int, @IKCAT int, @IKGLST nvarchar(500))
AS

/*Check if the user is an IS-KEY administrator or Document administrator*/
IF @IKCAT=4 OR @IKPDO=0
BEGIN
	SELECT CODIGO,CAMINO AS DESCRIPCION,ORDEN FROM TBL_CATEGORIASDOCUMENTOS ORDER BY ORDEN
	RETURN
END

IF LTRIM(RTRIM(@IKGLST)) = ''
	BEGIN
		SELECT DISTINCT t.CODIGO,t.CAMINO AS DESCRIPCION,t.ORDEN
			FROM  TBL_CATEGORIASDOCUMENTOS t 
			INNER JOIN NCMODULESECURITYLEVELS n ON t.codigo = n.codigotiponc - 300000
			WHERE n.CODIGOUSUARIO = @CodUser
				AND n.L_PUEDENUEVOS = 1
			ORDER BY ORDEN
	END
ELSE
	BEGIN
	DECLARE @ALL varchar(500)
	DECLARE @SQL varchar(1000)
	SET @ALL = @IKGLST + ',' + LTRIM(STR(@CodUser))
	SET @SQL='SELECT DISTINCT t.CODIGO,t.CAMINO AS DESCRIPCION,t.ORDEN
			FROM  TBL_CATEGORIASDOCUMENTOS t 
			INNER JOIN NCMODULESECURITYLEVELS n ON t.codigo = n.codigotiponc - 300000
			WHERE n.CODIGOUSUARIO IN (' + @ALL +')
				AND n.L_PUEDENUEVOS = 1
			ORDER BY ORDEN'
	EXEC(@SQL)
	END
RETURN
GO
