SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_document_groups_in_document]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_document_groups_in_document] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_document_groups_in_document]
(@CodUser int,@CodDocument int, @IKPDO int, @IKCAT int, @IKGLST nvarchar(500))
AS

SELECT t.CODIGO AS CODIGO, t.DESCRIPCION 
		FROM DOCUMENTOSCATEGORIAS d INNER JOIN TBL_CATEGORIASDOCUMENTOS t
		ON d.CODIGOCATEGORIA = t.CODIGO
		WHERE d.CODIGODOCUMENTO = @CodDocument
		ORDER BY t.DESCRIPCION
	RETURN
GO
