SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_surveys_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_surveys_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_surveys_withaccess]
(
		@parameters varchar(8000) =  '', /*WHERE CONDITIONS WITHOUT WHERE CLAUSE*/
		@sort nvarchar(100), /*WITHOUT CLAUSE ORDER BY*/
		@IKPDO int,
		@IKCAT int,
		@IKCDU int
	)

AS

SET DATEFORMAT YMD

DECLARE @strDOC varchar(4000), @where varchar(100)


SELECT @strDOC =
CASE	
	WHEN  @IKCAT=0 OR @IKPDO=2  THEN
		'SELECT * FROM DOCUMENTOS WHERE CODIGO = 0' /*select nothing*/
	WHEN @IKCAT=4 OR @IKPDO=0 THEN
		'SELECT DOCUMENTOS.*,
		''ICONOESTADO'' = CASE
			WHEN (DOCUMENTOS.ESTADO=1) THEN ''Images/Doc_Development.gif''
			WHEN (DOCUMENTOS.ESTADO=2) THEN ''Images/Doc_Current.gif''
			ELSE ''Images/Doc_Obsolete.gif''
		END,
		''DOCCODE=''+LTRIM(STR(DOCUMENTOS.CODIGO))+''&STATUS=''+LTRIM(STR(DOCUMENTOS.ESTADO)) AS _URL_DATA,
		TIPOSDOCUMENTOS.DESCRIPCION AS TIPO_DESCRIPCION,
		 DOCUMENTOS.CODIGOISO + '' Rev.'' + LTRIM(STR(DOCUMENTOS.REVISION)) AS CODIGOREV,
		 DOCUMENTOS.CODIGOISO + '' Rev.'' + LTRIM(STR(DOCUMENTOS.REVISION))  + '' - '' + DOCUMENTOS.NOMBRE  AS NOMBRECOMPLETO, 
		 ESTADOSPROCESOS.DESCRIPCIONESTADO AS ESTADOPROCESO,
		SURVEYDEFINITIONS.TITULO,
		SURVEYDEFINITIONS.TIPOSURVEY,
		SURVEYDEFINITIONS.STARTED,
		SURVEYDEFINITIONS.DURATION,
		SURVEYDEFINITIONS.ENDED,
		SURVEYDEFINITIONS.L_READYTOSTART,
		SURVEYDEFINITIONS.SURVEY_UID,
		''SURVEYTYPE'' = CASE
			WHEN (SURVEYDEFINITIONS.TIPOSURVEY=1) THEN ''Loc_Anonymous''
			WHEN (SURVEYDEFINITIONS.TIPOSURVEY=2) THEN ''Loc_AnonymousCookies''			
			ELSE ''Loc_WithAuthentication''			
		END,
		''SURVEYSTATUS'' = CASE
			WHEN (SURVEYDEFINITIONS.ESTADO=1) THEN ''Loc_Not_Started''
			WHEN (SURVEYDEFINITIONS.ESTADO=2) THEN ''Loc_HasStarted''			
			ELSE ''Loc_Stage_Finished''			
		END

				
		 FROM DOCUMENTOS 
			JOIN TIPOSDOCUMENTOS ON DOCUMENTOS.CODIGOTIPO = TIPOSDOCUMENTOS.CODIGO 
			JOIN ESTADOSPROCESOS ON ESTADOSPROCESOS.CODIGOESTADO = DOCUMENTOS.PROCESO
			JOIN SURVEYDEFINITIONS ON DOCUMENTOS.CODIGOSURVEY=SURVEYDEFINITIONS.CODIGO
			' /*select all*/
		
	ELSE /*Select only allowed docs*/
		 		'SELECT DOCUMENTOS.*,
		''ICONOESTADO'' = CASE
			WHEN (DOCUMENTOS.ESTADO=1) THEN ''Images/Doc_Development.gif''
			WHEN (DOCUMENTOS.ESTADO=2) THEN ''Images/Doc_Current.gif''
			ELSE ''Images/Doc_Obsolete.gif''
		END,
		''DOCCODE=''+LTRIM(STR(CODIGODOCUMENTO))+''&STATUS=''+LTRIM(STR(DOCUMENTOS.ESTADO)) AS _URL_DATA,
		TIPOSDOCUMENTOS.DESCRIPCION AS TIPO_DESCRIPCION,
  	        DOCUMENTOS.CODIGOISO + '' Rev.'' + LTRIM(STR(DOCUMENTOS.REVISION)) AS CODIGOREV,
		 DOCUMENTOS.CODIGOISO + '' Rev.'' + LTRIM(STR(DOCUMENTOS.REVISION))  + '' - '' + DOCUMENTOS.NOMBRE  AS NOMBRECOMPLETO, 
		 ESTADOSPROCESOS.DESCRIPCIONESTADO AS ESTADOPROCESO,
		SURVEYDEFINITIONS.TITULO,
		SURVEYDEFINITIONS.TIPOSURVEY,
		SURVEYDEFINITIONS.STARTED,
		SURVEYDEFINITIONS.DURATION,
		SURVEYDEFINITIONS.ENDED,
		SURVEYDEFINITIONS.L_READYTOSTART,
		SURVEYDEFINITIONS.SURVEY_UID,
		''SURVEYTYPE'' = CASE
			WHEN (SURVEYDEFINITIONS.TIPOSURVEY=1) THEN ''Loc_Anonymous''
			WHEN (SURVEYDEFINITIONS.TIPOSURVEY=2) THEN ''Loc_AnonymousCookies''			
			ELSE ''Loc_WithAuthentication''			
		END,
		''SURVEYSTATUS'' = CASE
			WHEN (SURVEYDEFINITIONS.ESTADO=1) THEN ''Loc_Not_Started''
			WHEN (SURVEYDEFINITIONS.ESTADO=2) THEN ''Loc_HasStarted''			
			ELSE ''Loc_Stage_Finished''			
		END


		 		 FROM  (
			SELECT PERMISOSDOC.CODIGODOCUMENTO  FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO 
			WHERE 
				(DOCUMENTOS.ESTADO=2 AND PERMISOSDOC.NIVELACCESO > 300000 AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ') ' + 
				'OR (DOCUMENTOS.ESTADO=1 AND PERMISOSDOC.NIVELACCESO > 300002 AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ') ' + 

			' UNION

			SELECT PERMISOSDOC.CODIGODOCUMENTO FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO 
			WHERE 
				( (DOCUMENTOS.ESTADO=2 AND PERMISOSDOC.NIVELACCESO > 300000 AND PERMISOSDOC.CODIGOUSUARIO IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO='+ LTRIM(STR(@IKCDU)) + '))
				 OR
				 (DOCUMENTOS.ESTADO=1 AND PERMISOSDOC.NIVELACCESO > 300002 AND PERMISOSDOC.CODIGOUSUARIO IN (SELECT CODIGOGRUPO FROM WEBGROUPMEMBERS WHERE CODIGOUSUARIO='+ LTRIM(STR(@IKCDU)) + ')) 
				)
			AND
				PERMISOSDOC.CODIGODOCUMENTO NOT IN 
				( SELECT CODIGODOCUMENTO FROM PERMISOSDOC JOIN DOCUMENTOS ON DOCUMENTOS.CODIGO = PERMISOSDOC.CODIGODOCUMENTO WHERE (DOCUMENTOS.ESTADO=2  AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ' AND NIVELACCESO=300000) OR (DOCUMENTOS.ESTADO=1  AND CODIGOUSUARIO=' + LTRIM(STR(@IKCDU)) + ' AND NIVELACCESO<300003))
			)D JOIN DOCUMENTOS 
					JOIN TIPOSDOCUMENTOS ON DOCUMENTOS.CODIGOTIPO = TIPOSDOCUMENTOS.CODIGO ON D.CODIGODOCUMENTO = DOCUMENTOS.CODIGO 
					JOIN ESTADOSPROCESOS ON ESTADOSPROCESOS.CODIGOESTADO = DOCUMENTOS.PROCESO
					JOIN SURVEYDEFINITIONS ON DOCUMENTOS.CODIGOSURVEY=SURVEYDEFINITIONS.CODIGO
				
			'	
							
		
END		

SET @where = ''
IF NOT (@IKCAT=0 OR @IKPDO=2)
BEGIN
	IF @parameters <> ''
	BEGIN
		SET @where = ' WHERE '
	END

	IF @sort <> ''
	BEGIN
		SET @sort = ' ORDER BY ' + @sort
	END
	ELSE
	BEGIN
		SET @sort = ' ORDER BY DOCUMENTOS.CODIGO'
	END
END
 

EXEC (@strDOC+@where+@parameters+@sort)

RETURN
GO
