SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_procnodesreldocs_withaccess]') IS NULL EXEC('CREATE PROCEDURE [dbo].[ik_procnodesreldocs_withaccess] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[ik_procnodesreldocs_withaccess]
(
		@parameters varchar(8000) =  '', /*WHERE CONDITIONS WITHOUT WHERE CLAUSE*/
		@sort nvarchar(100), /*WITHOUT CLAUSE ORDER BY*/
		@BSPROCCAT int,
		@IKCAT int,
		@IKCDU int
	)

AS

SET DATEFORMAT YMD

DECLARE @strDOC varchar(4000), @where varchar(100)


SET  @strDOC ='
CREATE TABLE #TMP_DOCS_WITH_ACCESS_IDS (CODIGODOC int, NIVELACCESO INT)
EXEC dbo.[ik_DocumentsIds_withaccess]  ' + CONVERT(nvarchar(5),@IKCDU) + '

CREATE TABLE #TMP_PROCNODES_WITH_ACCESS_IDS (PROC_NODESID int)		
EXEC dbo.[ik_procNodesIds_withaccess]  ' + CONVERT(nvarchar(5),@BSPROCCAT) + ',' + CONVERT(nvarchar(5),@IKCAT) + ', ' + CONVERT(nvarchar(5),@IKCDU) + ',''#TMP_PROCNODES_WITH_ACCESS_IDS'',0


SELECT 
DISTINCT PROC_PLANSID, PROCNODES_ID, PROCNODES_DESCRIPTION, PROCNODES_NODEIMG 
FROM VISTA_ALLRELS_DOCUMENTS_PROCNODE NODESDOCS
JOIN dbo.PROC_NODES NODES ON NODESDOCS.PROCNODES_ID=NODES.PROC_NODESID
JOIN #TMP_PROCNODES_WITH_ACCESS_IDS ON #TMP_PROCNODES_WITH_ACCESS_IDS.PROC_NODESID=NODESDOCS.PROCNODES_ID
JOIN #TMP_DOCS_WITH_ACCESS_IDS ON #TMP_DOCS_WITH_ACCESS_IDS.CODIGODOC=NODESDOCS.DOCUMENT_ID
'

SET @where = ''
IF NOT (@IKCAT=0 OR @BSPROCCAT=2)
BEGIN
	IF @parameters <> ''
	BEGIN
		SET @where = ' WHERE '
	END

	IF @sort <> ''
	BEGIN
		SET @sort = ' ORDER BY ' + @sort
	END
	ELSE
	BEGIN
		SET @sort = ' ORDER BY [DESCRIPTION]'
	END

	EXEC (@strDOC+@where+@parameters+@sort)
END
ELSE
BEGIN
	EXEC (@strDOC)
END

--print @strDOC+@where+@parameters+@sort



RETURN
GO
