
GO
--SqlScripter----[dbo].[PC_DBOBJECT].[FK_PC_DBOBJECT_PC_].sql
GO
ALTER TABLE [dbo].[PC_DBOBJECT] WITH NOCHECK ADD CONSTRAINT [FK_PC_DBOBJECT_PC_] FOREIGN KEY ([PCA_ORMSTATE_ID])
REFERENCES [dbo].[PC_ORMSTATE] ([PCO_ORMSTATEID])
GO
ALTER TABLE [dbo].[PC_DBOBJECT] WITH CHECK CHECK CONSTRAINT [FK_PC_DBOBJECT_PC_]
GO
--SqlScripter----[dbo].[PC_ICLASS_SIG].[FK_PC_ICLASS_SIG_P].sql
GO
ALTER TABLE [dbo].[PC_ICLASS_SIG] WITH NOCHECK ADD CONSTRAINT [FK_PC_ICLASS_SIG_P] FOREIGN KEY ([PCI_PACKAGE])
REFERENCES [dbo].[PC_PACKAGE] ([PCP_PKGID])
GO
ALTER TABLE [dbo].[PC_ICLASS_SIG] WITH CHECK CHECK CONSTRAINT [FK_PC_ICLASS_SIG_P]
GO
--SqlScripter----[dbo].[PC_NAMESPACE].[FK_PC_NAMESPACE_PC].sql
GO
ALTER TABLE [dbo].[PC_NAMESPACE] WITH NOCHECK ADD CONSTRAINT [FK_PC_NAMESPACE_PC] FOREIGN KEY ([PCN_REPOSIG])
REFERENCES [dbo].[PC_REPOSITORY] ([PCR_SIGNATURE])
GO
ALTER TABLE [dbo].[PC_NAMESPACE] WITH CHECK CHECK CONSTRAINT [FK_PC_NAMESPACE_PC]
GO
--SqlScripter----[dbo].[PC_NAMESPACE_SEQUENCE].[FK_PC_NAMESPACE_SE].sql
GO
ALTER TABLE [dbo].[PC_NAMESPACE_SEQUENCE] WITH NOCHECK ADD CONSTRAINT [FK_PC_NAMESPACE_SE] FOREIGN KEY ([PCA_NAMESPACE])
REFERENCES [dbo].[PC_NAMESPACE] ([PCN_NSID])
GO
ALTER TABLE [dbo].[PC_NAMESPACE_SEQUENCE] WITH CHECK CHECK CONSTRAINT [FK_PC_NAMESPACE_SE]
GO
--SqlScripter----[dbo].[PC_PACKAGE].[FK_PC_PACKAGE_PC_R].sql
GO
ALTER TABLE [dbo].[PC_PACKAGE] WITH NOCHECK ADD CONSTRAINT [FK_PC_PACKAGE_PC_R] FOREIGN KEY ([PCP_REPOSIG])
REFERENCES [dbo].[PC_REPOSITORY] ([PCR_SIGNATURE])
GO
ALTER TABLE [dbo].[PC_PACKAGE] WITH CHECK CHECK CONSTRAINT [FK_PC_PACKAGE_PC_R]
GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[FK_PR_ATTRIBUTE_PR].sql
GO
ALTER TABLE [dbo].[PR_ATTRIBUTE] WITH NOCHECK ADD CONSTRAINT [FK_PR_ATTRIBUTE_PR] FOREIGN KEY ([PRA_RESOURCE])
REFERENCES [dbo].[PR_RESOURCE] ([PRR_ID])
GO
ALTER TABLE [dbo].[PR_ATTRIBUTE] WITH CHECK CHECK CONSTRAINT [FK_PR_ATTRIBUTE_PR]
GO
--SqlScripter----[dbo].[PR_GANNOTATIONS].[FK_PR_GANNOTATIONS].sql
GO
ALTER TABLE [dbo].[PR_GANNOTATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PR_GANNOTATIONS] FOREIGN KEY ([PRA_RESOURCE])
REFERENCES [dbo].[PR_RESOURCE] ([PRR_ID])
GO
ALTER TABLE [dbo].[PR_GANNOTATIONS] WITH CHECK CHECK CONSTRAINT [FK_PR_GANNOTATIONS]
GO
--SqlScripter----[dbo].[PR_RESOURCE].[FK_PR_RESOURCE_PR_].sql
GO
ALTER TABLE [dbo].[PR_RESOURCE] WITH NOCHECK ADD CONSTRAINT [FK_PR_RESOURCE_PR_] FOREIGN KEY ([PRR_PARENTCONTAINER])
REFERENCES [dbo].[PR_RESOURCE] ([PRR_ID])
GO
ALTER TABLE [dbo].[PR_RESOURCE] WITH CHECK CHECK CONSTRAINT [FK_PR_RESOURCE_PR_]