
GO
--SqlScripter----[dbo].[APROBACIONES].[FK_APROBACIONES_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[APROBACIONES] WITH NOCHECK ADD CONSTRAINT [FK_APROBACIONES_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[APROBACIONES] WITH CHECK CHECK CONSTRAINT [FK_APROBACIONES_DOCUMENTOS]
GO
--SqlScripter----[dbo].[APROBACIONES].[FK_APROBACIONES_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[APROBACIONES] WITH NOCHECK ADD CONSTRAINT [FK_APROBACIONES_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGO])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[APROBACIONES] WITH CHECK CHECK CONSTRAINT [FK_APROBACIONES_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[ARCHIVOS].[FK_ARCHIVOS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[ARCHIVOS] WITH NOCHECK ADD CONSTRAINT [FK_ARCHIVOS_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[ARCHIVOS] WITH CHECK CHECK CONSTRAINT [FK_ARCHIVOS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[AUDITEDS].[FK_AUDITEDS_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[AUDITEDS] WITH NOCHECK ADD CONSTRAINT [FK_AUDITEDS_AUDITORIAS] FOREIGN KEY ([AUDIT_ID])
REFERENCES [dbo].[AUDITORIAS] ([CODIGO])
GO
ALTER TABLE [dbo].[AUDITEDS] WITH CHECK CHECK CONSTRAINT [FK_AUDITEDS_AUDITORIAS]
GO
--SqlScripter----[dbo].[AUDITORIAS].[FK_AUDITORIAS_AUDITORIASTIPOS].sql
GO
ALTER TABLE [dbo].[AUDITORIAS] WITH NOCHECK ADD CONSTRAINT [FK_AUDITORIAS_AUDITORIASTIPOS] FOREIGN KEY ([CODIGOTIPO])
REFERENCES [dbo].[AUDITORIASTIPOS] ([CODIGO])
GO
ALTER TABLE [dbo].[AUDITORIAS] WITH CHECK CHECK CONSTRAINT [FK_AUDITORIAS_AUDITORIASTIPOS]
GO
--SqlScripter----[dbo].[AUDITORIAS].[FK_AUDITORIAS_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[AUDITORIAS] WITH NOCHECK ADD CONSTRAINT [FK_AUDITORIAS_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGOADMINISTRADOR])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[AUDITORIAS] WITH CHECK CHECK CONSTRAINT [FK_AUDITORIAS_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[AUDITORIASARCHIVOS].[FK_AUDITORIASARCHIVOS_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[AUDITORIASARCHIVOS] WITH NOCHECK ADD CONSTRAINT [FK_AUDITORIASARCHIVOS_AUDITORIAS] FOREIGN KEY ([CODIGOMARCO])
REFERENCES [dbo].[AUDITORIAS] ([CODIGO])
GO
ALTER TABLE [dbo].[AUDITORIASARCHIVOS] WITH CHECK CHECK CONSTRAINT [FK_AUDITORIASARCHIVOS_AUDITORIAS]
GO
--SqlScripter----[dbo].[AUDITORS].[FK_AUDITORS_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[AUDITORS] WITH NOCHECK ADD CONSTRAINT [FK_AUDITORS_AUDITORIAS] FOREIGN KEY ([AUDIT_ID])
REFERENCES [dbo].[AUDITORIAS] ([CODIGO])
GO
ALTER TABLE [dbo].[AUDITORS] WITH CHECK CHECK CONSTRAINT [FK_AUDITORS_AUDITORIAS]
GO
--SqlScripter----[dbo].[BS_IND_ASSESMENTS].[FK_BS_IND_ASSESMENTS_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_IND_ASSESMENTS] WITH NOCHECK ADD CONSTRAINT [FK_BS_IND_ASSESMENTS_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_IND_ASSESMENTS] WITH CHECK CHECK CONSTRAINT [FK_BS_IND_ASSESMENTS_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_IND_STATE_CACHE].[FK_BS_IND_STATE_CACHE_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_IND_STATE_CACHE] WITH NOCHECK ADD CONSTRAINT [FK_BS_IND_STATE_CACHE_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_IND_STATE_CACHE] WITH CHECK CHECK CONSTRAINT [FK_BS_IND_STATE_CACHE_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_INDICATORS].[FK_BS_INDICATORS_BS_INDICATORSCATEGORIES].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_BS_INDICATORSCATEGORIES] FOREIGN KEY ([BS_INDICATORSCATEGORIESID])
REFERENCES [dbo].[BS_INDICATORSCATEGORIES] ([BS_INDICATORSCATEGORIESID])
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_BS_INDICATORSCATEGORIES]
GO
--SqlScripter----[dbo].[BS_INDICATORS].[FK_BS_INDICATORS_BS_LOCATIONS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_BS_LOCATIONS] FOREIGN KEY ([BS_LOCATIONSID])
REFERENCES [dbo].[BS_LOCATIONS] ([BS_LOCATIONSID])
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_BS_LOCATIONS]
GO
--SqlScripter----[dbo].[BS_INDICATORS].[FK_BS_INDICATORS_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_ORGANIGRAMA] FOREIGN KEY ([OWNER_RANKID])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[BS_INDICATORS].[FK_BS_INDICATORS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_USUARIOS] FOREIGN KEY ([RESP_USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_INDICATORS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_USUARIOS]
GO
--SqlScripter----[dbo].[BS_INDICATORS_DATA_ARCHIVED_RE].[FK_BS_INDICATORS_DATA_ARCH#532C78B26B3C962B90D3E652EE73B070].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS_DATA_ARCHIVED_RE] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_DATA_ARCHIVED_RECORDS_BS_INDICATORS_DATA_ARCHIVED] FOREIGN KEY ([BS_INDICATORS_DATA_ARCHIVEDID])
REFERENCES [dbo].[BS_INDICATORS_DATA_ARCHIVED] ([BS_INDICATORS_DATA_ARCHIVEDID])
GO
ALTER TABLE [dbo].[BS_INDICATORS_DATA_ARCHIVED_RE] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_DATA_ARCHIVED_RECORDS_BS_INDICATORS_DATA_ARCHIVED]
GO
--SqlScripter----[dbo].[BS_INDICATORS_NOTIFICATIONS].[FK_BS_INDICATORS_NOTIFICATIONS_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS_NOTIFICATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_NOTIFICATIONS_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_INDICATORS_NOTIFICATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_NOTIFICATIONS_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_INDICATORS_NOTIFICATIONS].[FK_BS_INDICATORS_NOTIFICATIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS_NOTIFICATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_NOTIFICATIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_INDICATORS_NOTIFICATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_NOTIFICATIONS_USUARIOS]
GO
--SqlScripter----[dbo].[BS_INDICATORS_OPTIONS].[FK_BS_INDICATORS_OPTIONS_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_OPTIONS_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_INDICATORS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_OPTIONS_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_INDICATORS_OPTIONS].[FK_BS_INDICATORS_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORS_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_INDICATORS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORS_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[BS_INDICATORSDATA].[FK_BS_INDICATORSDATA_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORSDATA] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORSDATA_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_INDICATORSDATA] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORSDATA_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_INDICATORSREL].[FK_BS_INDICATORSREL_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[BS_INDICATORSREL] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORSREL_BS_INDICATORS] FOREIGN KEY ([BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_INDICATORSREL] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORSREL_BS_INDICATORS]
GO
--SqlScripter----[dbo].[BS_INDICATORSREL].[FK_BS_INDICATORSREL_BS_INDICATORS1].sql
GO
ALTER TABLE [dbo].[BS_INDICATORSREL] WITH NOCHECK ADD CONSTRAINT [FK_BS_INDICATORSREL_BS_INDICATORS1] FOREIGN KEY ([REL_BS_INDICATORSID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[BS_INDICATORSREL] WITH CHECK CHECK CONSTRAINT [FK_BS_INDICATORSREL_BS_INDICATORS1]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES].[FK_BS_STRAT_NODES_BS_LOCATIONS].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_BS_LOCATIONS] FOREIGN KEY ([BS_LOCATIONSID])
REFERENCES [dbo].[BS_LOCATIONS] ([BS_LOCATIONSID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_BS_LOCATIONS]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES].[FK_BS_STRAT_NODES_BS_STRAT_NODETYPES].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_BS_STRAT_NODETYPES] FOREIGN KEY ([BS_STRAT_NODE_TYPESID])
REFERENCES [dbo].[BS_STRAT_NODE_TYPES] ([BS_STRAT_NODE_TYPESID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_BS_STRAT_NODETYPES]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES].[FK_BS_STRAT_NODES_BS_STRAT_PLANS].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_BS_STRAT_PLANS] FOREIGN KEY ([BS_STRAT_PLANSID])
REFERENCES [dbo].[BS_STRAT_PLANS] ([BS_STRAT_PLANSID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_BS_STRAT_PLANS]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES].[FK_BS_STRAT_NODES_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_IKI_MASTER]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_OPTIONS].[FK_BS_STRAT_NODES_OPTIONS_BS_STRAT_NODES].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_OPTIONS_BS_STRAT_NODES] FOREIGN KEY ([BS_STRAT_NODESID])
REFERENCES [dbo].[BS_STRAT_NODES] ([BS_STRAT_NODESID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_OPTIONS_BS_STRAT_NODES]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_OPTIONS].[FK_BS_STRAT_NODES_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS].[FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES] FOREIGN KEY ([BS_STRAT_NODESID_SOURCE])
REFERENCES [dbo].[BS_STRAT_NODES] ([BS_STRAT_NODESID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS].[FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_STRENGHT].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_STRENGHT] FOREIGN KEY ([BS_STRAT_NODES_RELS_STRENGTHID])
REFERENCES [dbo].[BS_STRAT_NODES_RELS_STRENGTH] ([BS_STRAT_NODES_RELS_STRENGTHID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_STRENGHT]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS].[FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_TYPES].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_TYPES] FOREIGN KEY ([BS_STRAT_NODES_RELS_TYPESID])
REFERENCES [dbo].[BS_STRAT_NODES_RELATIONS_TYPES] ([BS_STRAT_NODES_RELS_TYPESID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES_RELATIONS_TYPES]
GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS].[FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES1].sql
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES1] FOREIGN KEY ([BS_STRAT_NODESID_TARGET])
REFERENCES [dbo].[BS_STRAT_NODES] ([BS_STRAT_NODESID])
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_NODES_RELATIONS_BS_STRAT_NODES1]
GO
--SqlScripter----[dbo].[BS_STRAT_PLANS_OPTIONS].[FK_BS_STRAT_PLANS_OPTIONS_BS_STRAT_PLANS].sql
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_PLANS_OPTIONS_BS_STRAT_PLANS] FOREIGN KEY ([BS_STRAT_PLANSID])
REFERENCES [dbo].[BS_STRAT_PLANS] ([BS_STRAT_PLANSID])
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_PLANS_OPTIONS_BS_STRAT_PLANS]
GO
--SqlScripter----[dbo].[BS_STRAT_PLANS_OPTIONS].[FK_BS_STRAT_PLANS_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_STRAT_PLANS_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_STRAT_PLANS_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[BS_SVG].[FK_BS_SVG_SVG_TYPES].sql
GO
ALTER TABLE [dbo].[BS_SVG] WITH NOCHECK ADD CONSTRAINT [FK_BS_SVG_SVG_TYPES] FOREIGN KEY ([SVG_TYPESID])
REFERENCES [dbo].[SVG_TYPES] ([SVG_TYPESID])
GO
ALTER TABLE [dbo].[BS_SVG] WITH CHECK CHECK CONSTRAINT [FK_BS_SVG_SVG_TYPES]
GO
--SqlScripter----[dbo].[BS_SVG_OPTIONS].[FK_BS_SVG_OPTIONS_BS_SVG].sql
GO
ALTER TABLE [dbo].[BS_SVG_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_SVG_OPTIONS_BS_SVG] FOREIGN KEY ([BS_SVGID])
REFERENCES [dbo].[BS_SVG] ([BS_SVGID])
GO
ALTER TABLE [dbo].[BS_SVG_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_SVG_OPTIONS_BS_SVG]
GO
--SqlScripter----[dbo].[BS_SVG_OPTIONS].[FK_BS_SVG_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[BS_SVG_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_BS_SVG_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[BS_SVG_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_BS_SVG_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[CARGOSUSUARIOS].[FK_CARGOSUSUARIOS_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[CARGOSUSUARIOS] WITH NOCHECK ADD CONSTRAINT [FK_CARGOSUSUARIOS_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGO])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[CARGOSUSUARIOS] WITH CHECK CHECK CONSTRAINT [FK_CARGOSUSUARIOS_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[CARGOSUSUARIOS].[FK_CARGOSUSUARIOS_USUARIOS].sql
GO
ALTER TABLE [dbo].[CARGOSUSUARIOS] WITH NOCHECK ADD CONSTRAINT [FK_CARGOSUSUARIOS_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[CARGOSUSUARIOS] WITH CHECK CHECK CONSTRAINT [FK_CARGOSUSUARIOS_USUARIOS]
GO
--SqlScripter----[dbo].[CRITICAS].[FK_CRITICAS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[CRITICAS] WITH NOCHECK ADD CONSTRAINT [FK_CRITICAS_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[CRITICAS] WITH CHECK CHECK CONSTRAINT [FK_CRITICAS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[CRITICAS].[FK_CRITICAS_TIPOSCRITICAS].sql
GO
ALTER TABLE [dbo].[CRITICAS] WITH NOCHECK ADD CONSTRAINT [FK_CRITICAS_TIPOSCRITICAS] FOREIGN KEY ([CODIGOCRITICA])
REFERENCES [dbo].[TIPOSCRITICAS] ([CODIGO])
GO
ALTER TABLE [dbo].[CRITICAS] WITH CHECK CHECK CONSTRAINT [FK_CRITICAS_TIPOSCRITICAS]
GO
--SqlScripter----[dbo].[DISTRIBUCION].[FK_DISTRIBUCION_DISTRIBUCION].sql
GO
ALTER TABLE [dbo].[DISTRIBUCION] WITH NOCHECK ADD CONSTRAINT [FK_DISTRIBUCION_DISTRIBUCION] FOREIGN KEY ([CODIGODISTRIBUIDOR])
REFERENCES [dbo].[DISTRIBUCION] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[DISTRIBUCION] NOCHECK CONSTRAINT [FK_DISTRIBUCION_DISTRIBUCION]
GO
--SqlScripter----[dbo].[DISTRIBUCION].[FK_DISTRIBUCION_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DISTRIBUCION] WITH NOCHECK ADD CONSTRAINT [FK_DISTRIBUCION_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DISTRIBUCION] WITH CHECK CHECK CONSTRAINT [FK_DISTRIBUCION_DOCUMENTOS]
GO
--SqlScripter----[dbo].[DISTRIBUCION].[FK_DISTRIBUCION_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[DISTRIBUCION] WITH NOCHECK ADD CONSTRAINT [FK_DISTRIBUCION_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGO])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[DISTRIBUCION] WITH CHECK CHECK CONSTRAINT [FK_DISTRIBUCION_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_DOCUMENTOS] FOREIGN KEY ([CODIGOBASADOEN])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_ESTADOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_ESTADOS] FOREIGN KEY ([ESTADO])
REFERENCES [dbo].[ESTADOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_ESTADOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_ESTADOSPROCESOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_ESTADOSPROCESOS] FOREIGN KEY ([PROCESO])
REFERENCES [dbo].[ESTADOSPROCESOS] ([CODIGOESTADO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_ESTADOSPROCESOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_IKFOROS_CRITICAS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_IKFOROS_CRITICAS] FOREIGN KEY ([CODIGOFOROCRITICAS])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_IKFOROS_CRITICAS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_IKFOROS_DESARROLLO].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_IKFOROS_DESARROLLO] FOREIGN KEY ([CODIGOFORODESARROLLO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_IKFOROS_DESARROLLO]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_PROCESOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_PROCESOS] FOREIGN KEY ([PROCESOREVISA])
REFERENCES [dbo].[PROCESOS] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_PROCESOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_PROCESOS1].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_PROCESOS1] FOREIGN KEY ([PROCESOAPRUEBA])
REFERENCES [dbo].[PROCESOS] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_PROCESOS1]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_PROCESOS2].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_PROCESOS2] FOREIGN KEY ([PROCESODISTRIBUYE])
REFERENCES [dbo].[PROCESOS] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[DOCUMENTOS] NOCHECK CONSTRAINT [FK_DOCUMENTOS_PROCESOS2]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_TIPOSDOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_TIPOSDOCUMENTOS] FOREIGN KEY ([CODIGOTIPO])
REFERENCES [dbo].[TIPOSDOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_TIPOSDOCUMENTOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS].[FK_DOCUMENTOS_USUARIOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_USUARIOS] FOREIGN KEY ([USUARIORESPONSABLE])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_USUARIOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS_CHANGELOG].[FK_DOCUMENTOS_CHANGELOG_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS_CHANGELOG] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_CHANGELOG_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS_CHANGELOG] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_CHANGELOG_DOCUMENTOS]
GO
--SqlScripter----[dbo].[DOCUMENTOS_CHANGELOG].[FK_DOCUMENTOS_CHANGELOG_TBL_DOCUMENT_CHANGELOG_TYPES].sql
GO
ALTER TABLE [dbo].[DOCUMENTOS_CHANGELOG] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOS_CHANGELOG_TBL_DOCUMENT_CHANGELOG_TYPES] FOREIGN KEY ([CHANGELOG_TYPE])
REFERENCES [dbo].[TBL_DOCUMENT_CHANGELOG_TYPES] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOS_CHANGELOG] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOS_CHANGELOG_TBL_DOCUMENT_CHANGELOG_TYPES]
GO
--SqlScripter----[dbo].[DOCUMENTOSHISTORIA].[FK_DOCUMENTOSHISTORIA_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOSHISTORIA] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOSHISTORIA_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DOCUMENTOSHISTORIA] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOSHISTORIA_DOCUMENTOS]
GO
--SqlScripter----[dbo].[DOCUMENTOSREL].[FK_DOCUMENTOSREL_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOSREL] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOSREL_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOSREL] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOSREL_DOCUMENTOS]
GO
--SqlScripter----[dbo].[DOCUMENTOSRELTRANS].[FK_DOCUMENTOSRELTRANS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[DOCUMENTOSRELTRANS] WITH NOCHECK ADD CONSTRAINT [FK_DOCUMENTOSRELTRANS_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[DOCUMENTOSRELTRANS] WITH CHECK CHECK CONSTRAINT [FK_DOCUMENTOSRELTRANS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[IK_PEOPLE].[FK_USUARIOS_USUARIOS].sql
GO
ALTER TABLE [dbo].[IK_PEOPLE] WITH NOCHECK ADD CONSTRAINT [FK_USUARIOS_USUARIOS] FOREIGN KEY ([CODIGOGRUPO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[IK_PEOPLE] NOCHECK CONSTRAINT [FK_USUARIOS_USUARIOS]
GO
--SqlScripter----[dbo].[IKFOROSARCHIVOS].[FK_IKFOROSARCHIVOS_IKFOROS].sql
GO
ALTER TABLE [dbo].[IKFOROSARCHIVOS] WITH NOCHECK ADD CONSTRAINT [FK_IKFOROSARCHIVOS_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[IKFOROSARCHIVOS] WITH CHECK CHECK CONSTRAINT [FK_IKFOROSARCHIVOS_IKFOROS]
GO
--SqlScripter----[dbo].[IKFOROSMENSAJES].[FK_IKFOROSMENSAJES_IKFOROS].sql
GO
ALTER TABLE [dbo].[IKFOROSMENSAJES] WITH NOCHECK ADD CONSTRAINT [FK_IKFOROSMENSAJES_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[IKFOROSMENSAJES] WITH CHECK CHECK CONSTRAINT [FK_IKFOROSMENSAJES_IKFOROS]
GO
--SqlScripter----[dbo].[IKFOROSNOVEDADES].[FK_IKFOROSNOVEDADES_IKFOROS].sql
GO
ALTER TABLE [dbo].[IKFOROSNOVEDADES] WITH NOCHECK ADD CONSTRAINT [FK_IKFOROSNOVEDADES_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[IKFOROSNOVEDADES] WITH CHECK CHECK CONSTRAINT [FK_IKFOROSNOVEDADES_IKFOROS]
GO
--SqlScripter----[dbo].[IKFOROSNOVEDADES].[FK_IKFOROSNOVEDADES_USUARIOS].sql
GO
ALTER TABLE [dbo].[IKFOROSNOVEDADES] WITH NOCHECK ADD CONSTRAINT [FK_IKFOROSNOVEDADES_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[IKFOROSNOVEDADES] WITH CHECK CHECK CONSTRAINT [FK_IKFOROSNOVEDADES_USUARIOS]
GO
--SqlScripter----[dbo].[IKFOROSSUSCRIPTORES].[FK_IKFOROSSUSCRIPTORES_IKFOROS].sql
GO
ALTER TABLE [dbo].[IKFOROSSUSCRIPTORES] WITH NOCHECK ADD CONSTRAINT [FK_IKFOROSSUSCRIPTORES_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[IKFOROSSUSCRIPTORES] WITH CHECK CHECK CONSTRAINT [FK_IKFOROSSUSCRIPTORES_IKFOROS]
GO
--SqlScripter----[dbo].[IKI_BSINDICATORS].[FK_IKI_BSINDICATORS_BS_INDICATORS].sql
GO
ALTER TABLE [dbo].[IKI_BSINDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_BSINDICATORS_BS_INDICATORS] FOREIGN KEY ([I_ID])
REFERENCES [dbo].[BS_INDICATORS] ([BS_INDICATORSID])
GO
ALTER TABLE [dbo].[IKI_BSINDICATORS] WITH CHECK CHECK CONSTRAINT [FK_IKI_BSINDICATORS_BS_INDICATORS]
GO
--SqlScripter----[dbo].[IKI_BSINDICATORS].[FK_IKI_BSINDICATORS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_BSINDICATORS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_BSINDICATORS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_BSINDICATORS] WITH CHECK CHECK CONSTRAINT [FK_IKI_BSINDICATORS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_BSSTRATPLANS].[FK_IKI_BSSTRATPLANS_BS_STRAT_PLANS].sql
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_BSSTRATPLANS_BS_STRAT_PLANS] FOREIGN KEY ([SPLAN_ID])
REFERENCES [dbo].[BS_STRAT_PLANS] ([BS_STRAT_PLANSID])
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH CHECK CHECK CONSTRAINT [FK_IKI_BSSTRATPLANS_BS_STRAT_PLANS]
GO
--SqlScripter----[dbo].[IKI_BSSTRATPLANS].[FK_IKI_BSSTRATPLANS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_BSSTRATPLANS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH CHECK CHECK CONSTRAINT [FK_IKI_BSSTRATPLANS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_BSSTRATPLANS].[FK_IKI_BSSTRATPLANS_IKI_MASTER1].sql
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_BSSTRATPLANS_IKI_MASTER1] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] WITH CHECK CHECK CONSTRAINT [FK_IKI_BSSTRATPLANS_IKI_MASTER1]
GO
--SqlScripter----[dbo].[IKI_DOCUMENTS].[FK_IKI_DOCUMENTOS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[IKI_DOCUMENTS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_DOCUMENTOS_DOCUMENTOS] FOREIGN KEY ([D_ID])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[IKI_DOCUMENTS] WITH CHECK CHECK CONSTRAINT [FK_IKI_DOCUMENTOS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[IKI_DOCUMENTS].[FK_IKI_DOCUMENTOS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_DOCUMENTS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_DOCUMENTOS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_DOCUMENTS] WITH CHECK CHECK CONSTRAINT [FK_IKI_DOCUMENTOS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_FILES].[FK_IKI_FILES_IKFILES].sql
GO
ALTER TABLE [dbo].[IKI_FILES] WITH NOCHECK ADD CONSTRAINT [FK_IKI_FILES_IKFILES] FOREIGN KEY ([F_ID])
REFERENCES [dbo].[IKFILES] ([IKFILESID])
GO
ALTER TABLE [dbo].[IKI_FILES] WITH CHECK CHECK CONSTRAINT [FK_IKI_FILES_IKFILES]
GO
--SqlScripter----[dbo].[IKI_FILES].[FK_IKI_FILES_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_FILES] WITH NOCHECK ADD CONSTRAINT [FK_IKI_FILES_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_FILES] WITH CHECK CHECK CONSTRAINT [FK_IKI_FILES_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_ISSUES].[FK_IKI_ISSUES_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_ISSUES] WITH NOCHECK ADD CONSTRAINT [FK_IKI_ISSUES_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_ISSUES] WITH CHECK CHECK CONSTRAINT [FK_IKI_ISSUES_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_ISSUES].[FK_IKI_ISSUES_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[IKI_ISSUES] WITH NOCHECK ADD CONSTRAINT [FK_IKI_ISSUES_NCMAINPROD] FOREIGN KEY ([N_ID])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[IKI_ISSUES] WITH CHECK CHECK CONSTRAINT [FK_IKI_ISSUES_NCMAINPROD]
GO
--SqlScripter----[dbo].[IKI_NAXCHARTS].[FK_IKI_NAXCHARTS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_NAXCHARTS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_NAXCHARTS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_NAXCHARTS] WITH CHECK CHECK CONSTRAINT [FK_IKI_NAXCHARTS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_ORGCHART].[FK_IKI_ORGCHART_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_ORGCHART] WITH NOCHECK ADD CONSTRAINT [FK_IKI_ORGCHART_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_ORGCHART] WITH CHECK CHECK CONSTRAINT [FK_IKI_ORGCHART_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_ORGCHART].[FK_IKI_ORGCHART_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[IKI_ORGCHART] WITH NOCHECK ADD CONSTRAINT [FK_IKI_ORGCHART_ORGANIGRAMA] FOREIGN KEY ([O_ID])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[IKI_ORGCHART] WITH CHECK CHECK CONSTRAINT [FK_IKI_ORGCHART_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[IKI_PROCPLANS].[FK_IKI_PROCPLANS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_PROCPLANS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_PROCPLANS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_PROCPLANS] WITH CHECK CHECK CONSTRAINT [FK_IKI_PROCPLANS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKI_PROCPLANS].[FK_IKI_PROCPLANS_PROC_PLANS].sql
GO
ALTER TABLE [dbo].[IKI_PROCPLANS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_PROCPLANS_PROC_PLANS] FOREIGN KEY ([PPLAN_ID])
REFERENCES [dbo].[PROC_PLANS] ([PROC_PLANSID])
GO
ALTER TABLE [dbo].[IKI_PROCPLANS] WITH CHECK CHECK CONSTRAINT [FK_IKI_PROCPLANS_PROC_PLANS]
GO
--SqlScripter----[dbo].[IKI_SVGDRAWINGS].[FK_IKI_SVGDRAWINGS_BS_SVG].sql
GO
ALTER TABLE [dbo].[IKI_SVGDRAWINGS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_SVGDRAWINGS_BS_SVG] FOREIGN KEY ([SVG_ID])
REFERENCES [dbo].[BS_SVG] ([BS_SVGID])
GO
ALTER TABLE [dbo].[IKI_SVGDRAWINGS] WITH CHECK CHECK CONSTRAINT [FK_IKI_SVGDRAWINGS_BS_SVG]
GO
--SqlScripter----[dbo].[IKI_SVGDRAWINGS].[FK_IKI_SVGDRAWINGS_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[IKI_SVGDRAWINGS] WITH NOCHECK ADD CONSTRAINT [FK_IKI_SVGDRAWINGS_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[IKI_SVGDRAWINGS] WITH CHECK CHECK CONSTRAINT [FK_IKI_SVGDRAWINGS_IKI_MASTER]
GO
--SqlScripter----[dbo].[IKNOTIFICACIONES].[FK_IKNOTIFICACIONES_USUARIOS].sql
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES] WITH NOCHECK ADD CONSTRAINT [FK_IKNOTIFICACIONES_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES] WITH CHECK CHECK CONSTRAINT [FK_IKNOTIFICACIONES_USUARIOS]
GO
--SqlScripter----[dbo].[IKNOTIFICACIONES_PROFILES].[FK_IKNOTIFICACIONES_PROFILES_IKPROFILES].sql
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES_PROFILES] WITH NOCHECK ADD CONSTRAINT [FK_IKNOTIFICACIONES_PROFILES_IKPROFILES] FOREIGN KEY ([IKPROFILESID])
REFERENCES [dbo].[IKPROFILES] ([IKPROFILESID])
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES_PROFILES] WITH CHECK CHECK CONSTRAINT [FK_IKNOTIFICACIONES_PROFILES_IKPROFILES]
GO
--SqlScripter----[dbo].[IKPOSITIONSGROUPS].[FK_IKPOSITIONSGROUPS_IKPOSITIONSGROUPSTREE].sql
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPS] WITH NOCHECK ADD CONSTRAINT [FK_IKPOSITIONSGROUPS_IKPOSITIONSGROUPSTREE] FOREIGN KEY ([IKPOSITIONSGROUPSTREEID])
REFERENCES [dbo].[IKPOSITIONSGROUPSTREE] ([IKPOSITIONSGROUPSTREEID])
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPS] WITH CHECK CHECK CONSTRAINT [FK_IKPOSITIONSGROUPS_IKPOSITIONSGROUPSTREE]
GO
--SqlScripter----[dbo].[IKPOSITIONSGROUPS].[FK_IKPOSITIONSGROUPS_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPS] WITH NOCHECK ADD CONSTRAINT [FK_IKPOSITIONSGROUPS_ORGANIGRAMA] FOREIGN KEY ([POSITIONID])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPS] WITH CHECK CHECK CONSTRAINT [FK_IKPOSITIONSGROUPS_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[MARCODOCUMENTOSREL].[FK_MARCODOCUMENTOSREL_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[MARCODOCUMENTOSREL] WITH NOCHECK ADD CONSTRAINT [FK_MARCODOCUMENTOSREL_AUDITORIAS] FOREIGN KEY ([CODIGOMARCO])
REFERENCES [dbo].[AUDITORIAS] ([CODIGO])
GO
ALTER TABLE [dbo].[MARCODOCUMENTOSREL] WITH CHECK CHECK CONSTRAINT [FK_MARCODOCUMENTOSREL_AUDITORIAS]
GO
--SqlScripter----[dbo].[NC_FILES].[FK_ARCHIVOSASUNTOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NC_FILES] WITH NOCHECK ADD CONSTRAINT [FK_ARCHIVOSASUNTOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NC_FILES] WITH CHECK CHECK CONSTRAINT [FK_ARCHIVOSASUNTOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCCOSTOS].[FK_NCCOSTOS_NCCOSTOSCATEGORIAS].sql
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH NOCHECK ADD CONSTRAINT [FK_NCCOSTOS_NCCOSTOSCATEGORIAS] FOREIGN KEY ([CODIGOCATEGORIA])
REFERENCES [dbo].[NCCOSTOSCATEGORIAS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH CHECK CHECK CONSTRAINT [FK_NCCOSTOS_NCCOSTOSCATEGORIAS]
GO
--SqlScripter----[dbo].[NCCOSTOS].[FK_NCCOSTOS_NCCOSTOSCLASES].sql
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH NOCHECK ADD CONSTRAINT [FK_NCCOSTOS_NCCOSTOSCLASES] FOREIGN KEY ([CODIGOCLASE])
REFERENCES [dbo].[NCCOSTOSCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH CHECK CHECK CONSTRAINT [FK_NCCOSTOS_NCCOSTOSCLASES]
GO
--SqlScripter----[dbo].[NCCOSTOS].[FK_NCCOSTOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH NOCHECK ADD CONSTRAINT [FK_NCCOSTOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCCOSTOS] WITH CHECK CHECK CONSTRAINT [FK_NCCOSTOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCETAPAS].[FK_NCETAPAS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NCETAPAS] WITH NOCHECK ADD CONSTRAINT [FK_NCETAPAS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCETAPAS] WITH CHECK CHECK CONSTRAINT [FK_NCETAPAS_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCINTERRELACIONES].[FK_NCINTERRELACIONES_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NCINTERRELACIONES] WITH NOCHECK ADD CONSTRAINT [FK_NCINTERRELACIONES_NCMAINPROD] FOREIGN KEY ([CODIGOASUNTOORIGEN])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCINTERRELACIONES] WITH CHECK CHECK CONSTRAINT [FK_NCINTERRELACIONES_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCINTERRELACIONES].[FK_NCINTERRELACIONES_NCMAINPROD1].sql
GO
ALTER TABLE [dbo].[NCINTERRELACIONES] WITH NOCHECK ADD CONSTRAINT [FK_NCINTERRELACIONES_NCMAINPROD1] FOREIGN KEY ([CODIGOASUNTORELACIONADO])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCINTERRELACIONES] WITH CHECK CHECK CONSTRAINT [FK_NCINTERRELACIONES_NCMAINPROD1]
GO
--SqlScripter----[dbo].[NCINVOLUCRADOS].[FK_NCINVOLUCRADOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NCINVOLUCRADOS] WITH NOCHECK ADD CONSTRAINT [FK_NCINVOLUCRADOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCINVOLUCRADOS] WITH CHECK CHECK CONSTRAINT [FK_NCINVOLUCRADOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCINVOLUCRADOS].[FK_NCINVOLUCRADOS_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[NCINVOLUCRADOS] WITH NOCHECK ADD CONSTRAINT [FK_NCINVOLUCRADOS_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGO])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[NCINVOLUCRADOS] WITH CHECK CHECK CONSTRAINT [FK_NCINVOLUCRADOS_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[NCMAINPROD].[FK_NCMAINPROD_IKFOROS].sql
GO
ALTER TABLE [dbo].[NCMAINPROD] WITH NOCHECK ADD CONSTRAINT [FK_NCMAINPROD_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCMAINPROD] NOCHECK CONSTRAINT [FK_NCMAINPROD_IKFOROS]
GO
--SqlScripter----[dbo].[NCMAINPROD].[FK_NCMAINPROD_NCESTADOS].sql
GO
ALTER TABLE [dbo].[NCMAINPROD] WITH NOCHECK ADD CONSTRAINT [FK_NCMAINPROD_NCESTADOS] FOREIGN KEY ([ESTADO])
REFERENCES [dbo].[NCESTADOS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCMAINPROD] WITH CHECK CHECK CONSTRAINT [FK_NCMAINPROD_NCESTADOS]
GO
--SqlScripter----[dbo].[NCMAINPROD].[FK_NCMAINPROD_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[NCMAINPROD] WITH NOCHECK ADD CONSTRAINT [FK_NCMAINPROD_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGOADMINISTRADOR])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[NCMAINPROD] WITH CHECK CHECK CONSTRAINT [FK_NCMAINPROD_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[NCMODULESECURITYLEVELS].[FK_NCMODULESECURITYLEVELS_NCSECURITYLEVELSDESCRIPTION].sql
GO
ALTER TABLE [dbo].[NCMODULESECURITYLEVELS] WITH NOCHECK ADD CONSTRAINT [FK_NCMODULESECURITYLEVELS_NCSECURITYLEVELSDESCRIPTION] FOREIGN KEY ([NIVELACCESO])
REFERENCES [dbo].[NCSECURITYLEVELSDESCRIPTION] ([NIVEL])
GO
ALTER TABLE [dbo].[NCMODULESECURITYLEVELS] WITH CHECK CHECK CONSTRAINT [FK_NCMODULESECURITYLEVELS_NCSECURITYLEVELSDESCRIPTION]
GO
--SqlScripter----[dbo].[NCMODULESECURITYLEVELS].[FK_NCMODULESECURITYLEVELS_USUARIOS].sql
GO
ALTER TABLE [dbo].[NCMODULESECURITYLEVELS] WITH NOCHECK ADD CONSTRAINT [FK_NCMODULESECURITYLEVELS_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[NCMODULESECURITYLEVELS] WITH CHECK CHECK CONSTRAINT [FK_NCMODULESECURITYLEVELS_USUARIOS]
GO
--SqlScripter----[dbo].[NCTAREAS].[FK_NCTAREAS_IKFOROS].sql
GO
ALTER TABLE [dbo].[NCTAREAS] WITH NOCHECK ADD CONSTRAINT [FK_NCTAREAS_IKFOROS] FOREIGN KEY ([CODIGOFORO])
REFERENCES [dbo].[IKFOROS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCTAREAS] NOCHECK CONSTRAINT [FK_NCTAREAS_IKFOROS]
GO
--SqlScripter----[dbo].[NCTAREAS].[FK_NCTAREAS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[NCTAREAS] WITH NOCHECK ADD CONSTRAINT [FK_NCTAREAS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[NCTAREAS] WITH CHECK CHECK CONSTRAINT [FK_NCTAREAS_NCMAINPROD]
GO
--SqlScripter----[dbo].[NCTAREAS].[FK_NCTAREAS_NCTAREAS].sql
GO
ALTER TABLE [dbo].[NCTAREAS] WITH NOCHECK ADD CONSTRAINT [FK_NCTAREAS_NCTAREAS] FOREIGN KEY ([CODIGOTAREACONDICIONAL])
REFERENCES [dbo].[NCTAREAS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCTAREAS] WITH CHECK CHECK CONSTRAINT [FK_NCTAREAS_NCTAREAS]
GO
--SqlScripter----[dbo].[NCTAREAS].[FK_NCTAREAS_TASKSCATEGORIES].sql
GO
ALTER TABLE [dbo].[NCTAREAS] WITH NOCHECK ADD CONSTRAINT [FK_NCTAREAS_TASKSCATEGORIES] FOREIGN KEY ([TASKSCATEGORIES_ID])
REFERENCES [dbo].[TASKSCATEGORIES] ([TASKSCATEGORIES_ID])
GO
ALTER TABLE [dbo].[NCTAREAS] WITH CHECK CHECK CONSTRAINT [FK_NCTAREAS_TASKSCATEGORIES]
GO
--SqlScripter----[dbo].[NCTAREASDESTINATARIOS].[FK_NCTAREASDESTINATARIOS_NCTAREAS].sql
GO
ALTER TABLE [dbo].[NCTAREASDESTINATARIOS] WITH NOCHECK ADD CONSTRAINT [FK_NCTAREASDESTINATARIOS_NCTAREAS] FOREIGN KEY ([CODIGOTAREA])
REFERENCES [dbo].[NCTAREAS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCTAREASDESTINATARIOS] WITH CHECK CHECK CONSTRAINT [FK_NCTAREASDESTINATARIOS_NCTAREAS]
GO
--SqlScripter----[dbo].[NCTASKSSTEPS].[FK_NCTASKSSTEPS_NCTAREAS].sql
GO
ALTER TABLE [dbo].[NCTASKSSTEPS] WITH NOCHECK ADD CONSTRAINT [FK_NCTASKSSTEPS_NCTAREAS] FOREIGN KEY ([NCTASKID])
REFERENCES [dbo].[NCTAREAS] ([CODIGO])
GO
ALTER TABLE [dbo].[NCTASKSSTEPS] WITH CHECK CHECK CONSTRAINT [FK_NCTASKSSTEPS_NCTAREAS]
GO
--SqlScripter----[dbo].[ORGANIGRAMA].[FK_ORGANIGRAMA_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[ORGANIGRAMA] WITH NOCHECK ADD CONSTRAINT [FK_ORGANIGRAMA_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[ORGANIGRAMA] WITH CHECK CHECK CONSTRAINT [FK_ORGANIGRAMA_IKI_MASTER]
GO
--SqlScripter----[dbo].[ORGANIGRAMA].[FK_ORGANIGRAMA_LUGARES].sql
GO
ALTER TABLE [dbo].[ORGANIGRAMA] WITH NOCHECK ADD CONSTRAINT [FK_ORGANIGRAMA_LUGARES] FOREIGN KEY ([CODIGOLUGAR])
REFERENCES [dbo].[LUGARES] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[ORGANIGRAMA] NOCHECK CONSTRAINT [FK_ORGANIGRAMA_LUGARES]
GO
--SqlScripter----[dbo].[ORGANIGRAMA].[FK_ORGANIGRAMA_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[ORGANIGRAMA] WITH NOCHECK ADD CONSTRAINT [FK_ORGANIGRAMA_ORGANIGRAMA] FOREIGN KEY ([CODIGOPADRE])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[ORGANIGRAMA] NOCHECK CONSTRAINT [FK_ORGANIGRAMA_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[PERMISOSDOC].[FK_PERMISOSDOC_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[PERMISOSDOC] WITH NOCHECK ADD CONSTRAINT [FK_PERMISOSDOC_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[PERMISOSDOC] WITH CHECK CHECK CONSTRAINT [FK_PERMISOSDOC_DOCUMENTOS]
GO
--SqlScripter----[dbo].[PERMISOSDOC].[FK_PERMISOSDOC_USUARIOS].sql
GO
ALTER TABLE [dbo].[PERMISOSDOC] WITH NOCHECK ADD CONSTRAINT [FK_PERMISOSDOC_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[PERMISOSDOC] WITH CHECK CHECK CONSTRAINT [FK_PERMISOSDOC_USUARIOS]
GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS].[FK_PROC_FLOW_RELATIONS_PROC_FLOW_RELATIONS_ELEMENTS].sql
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_FLOW_RELATIONS_ELEMENTS] FOREIGN KEY ([PROC_FLOW_RELS_ELEMENTSID])
REFERENCES [dbo].[PROC_FLOW_RELATIONS_ELEMENTS] ([PROC_FLOW_RELS_ELEMENTSID])
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_FLOW_RELATIONS_ELEMENTS]
GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS].[FK_PROC_FLOW_RELATIONS_PROC_NODES].sql
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES] FOREIGN KEY ([PROC_NODESID_SOURCE])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES]
GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS].[FK_PROC_FLOW_RELATIONS_PROC_NODES_RELATIONS_STRENGTH].sql
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES_RELATIONS_STRENGTH] FOREIGN KEY ([PROC_NODES_RELS_STRENGTHID])
REFERENCES [dbo].[PROC_NODES_RELATIONS_STRENGTH] ([PROC_NODES_RELS_STRENGTHID])
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES_RELATIONS_STRENGTH]
GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS].[FK_PROC_FLOW_RELATIONS_PROC_NODES1].sql
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES1] FOREIGN KEY ([PROC_NODESID_TARGET])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_FLOW_RELATIONS_PROC_NODES1]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_BS_LOCATIONS].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_BS_LOCATIONS] FOREIGN KEY ([BS_LOCATIONSID])
REFERENCES [dbo].[BS_LOCATIONS] ([BS_LOCATIONSID])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_BS_LOCATIONS]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_IKI_MASTER].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_IKI_MASTER] FOREIGN KEY ([IKI_MASTERID])
REFERENCES [dbo].[IKI_MASTER] ([IKI_MASTERID])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_IKI_MASTER]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_ORGANIGRAMA] FOREIGN KEY ([RESPONSIBLE_RANK_ID])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_PROC_NODE_TYPES].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_PROC_NODE_TYPES] FOREIGN KEY ([PROC_NODE_TYPESID])
REFERENCES [dbo].[PROC_NODE_TYPES] ([PROC_NODE_TYPESID])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_PROC_NODE_TYPES]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_PROC_NODES].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_PROC_NODES] FOREIGN KEY ([PROC_NODESID_PARENT])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_PROC_NODES]
GO
--SqlScripter----[dbo].[PROC_NODES].[FK_PROC_NODES_PROC_PLANS].sql
GO
ALTER TABLE [dbo].[PROC_NODES] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_PROC_PLANS] FOREIGN KEY ([PROC_PLANSID])
REFERENCES [dbo].[PROC_PLANS] ([PROC_PLANSID])
GO
ALTER TABLE [dbo].[PROC_NODES] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_PROC_PLANS]
GO
--SqlScripter----[dbo].[PROC_NODES_OPTIONS].[FK_PROC_NODES_OPTIONS_PROC_NODES].sql
GO
ALTER TABLE [dbo].[PROC_NODES_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_OPTIONS_PROC_NODES] FOREIGN KEY ([PROC_NODESID])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_NODES_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_OPTIONS_PROC_NODES]
GO
--SqlScripter----[dbo].[PROC_NODES_OPTIONS].[FK_PROC_NODES_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[PROC_NODES_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[PROC_NODES_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS].[FK_PROC_NODES_RELATIONS_PROC_NODES].sql
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES] FOREIGN KEY ([PROC_NODESID_SOURCE])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES]
GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS].[FK_PROC_NODES_RELATIONS_PROC_NODES_RELATIONS_STRENGTH].sql
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES_RELATIONS_STRENGTH] FOREIGN KEY ([PROC_NODES_RELS_STRENGTHID])
REFERENCES [dbo].[PROC_NODES_RELATIONS_STRENGTH] ([PROC_NODES_RELS_STRENGTHID])
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES_RELATIONS_STRENGTH]
GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS].[FK_PROC_NODES_RELATIONS_PROC_NODES1].sql
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES1] FOREIGN KEY ([PROC_NODESID_TARGET])
REFERENCES [dbo].[PROC_NODES] ([PROC_NODESID])
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_NODES1]
GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS].[FK_PROC_NODES_RELATIONS_PROC_RELATIONS_TYPES].sql
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_RELATIONS_TYPES] FOREIGN KEY ([PROC_RELATIONS_TYPESID])
REFERENCES [dbo].[PROC_RELATIONS_TYPES] ([PROC_RELATIONS_TYPESID])
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_NODES_RELATIONS_PROC_RELATIONS_TYPES]
GO
--SqlScripter----[dbo].[PROC_PLANS_OPTIONS].[FK_PROC_PLANS_OPTIONS_PROC_PLANS].sql
GO
ALTER TABLE [dbo].[PROC_PLANS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_PLANS_OPTIONS_PROC_PLANS] FOREIGN KEY ([PROC_PLANSID])
REFERENCES [dbo].[PROC_PLANS] ([PROC_PLANSID])
GO
ALTER TABLE [dbo].[PROC_PLANS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_PLANS_OPTIONS_PROC_PLANS]
GO
--SqlScripter----[dbo].[PROC_PLANS_OPTIONS].[FK_PROC_PLANS_OPTIONS_USUARIOS].sql
GO
ALTER TABLE [dbo].[PROC_PLANS_OPTIONS] WITH NOCHECK ADD CONSTRAINT [FK_PROC_PLANS_OPTIONS_USUARIOS] FOREIGN KEY ([USERID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[PROC_PLANS_OPTIONS] WITH CHECK CHECK CONSTRAINT [FK_PROC_PLANS_OPTIONS_USUARIOS]
GO
--SqlScripter----[dbo].[PROCESOS].[FK_PROCESOS_DOCUMENTOS].sql
GO
ALTER TABLE [dbo].[PROCESOS] WITH NOCHECK ADD CONSTRAINT [FK_PROCESOS_DOCUMENTOS] FOREIGN KEY ([CODIGODOCUMENTO])
REFERENCES [dbo].[DOCUMENTOS] ([CODIGO])
GO
ALTER TABLE [dbo].[PROCESOS] WITH CHECK CHECK CONSTRAINT [FK_PROCESOS_DOCUMENTOS]
GO
--SqlScripter----[dbo].[SURVEYGROUPSMEMBERS].[FK_SURVEYGROUPSMEMBERS_SURVEYGROUPS].sql
GO
ALTER TABLE [dbo].[SURVEYGROUPSMEMBERS] WITH NOCHECK ADD CONSTRAINT [FK_SURVEYGROUPSMEMBERS_SURVEYGROUPS] FOREIGN KEY ([CODIGOSURVEYGROUP])
REFERENCES [dbo].[SURVEYGROUPS] ([CODIGO])
GO
ALTER TABLE [dbo].[SURVEYGROUPSMEMBERS] WITH CHECK CHECK CONSTRAINT [FK_SURVEYGROUPSMEMBERS_SURVEYGROUPS]
GO
--SqlScripter----[dbo].[SURVEYGROUPSMEMBERS].[FK_SURVEYGROUPSMEMBERS_SURVEYUSERS].sql
GO
ALTER TABLE [dbo].[SURVEYGROUPSMEMBERS] WITH NOCHECK ADD CONSTRAINT [FK_SURVEYGROUPSMEMBERS_SURVEYUSERS] FOREIGN KEY ([CODIGOSURVEYUSER])
REFERENCES [dbo].[SURVEYUSERS] ([CODIGO])
GO
ALTER TABLE [dbo].[SURVEYGROUPSMEMBERS] WITH CHECK CHECK CONSTRAINT [FK_SURVEYGROUPSMEMBERS_SURVEYUSERS]
GO
--SqlScripter----[dbo].[TAREASREVISION].[FK_TAREASREVISION_PROCESOS].sql
GO
ALTER TABLE [dbo].[TAREASREVISION] WITH NOCHECK ADD CONSTRAINT [FK_TAREASREVISION_PROCESOS] FOREIGN KEY ([CODIGOPROCESO])
REFERENCES [dbo].[PROCESOS] ([CODIGO])
GO
ALTER TABLE [dbo].[TAREASREVISION] WITH CHECK CHECK CONSTRAINT [FK_TAREASREVISION_PROCESOS]
GO
--SqlScripter----[dbo].[TAREASREVISION].[FK_TAREASREVISION_USUARIOS].sql
GO
ALTER TABLE [dbo].[TAREASREVISION] WITH NOCHECK ADD CONSTRAINT [FK_TAREASREVISION_USUARIOS] FOREIGN KEY ([CODIGOUSUARIO])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[TAREASREVISION] NOCHECK CONSTRAINT [FK_TAREASREVISION_USUARIOS]
GO
--SqlScripter----[dbo].[TASKSDELAYS].[FK_TASKSDELAYS_NCTAREAS].sql
GO
ALTER TABLE [dbo].[TASKSDELAYS] WITH NOCHECK ADD CONSTRAINT [FK_TASKSDELAYS_NCTAREAS] FOREIGN KEY ([NCTASKID])
REFERENCES [dbo].[NCTAREAS] ([CODIGO])
GO
ALTER TABLE [dbo].[TASKSDELAYS] WITH CHECK CHECK CONSTRAINT [FK_TASKSDELAYS_NCTAREAS]
GO
--SqlScripter----[dbo].[TPROT_INVOLVED].[FK_TPROT_INVOLVED_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[TPROT_INVOLVED] WITH NOCHECK ADD CONSTRAINT [FK_TPROT_INVOLVED_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[TPROT_INVOLVED] WITH CHECK CHECK CONSTRAINT [FK_TPROT_INVOLVED_NCMAINPROD]
GO
--SqlScripter----[dbo].[TPROT_INVOLVED].[FK_TPROT_INVOLVED_ORGANIGRAMA].sql
GO
ALTER TABLE [dbo].[TPROT_INVOLVED] WITH NOCHECK ADD CONSTRAINT [FK_TPROT_INVOLVED_ORGANIGRAMA] FOREIGN KEY ([CODIGOCARGO])
REFERENCES [dbo].[ORGANIGRAMA] ([CODIGO])
GO
ALTER TABLE [dbo].[TPROT_INVOLVED] WITH CHECK CHECK CONSTRAINT [FK_TPROT_INVOLVED_ORGANIGRAMA]
GO
--SqlScripter----[dbo].[TPROT_RESPONSIBLE].[FK_TPROT_RESPONSIBLE_TPROT_TASK].sql
GO
ALTER TABLE [dbo].[TPROT_RESPONSIBLE] WITH NOCHECK ADD CONSTRAINT [FK_TPROT_RESPONSIBLE_TPROT_TASK] FOREIGN KEY ([CODIGOTAREA])
REFERENCES [dbo].[TPROT_TASK] ([CODIGO])
GO
ALTER TABLE [dbo].[TPROT_RESPONSIBLE] WITH CHECK CHECK CONSTRAINT [FK_TPROT_RESPONSIBLE_TPROT_TASK]
GO
--SqlScripter----[dbo].[TPROT_TASK].[FK_TPROT_TASK_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[TPROT_TASK] WITH NOCHECK ADD CONSTRAINT [FK_TPROT_TASK_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[TPROT_TASK] WITH CHECK CHECK CONSTRAINT [FK_TPROT_TASK_NCMAINPROD]
GO
--SqlScripter----[dbo].[TPROT_TASKSSTEPS].[FK_TPROT_TASKSSTEPS_TPROT_TASK].sql
GO
ALTER TABLE [dbo].[TPROT_TASKSSTEPS] WITH NOCHECK ADD CONSTRAINT [FK_TPROT_TASKSSTEPS_TPROT_TASK] FOREIGN KEY ([NCTASKID])
REFERENCES [dbo].[TPROT_TASK] ([CODIGO])
GO
ALTER TABLE [dbo].[TPROT_TASKSSTEPS] WITH CHECK CHECK CONSTRAINT [FK_TPROT_TASKSSTEPS_TPROT_TASK]
GO
--SqlScripter----[dbo].[VAR_CIRCULOS_CALIDAD].[FK_VAR_CIRCULOS_CALIDAD_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_CIRCULOS_CALIDAD] WITH NOCHECK ADD CONSTRAINT [FK_VAR_CIRCULOS_CALIDAD_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_CIRCULOS_CALIDAD] WITH CHECK CHECK CONSTRAINT [FK_VAR_CIRCULOS_CALIDAD_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_DATOS].[FK_VAR_DATOS_VAR_OBJETIVOSNUM].sql
GO
ALTER TABLE [dbo].[VAR_DATOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_DATOS_VAR_OBJETIVOSNUM] FOREIGN KEY ([CODIGO_OBJETIVO])
REFERENCES [dbo].[VAR_OBJETIVOSNUM] ([CODIGONC])
GO
ALTER TABLE [dbo].[VAR_DATOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_DATOS_VAR_OBJETIVOSNUM]
GO
--SqlScripter----[dbo].[VAR_DISENOPRODUCTOS].[FK_VAR_DISENOPRODUCTOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_DISENOPRODUCTOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_DISENOPRODUCTOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_DISENOPRODUCTOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_DISENOPRODUCTOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_DISENOPRODUCTOS].[FK_VAR_DISENOPRODUCTOS_TBL_CLIENTES].sql
GO
ALTER TABLE [dbo].[VAR_DISENOPRODUCTOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_DISENOPRODUCTOS_TBL_CLIENTES] FOREIGN KEY ([CLIENTE])
REFERENCES [dbo].[TBL_CLIENTES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_DISENOPRODUCTOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_DISENOPRODUCTOS_TBL_CLIENTES]
GO
--SqlScripter----[dbo].[VAR_INCIDENTES_AUD].[FK_VAR_INCIDENTES_AUD_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_INCIDENTES_AUD] WITH NOCHECK ADD CONSTRAINT [FK_VAR_INCIDENTES_AUD_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_INCIDENTES_AUD] WITH CHECK CHECK CONSTRAINT [FK_VAR_INCIDENTES_AUD_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_INCIDENTESINT].[FK_VAR_INCIDENTESINT_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_INCIDENTESINT] WITH NOCHECK ADD CONSTRAINT [FK_VAR_INCIDENTESINT_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_INCIDENTESINT] WITH CHECK CHECK CONSTRAINT [FK_VAR_INCIDENTESINT_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_NCAUD].[FK_VAR_NCAUD_NCCAUSASCLASES].sql
GO
ALTER TABLE [dbo].[VAR_NCAUD] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NCAUD_NCCAUSASCLASES] FOREIGN KEY ([CODIGOCAUSAPRIMARIA])
REFERENCES [dbo].[NCCAUSASCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NCAUD] WITH CHECK CHECK CONSTRAINT [FK_VAR_NCAUD_NCCAUSASCLASES]
GO
--SqlScripter----[dbo].[VAR_NCAUD].[FK_VAR_NCAUD_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_NCAUD] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NCAUD_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NCAUD] WITH CHECK CHECK CONSTRAINT [FK_VAR_NCAUD_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_NOCONFORMIDADES].[FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES].sql
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES] FOREIGN KEY ([CODIGOCAUSAPRIMARIA])
REFERENCES [dbo].[NCCAUSASCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH CHECK CHECK CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES]
GO
--SqlScripter----[dbo].[VAR_NOCONFORMIDADES].[FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES1].sql
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES1] FOREIGN KEY ([CODIGOCAUSASECUNDARIA])
REFERENCES [dbo].[NCCAUSASCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH CHECK CHECK CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCCAUSASCLASES1]
GO
--SqlScripter----[dbo].[VAR_NOCONFORMIDADES].[FK_VAR_NOCONFORMIDADES_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH CHECK CHECK CONSTRAINT [FK_VAR_NOCONFORMIDADES_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_NOCONFORMIDADES].[FK_VAR_NOCONFORMIDADES_TBL_NCCARACTER].sql
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH NOCHECK ADD CONSTRAINT [FK_VAR_NOCONFORMIDADES_TBL_NCCARACTER] FOREIGN KEY ([CARACTER])
REFERENCES [dbo].[TBL_NCCARACTER] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] WITH CHECK CHECK CONSTRAINT [FK_VAR_NOCONFORMIDADES_TBL_NCCARACTER]
GO
--SqlScripter----[dbo].[VAR_OBJETIVOSCUAL].[FK_VAR_OBJETIVOSCUAL_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSCUAL] WITH NOCHECK ADD CONSTRAINT [FK_VAR_OBJETIVOSCUAL_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSCUAL] WITH CHECK CHECK CONSTRAINT [FK_VAR_OBJETIVOSCUAL_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_OBJETIVOSNUM].[FK_VAR_OBJETIVOSNUM_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSNUM] WITH NOCHECK ADD CONSTRAINT [FK_VAR_OBJETIVOSNUM_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSNUM] WITH CHECK CHECK CONSTRAINT [FK_VAR_OBJETIVOSNUM_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_OBJETIVOSNUM].[FK_VAR_OBJETIVOSNUM_TBL_UNIDADES].sql
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSNUM] WITH NOCHECK ADD CONSTRAINT [FK_VAR_OBJETIVOSNUM_TBL_UNIDADES] FOREIGN KEY ([UNIDAD])
REFERENCES [dbo].[TBL_UNIDADES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSNUM] WITH CHECK CHECK CONSTRAINT [FK_VAR_OBJETIVOSNUM_TBL_UNIDADES]
GO
--SqlScripter----[dbo].[VAR_PROYECTOS].[FK_VAR_PROYECTOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_PROYECTOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_PROYECTOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_PROYECTOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_PROYECTOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_QUEJAS].[FK_VAR_QUEJAS_NCCAUSASCLASES].sql
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_QUEJAS_NCCAUSASCLASES] FOREIGN KEY ([CODIGOCAUSAPRIMARIA])
REFERENCES [dbo].[NCCAUSASCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_QUEJAS_NCCAUSASCLASES]
GO
--SqlScripter----[dbo].[VAR_QUEJAS].[FK_VAR_QUEJAS_NCCAUSASCLASES1].sql
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_QUEJAS_NCCAUSASCLASES1] FOREIGN KEY ([CODIGOCAUSASECUNDARIA])
REFERENCES [dbo].[NCCAUSASCLASES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_QUEJAS_NCCAUSASCLASES1]
GO
--SqlScripter----[dbo].[VAR_QUEJAS].[FK_VAR_QUEJAS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_QUEJAS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_QUEJAS_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_QUEJAS].[FK_VAR_QUEJAS_TBL_CLIENTES].sql
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_QUEJAS_TBL_CLIENTES] FOREIGN KEY ([CLIENTE])
REFERENCES [dbo].[TBL_CLIENTES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_QUEJAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_QUEJAS_TBL_CLIENTES]
GO
--SqlScripter----[dbo].[VAR_REQUISITOS].[FK_VAR_REQUISITOS_NCDETECTANTES].sql
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_REQUISITOS_NCDETECTANTES] FOREIGN KEY ([DESCDETECCION])
REFERENCES [dbo].[NCDETECTANTES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_REQUISITOS_NCDETECTANTES]
GO
--SqlScripter----[dbo].[VAR_REQUISITOS].[FK_VAR_REQUISITOS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_REQUISITOS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_REQUISITOS_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_REQUISITOS].[FK_VAR_REQUISITOS_TBL_NCDETECCION].sql
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_REQUISITOS_TBL_NCDETECCION] FOREIGN KEY ([TIPODETECCION])
REFERENCES [dbo].[TBL_NCDETECCION] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] WITH CHECK CHECK CONSTRAINT [FK_VAR_REQUISITOS_TBL_NCDETECCION]
GO
--SqlScripter----[dbo].[VAR_REUNIONES].[FK_VAR_REUNIONES_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_REUNIONES] WITH NOCHECK ADD CONSTRAINT [FK_VAR_REUNIONES_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_REUNIONES] WITH CHECK CHECK CONSTRAINT [FK_VAR_REUNIONES_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_SUGERENCIAS].[FK_VAR_SUGERENCIAS_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_SUGERENCIAS_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_SUGERENCIAS_NCMAINPROD]
GO
--SqlScripter----[dbo].[VAR_SUGERENCIAS].[FK_VAR_SUGERENCIAS_TBL_CLIENTES].sql
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_SUGERENCIAS_TBL_CLIENTES] FOREIGN KEY ([CLIENTE])
REFERENCES [dbo].[TBL_CLIENTES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_SUGERENCIAS_TBL_CLIENTES]
GO
--SqlScripter----[dbo].[VAR_SUGERENCIAS].[FK_VAR_SUGERENCIAS_TBL_ORIGEN].sql
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH NOCHECK ADD CONSTRAINT [FK_VAR_SUGERENCIAS_TBL_ORIGEN] FOREIGN KEY ([ORIGEN])
REFERENCES [dbo].[TBL_ORIGEN] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] WITH CHECK CHECK CONSTRAINT [FK_VAR_SUGERENCIAS_TBL_ORIGEN]
GO
--SqlScripter----[dbo].[VAR_SUGERENCIASINT].[FK_VAR_SUGERENCIASINT_NCDETECTANTES].sql
GO
ALTER TABLE [dbo].[VAR_SUGERENCIASINT] WITH NOCHECK ADD CONSTRAINT [FK_VAR_SUGERENCIASINT_NCDETECTANTES] FOREIGN KEY ([PERSONA_SUGIERE])
REFERENCES [dbo].[NCDETECTANTES] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_SUGERENCIASINT] WITH CHECK CHECK CONSTRAINT [FK_VAR_SUGERENCIASINT_NCDETECTANTES]
GO
--SqlScripter----[dbo].[VAR_SUGERENCIASINT].[FK_VAR_SUGERENCIASINT_NCMAINPROD].sql
GO
ALTER TABLE [dbo].[VAR_SUGERENCIASINT] WITH NOCHECK ADD CONSTRAINT [FK_VAR_SUGERENCIASINT_NCMAINPROD] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[NCMAINPROD] ([CODIGO])
GO
ALTER TABLE [dbo].[VAR_SUGERENCIASINT] WITH CHECK CHECK CONSTRAINT [FK_VAR_SUGERENCIASINT_NCMAINPROD]
GO
--SqlScripter----[dbo].[VARCHILD_AUDITEDS].[FK_VARCHILD_AUDITEDS_VAR_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[VARCHILD_AUDITEDS] WITH NOCHECK ADD CONSTRAINT [FK_VARCHILD_AUDITEDS_VAR_AUDITORIAS] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[VAR_AUDITORIAS] ([CODIGONC])
GO
ALTER TABLE [dbo].[VARCHILD_AUDITEDS] WITH CHECK CHECK CONSTRAINT [FK_VARCHILD_AUDITEDS_VAR_AUDITORIAS]
GO
--SqlScripter----[dbo].[VARCHILD_AUDITORS].[FK_VARCHILD_AUDITORS_VAR_AUDITORIAS].sql
GO
ALTER TABLE [dbo].[VARCHILD_AUDITORS] WITH NOCHECK ADD CONSTRAINT [FK_VARCHILD_AUDITORS_VAR_AUDITORIAS] FOREIGN KEY ([CODIGONC])
REFERENCES [dbo].[VAR_AUDITORIAS] ([CODIGONC])
GO
ALTER TABLE [dbo].[VARCHILD_AUDITORS] WITH CHECK CHECK CONSTRAINT [FK_VARCHILD_AUDITORS_VAR_AUDITORIAS]
GO
--SqlScripter----[dbo].[WF_APPROVAL_RECORDS].[FK_WF_APPROVAL_RECORDS_IK_PEOPLE].sql
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS] WITH NOCHECK ADD CONSTRAINT [FK_WF_APPROVAL_RECORDS_IK_PEOPLE] FOREIGN KEY ([IKPERSON_ID])
REFERENCES [dbo].[IK_PEOPLE] ([CODIGO])
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS] WITH CHECK CHECK CONSTRAINT [FK_WF_APPROVAL_RECORDS_IK_PEOPLE]
GO
--SqlScripter----[dbo].[WF_APPROVAL_RECORDS].[FK_WF_APPROVAL_RECORDS_WF_APPROVAL_REQUIREMENTS].sql
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS] WITH NOCHECK ADD CONSTRAINT [FK_WF_APPROVAL_RECORDS_WF_APPROVAL_REQUIREMENTS] FOREIGN KEY ([WF_NODE_ID])
REFERENCES [dbo].[WF_APPROVAL_REQUIREMENTS] ([WF_NODE_ID])
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS] WITH CHECK CHECK CONSTRAINT [FK_WF_APPROVAL_RECORDS_WF_APPROVAL_REQUIREMENTS]
GO
--SqlScripter----[dbo].[WF_APPROVAL_REQUIREMENTS].[FK_WF_APPROVAL_REQUIREMENTS_WF_NODE].sql
GO
ALTER TABLE [dbo].[WF_APPROVAL_REQUIREMENTS] WITH NOCHECK ADD CONSTRAINT [FK_WF_APPROVAL_REQUIREMENTS_WF_NODE] FOREIGN KEY ([WF_NODE_ID])
REFERENCES [dbo].[WF_NODE] ([WF_NODE_ID])
GO
ALTER TABLE [dbo].[WF_APPROVAL_REQUIREMENTS] WITH CHECK CHECK CONSTRAINT [FK_WF_APPROVAL_REQUIREMENTS_WF_NODE]