SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[dte_enca_docu](
	[codi_empr] [numeric](9, 0) NOT NULL,
	[tipo_docu] [numeric](3, 0) NOT NULL,
	[foli_docu] [numeric](10, 0) NOT NULL,
	[esta_docu] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[mens_esta] [varchar](200) COLLATE Modern_Spanish_CI_AS NULL,
	[corr_envi] [numeric](22, 0) NULL,
	[mens_envi] [varchar](200) COLLATE Modern_Spanish_CI_AS NULL,
	[fech_emis] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[entr_bien] [numeric](1, 0) NULL,
	[vent_serv] [numeric](1, 0) NULL,
	[form_pago] [numeric](1, 0) NULL,
	[fech_canc] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[dias_tepa] [numeric](3, 0) NULL,
	[codi_tepa] [varchar](4) COLLATE Modern_Spanish_CI_AS NULL,
	[mont_brut] [char](18) COLLATE Modern_Spanish_CI_AS NULL,
	[moda_pago] [varchar](2) COLLATE Modern_Spanish_CI_AS NULL,
	[fech_venc] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_emis] [numeric](9, 0) NULL,
	[peri_desd] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[peri_hast] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[digi_emis] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[nomb_emis] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[giro_emis] [varchar](80) COLLATE Modern_Spanish_CI_AS NULL,
	[nomb_sucu] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_sucu] [numeric](9, 0) NULL,
	[dire_orig] [varchar](60) COLLATE Modern_Spanish_CI_AS NULL,
	[comu_orig] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[ciud_orig] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_vend] [varchar](60) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_mand] [numeric](9, 0) NULL,
	[digi_mand] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_rece] [numeric](9, 0) NULL,
	[digi_rece] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[nomb_rece] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_rece] [varchar](40) COLLATE Modern_Spanish_CI_AS NULL,
	[giro_rece] [varchar](40) COLLATE Modern_Spanish_CI_AS NULL,
	[cont_rece] [varchar](80) COLLATE Modern_Spanish_CI_AS NULL,
	[dire_rece] [varchar](70) COLLATE Modern_Spanish_CI_AS NULL,
	[comu_rece] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[ciud_rece] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[dire_post] [varchar](70) COLLATE Modern_Spanish_CI_AS NULL,
	[comu_post] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[ciud_post] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_sofa] [numeric](9, 0) NULL,
	[digi_sofa] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[info_tran] [varchar](8) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_tran] [numeric](9, 0) NULL,
	[digi_tran] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[dire_dest] [varchar](60) COLLATE Modern_Spanish_CI_AS NULL,
	[comu_dest] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[ciud_dest] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[mont_neto] [numeric](18, 0) NULL,
	[mont_exen] [numeric](22, 4) NULL,
	[impu_vaag] [numeric](18, 0) NULL,
	[impu_vanr] [numeric](18, 0) NULL,
	[cred_es65] [numeric](18, 0) NULL,
	[gara_enva] [numeric](18, 0) NULL,
	[mont_tota] [numeric](22, 4) NULL,
	[mont_nofa] [numeric](18, 0) NULL,
	[valo_paga] [numeric](18, 0) NULL,
	[sald_ante] [numeric](18, 0) NULL,
	[codi_ceco] [varchar](18) COLLATE Modern_Spanish_CI_AS NULL,
	[feho_firm] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[indi_vegd] [numeric](1, 0) NULL,
	[vers_enca] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[corr_rafo] [numeric](18, 0) NULL,
	[feho_ted] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[firm_ted] [varchar](200) COLLATE Modern_Spanish_CI_AS NULL,
	[fech_carg] [datetime] NULL,
	[usua_impr] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[nume_impr] [numeric](3, 0) NULL,
	[fech_impr] [datetime] NULL,
	[vige_docu] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_peri] [varchar](6) COLLATE Modern_Spanish_CI_AS NULL,
	[corr_envi1] [numeric](22, 0) NULL,
	[esta_docu1] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[mnsg_erro] [varchar](2000) COLLATE Modern_Spanish_CI_AS NULL,
	[indi_nore] [numeric](1, 0) NULL,
	[subt_vese] [numeric](18, 0) NULL,
	[dire_arch] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[impr_dest] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[val1] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val2] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val3] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val4] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val5] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val6] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val7] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val8] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[val9] [varchar](300) COLLATE Modern_Spanish_CI_AS NULL,
	[tasa_vaag] [numeric](5, 2) NULL,
	[mont_base] [numeric](18, 0) NULL,
	[cola_proc] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[nume_imme] [numeric](3, 0) NULL,
	[arch_resp] [varchar](200) COLLATE Modern_Spanish_CI_AS NULL,
	[hace_envi] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[tipo_impr] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[mont_canc] [numeric](18, 0) NULL,
	[sald_inso] [numeric](18, 0) NULL,
	[from_paex] [numeric](2, 0) NULL,
	[tipo_cupa] [numeric](2, 0) NULL,
	[cuen_pago] [numeric](20, 0) NULL,
	[banc_pago] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[glos_pago] [varchar](100) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_emtr] [numeric](1, 0) NULL,
	[foli_auto] [numeric](4, 0) NULL,
	[fech_auto] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_suad] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[iden_adem] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[iden_reex] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[naci_ext] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[iden_adre] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[mail_rece] [varchar](80) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_chof] [numeric](9, 0) NULL,
	[digi_chof] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[nomb_chof] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[moda_vent] [numeric](2, 0) NULL,
	[clau_expo] [numeric](2, 0) NULL,
	[tota_clex] [numeric](18, 2) NULL,
	[viaa_tran] [numeric](2, 0) NULL,
	[nomb_tran] [varchar](40) COLLATE Modern_Spanish_CI_AS NULL,
	[rutt_citr] [numeric](8, 0) NULL,
	[digi_citr] [varchar](1) COLLATE Modern_Spanish_CI_AS NULL,
	[nomb_citr] [varchar](40) COLLATE Modern_Spanish_CI_AS NULL,
	[iden_citr] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[nume_book] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_oper] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_puem] [numeric](4, 0) NULL,
	[iden_puem] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_pude] [numeric](4, 0) NULL,
	[iden_pude] [varchar](20) COLLATE Modern_Spanish_CI_AS NULL,
	[cant_tara] [numeric](7, 0) NULL,
	[umed_tara] [numeric](2, 0) NULL,
	[tota_brut] [numeric](12, 2) NULL,
	[unid_brut] [numeric](2, 0) NULL,
	[tota_neto] [numeric](12, 2) NULL,
	[unid_neto] [numeric](2, 0) NULL,
	[tota_item] [numeric](18, 0) NULL,
	[tota_bult] [numeric](18, 0) NULL,
	[mont_flet] [numeric](18, 4) NULL,
	[mont_segu] [numeric](18, 4) NULL,
	[pais_rece] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[pais_dest] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[tipo_mone] [varchar](15) COLLATE Modern_Spanish_CI_AS NULL,
	[mont_baco] [numeric](18, 0) NULL,
	[ivag_prop] [numeric](18, 0) NULL,
	[ivag_terc] [numeric](18, 0) NULL,
	[valo_cone] [numeric](18, 0) NULL,
	[valo_coex] [numeric](18, 0) NULL,
	[ivaag_core] [numeric](18, 0) NULL,
	[tipo_moom] [varchar](15) COLLATE Modern_Spanish_CI_AS NULL,
	[tipo_camb] [numeric](10, 4) NULL,
	[neto_otmo] [numeric](18, 4) NULL,
	[noaf_otmo] [numeric](18, 4) NULL,
	[faca_otmo] [numeric](18, 4) NULL,
	[maco_otmo] [numeric](18, 4) NULL,
	[ivag_otmo] [numeric](18, 4) NULL,
	[ivno_otmo] [numeric](18, 4) NULL,
	[mont_otmo] [numeric](18, 4) NULL,
	[foli_clie] [varchar](12) COLLATE Modern_Spanish_CI_AS NULL,
	[corr_extr] [numeric](6, 0) NULL,
	[codi_usua] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[comi_neto] [numeric](18, 0) NULL,
	[comi_exen] [numeric](18, 0) NULL,
	[comi_ivaa] [numeric](18, 0) NULL,
	[codi_emex] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[lote_docu] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[codi_serv] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[corr_cert_Firm] [numeric](22, 0) NULL,
	[codi_form] [varchar](30) COLLATE Modern_Spanish_CI_AS NULL,
	[peri_part] [int] NULL,
	[esta_reme] [varchar](3) COLLATE Modern_Spanish_CI_AS NULL,
	[even_recl] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[docu_escd] [varchar](10) COLLATE Modern_Spanish_CI_AS NULL,
	[tran_vent] [numeric](1, 0) NULL,
	[tran_comp] [numeric](1, 0) NULL,
	[TIPO_FAES] [numeric](1, 0) NULL,
	[TIPO_TURI] [numeric](1, 0) NULL
)
ON [PRIMARY]
