SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PC_ORMSTATE](
	[PCO_ORMSTATEID] [numeric](19, 0) NOT NULL,
	[PCO_VERSION] [int] NULL,
	[PCO_ORMAPPING] [ntext] COLLATE Latin1_General_CS_AS NULL,
	[PCO_MAPPING_STATE] [ntext] COLLATE Latin1_General_CS_AS NULL,
	[PCO_GENERATOR_STATE] [ntext] COLLATE Latin1_General_CS_AS NULL,
	[PCO_VIEWSPEC] [ntext] COLLATE Latin1_General_CS_AS NULL,
	[PCO_VIEWSPEC_VERSION] [nvarchar](255) COLLATE Latin1_General_CS_AS NULL,
	[PCO_EXT_VIEWSPEC] [ntext] COLLATE Latin1_General_CS_AS NULL,
	[PCO_EXT_VIEWSPEC_VERSION] [nvarchar](255) COLLATE Latin1_General_CS_AS NULL,
	[PCO_APP_VIEWSPEC_VERSION] [ntext] COLLATE Latin1_General_CS_AS NULL
)
ON [PRIMARY]
