SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PR_ATTRIBUTE](
	[PRA_RESOURCE] [numeric](19, 0) NOT NULL,
	[PRD_ATTR_NAME] [nvarchar](255) COLLATE Latin1_General_CS_AS NULL,
	[PRD_ATTR_VALUE] [nvarchar](255) COLLATE Latin1_General_CS_AS NULL,
	[PRD_PARENTCONTAINER] [numeric](19, 0) NULL
)
ON [PRIMARY]
