SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ik_AddWorkingDays]') IS NULL EXEC('CREATE FUNCTION [dbo].[ik_AddWorkingDays] () RETURNS int AS BEGIN /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ RETURN 0 END')
GO
ALTER FUNCTION [dbo].[ik_AddWorkingDays]
(
	@STARTDATE datetime,
	@DAYS int
	)
RETURNS datetime
AS
BEGIN

DECLARE @Saturday int, @Sunday int

DECLARE @satDate datetime
DECLARE @sunDate datetime

SET @satDate = '2006-08-26'
SET @sunDate = '2006-08-27'


SET @Saturday = (select datepart(weekday,@satDate))
SET @Sunday = (select datepart(weekday,@sunDate))

DECLARE @DOW int
DECLARE @WORKING tinyint
DECLARE @CODIGO int

IF @DAYS > 0
BEGIN
	WHILE @DAYS > 0
	BEGIN
		SET @WORKING = 1
		SET @DOW = DATEPART(WEEKDAY,@STARTDATE)
		IF (@DOW = @Saturday OR @DOW = @Sunday) SET @WORKING = 0
		ELSE
			BEGIN
			SET @CODIGO = (SELECT CODIGO FROM NCTASKS_NOT_WORKING_DAYS WHERE
						   DATEPART(day,FECHA) = DATEPART(day,@STARTDATE) AND
						   DATEPART(month,FECHA) = DATEPART(month,@STARTDATE) AND
						   DATEPART(year,FECHA) = DATEPART(year,@STARTDATE))
			IF NOT @CODIGO IS NULL SET @WORKING = 0
			END
		SET @STARTDATE = @STARTDATE + 1
		SET @DAYS = @DAYS - @WORKING
	END

	SET @WORKING = 0
	WHILE @WORKING = 0
	BEGIN
		SET @WORKING = 1
		SET @DOW = DATEPART(WEEKDAY,@STARTDATE)
		IF (@DOW = @Saturday OR @DOW = @Sunday) SET @WORKING = 0
		ELSE
			BEGIN
			SET @CODIGO = (SELECT CODIGO FROM NCTASKS_NOT_WORKING_DAYS WHERE
						   DATEPART(day,FECHA) = DATEPART(day,@STARTDATE) AND
						   DATEPART(month,FECHA) = DATEPART(month,@STARTDATE) AND
						   DATEPART(year,FECHA) = DATEPART(year,@STARTDATE))
			IF NOT @CODIGO IS NULL SET @WORKING = 0
			END
		IF @WORKING=0 SET @STARTDATE = @STARTDATE + 1
	END
END
ELSE
BEGIN
	WHILE @DAYS < 0
	BEGIN
		SET @WORKING = 1
		SET @DOW = DATEPART(WEEKDAY,@STARTDATE)
		IF (@DOW = @Saturday OR @DOW = @Sunday) SET @WORKING = 0
		ELSE
			BEGIN
			SET @CODIGO = (SELECT CODIGO FROM NCTASKS_NOT_WORKING_DAYS WHERE
						   DATEPART(day,FECHA) = DATEPART(day,@STARTDATE) AND
						   DATEPART(month,FECHA) = DATEPART(month,@STARTDATE) AND
						   DATEPART(year,FECHA) = DATEPART(year,@STARTDATE))
			IF NOT @CODIGO IS NULL SET @WORKING = 0
			END
		SET @STARTDATE = @STARTDATE - 1
		SET @DAYS = @DAYS + @WORKING
	END

	SET @WORKING = 0
	WHILE @WORKING = 0
	BEGIN
		SET @WORKING = 1
		SET @DOW = DATEPART(WEEKDAY,@STARTDATE)
		IF (@DOW = @Saturday OR @DOW = @Sunday) SET @WORKING = 0
		ELSE
			BEGIN
			SET @CODIGO = (SELECT CODIGO FROM NCTASKS_NOT_WORKING_DAYS WHERE
						   DATEPART(day,FECHA) = DATEPART(day,@STARTDATE) AND
						   DATEPART(month,FECHA) = DATEPART(month,@STARTDATE) AND
						   DATEPART(year,FECHA) = DATEPART(year,@STARTDATE))
			IF NOT @CODIGO IS NULL SET @WORKING = 0
			END
		IF @WORKING=0 SET @STARTDATE = @STARTDATE - 1
	END
END

RETURN @STARTDATE

END
GO
