
GO
--SqlScripter----[dbo].[SNMAN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SNMAN](
	[SENOR] [nvarchar](50) NULL,
	[CARGO] [nvarchar](50) NULL,
	[INST] [nvarchar](50) NULL,
	[REFERENCIA] [nvarchar](232) NULL,
	[SN_DADO] [nvarchar](10) NULL,
	[FECHA] [smalldatetime] NULL,
	[RESPONSABL] [nvarchar](50) NULL
)
ON [PRIMARY]

GO
--SqlScripter----[dbo].[SNNUM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SNNUM](
	[NUMBER] [float] NULL
)
ON [PRIMARY]

GO
--SqlScripter----[dbo].[USUARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[USERNAME] [nvarchar](40) NULL,
	[PASSWORD] [nvarchar](40) NULL,
	[NOMBRE] [nvarchar](50) NULL
)
ON [PRIMARY]

GO
--SqlScripter----[dbo].[USUARIOS_bkp].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS_bkp](
	[USERNAME] [nvarchar](10) NULL,
	[PASSWORD] [nvarchar](10) NULL,
	[NOMBRE] [nvarchar](50) NULL
)
ON [PRIMARY]
