SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_ELMNT_MAPPINGS]') IS NULL EXEC('CREATE VIEW [dbo].[V_ELMNT_MAPPINGS] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_ELMNT_MAPPINGS]
AS
select 
' ' "REPOSITORY_ID", 
'com.informatica.powercenter.map.Mapping' "CLASS_ID", 
       'Mapping_' + ltrim(str(map.MAPPING_ID)) "ELEMENT_ID", map.VERSION_NUMBER "VERSION_NUM",
	   map.MAPPING_NAME "ELEMENT_NAME", map.MAPPING_NAME "ELEMENT_LABEL",
	   '' "ELEMENT_ALIAS", map.COMMENTS "ELEMENT_DESC", 
	   '' "ELEMENT_USAGE", 'Application' "ELEMENT_TYPE", 
	   'Mapping' "ELEMENT_SUBTYPE", 
	   'VALID' "ELEMENT_ATTR1", (CASE WHEN IS_VALID=1 THEN 'Yes' ELSE 'No' END) "ELEMENT_VALUE1",
	   '' "ELEMENT_ATTR2", '' "ELEMENT_VALUE2", 
	   '' "ELEMENT_ATTR3", '' "ELEMENT_VALUE3",
     (CASE WHEN IS_VALID=1 THEN 'Y' ELSE 'N' END) "VALID_FLAG", 'N' "DISABLED_FLAG", 
	   '' "SRC_CREATE_DT", LAST_SAVED "SRC_UPDATE_DT",
	   '' "EFF_FROM_DT",  '' "EFF_TO_DT",
	   map.SUBJECT_ID	"SUBJECT_ID"
	   from OPB_MAPPING map
	   where 
	         REF_WIDGET_ID = 0 and map.IS_VISIBLE = 1
GO
