SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_ELMNT_TASKS]') IS NULL EXEC('CREATE VIEW [dbo].[V_ELMNT_TASKS] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_ELMNT_TASKS]
AS 
select ' ' "REPOSITORY_ID", 
'com.informatica.powercenter.process.' + Replace(otype.OBJECT_TYPE_NAME,' ','') "CLASS_ID", 
     otype.OBJECT_TYPE_NAME + '_' + ltrim(str(tasks.TASK_ID)) "ELEMENT_ID", tasks.VERSION_NUMBER "VERSION_NUM",
	   tasks.TASK_NAME "ELEMENT_NAME", tasks.TASK_NAME "ELEMENT_LABEL",
	   '' "ELEMENT_ALIAS", tasks.COMMENTS "ELEMENT_DESC",
	   '' "ELEMENT_USAGE", otype.OBJECT_TYPE_NAME "ELEMENT_TYPE",
	   '' "ELEMENT_SUBTYPE",
	   'REUSABLE' "ELEMENT_ATTR1", 'Yes' "ELEMENT_VALUE1",
	   '' "ELEMENT_ATTR2", '' "ELEMENT_VALUE2",
	   'TASK_PROPERTY' "ELEMENT_ATTR3", str(tasks.TASK_PROPERTY) "ELEMENT_VALUE3",
     (CASE WHEN tasks.IS_VALID=1 THEN 'Y' ELSE 'N' END) "VALID_FLAG",  (CASE WHEN tasks.IS_ENABLED=0 THEN 'Y' ELSE 'N' END) "DISABLED_FLAG",
	   '' "SRC_CREATE_DT", LAST_SAVED "SRC_UPDATE_DT",
	   '' "EFF_FROM_DT",  '' "EFF_TO_DT",
	   tasks.SUBJECT_ID	"SUBJECT_ID"
       from OPB_TASK tasks, OPB_OBJECT_TYPE otype
	  where otype.OBJECT_TYPE_ID = tasks.TASK_TYPE and
              IS_REUSABLE = 1 and tasks.IS_VISIBLE = 1
GO
