SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_ELMNT_WDGINST]') IS NULL EXEC('CREATE VIEW [dbo].[V_ELMNT_WDGINST] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_ELMNT_WDGINST]
AS 
select ' ' "REPOSITORY_ID", 
'com.informatica.powercenter.map.' + REPLACE(REPLACE(otype.OBJECT_TYPE_NAME,' ',''),'-','')+ 'Instance' "CLASS_ID", 
       'WIDGET_INSTANCE_' + otype.OBJECT_TYPE_NAME + '_' + ltrim(str(winst.MAPPING_ID)) + '_'+ ltrim(str(winst.INSTANCE_ID)) "ELEMENT_ID",
 	   winst.VERSION_NUMBER "VERSION_NUM",
	   winst.INSTANCE_NAME "ELEMENT_NAME", winst.INSTANCE_NAME "ELEMENT_LABEL",
	   '' "ELEMENT_ALIAS", winst.COMMENTS "ELEMENT_DESC", 
	   '' "ELEMENT_USAGE", 'Application' "ELEMENT_TYPE", 
	   'WIDGET_INSTANCE_' + otype.OBJECT_TYPE_NAME  "ELEMENT_SUBTYPE", 
	   '' "ELEMENT_ATTR1", '' "ELEMENT_VALUE1",
	   '' "ELEMENT_ATTR2", '' "ELEMENT_VALUE2", 
	   '' "ELEMENT_ATTR3", '' "ELEMENT_VALUE3",
  'Y' "VALID_FLAG", 'N' "DISABLED_FLAG", 
  '' "SRC_CREATE_DT", map.LAST_SAVED "SRC_UPDATE_DT",
	   '' "EFF_FROM_DT",  '' "EFF_TO_DT",
	   map.SUBJECT_ID	"SUBJECT_ID"
	   from OPB_WIDGET_INST winst, OPB_OBJECT_TYPE otype, OPB_MAPPING map
	   where winst.WIDGET_TYPE = otype.OBJECT_TYPE_ID and
	         map.MAPPING_ID = winst.MAPPING_ID and map.VERSION_NUMBER = winst.VERSION_NUMBER 
and map.IS_VISIBLE = 1
GO
