SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_DEFAULT_FILE_CNX]') IS NULL EXEC('CREATE VIEW [dbo].[V_DEFAULT_FILE_CNX] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_DEFAULT_FILE_CNX]
AS
select  ' ' "REPOSITORY_ID", 
	'com.informatica.powercenter.deployment.DefaultFlatfileConnection' "CLASS_ID", 
        'PC_DEFAULT_FILE_CONNECTION' "CONNECTION_ID", 
	NULL "CATALOG_ID",
	NULL  "DATA_MGR_CLASS_ID", 
	NULL "DATA_MANAGER_ID",
	'' "SCHEMA_CLASS_ID", 
	'' "SCHEMA_ID",
	'FLAT_FILE' "CONNECTION_TYPE", 
	'' "CONNECTION_NAME", 
	'' "CONNECTION_DESC", 
	'' "CONNECTION_SUBTYPE", 
	'' "HOST_NAME", '' "SCHEMA_NAME",
        '' "USER_NAME", '' "ADDRESS",
        '' "CONNECTION_TEXT1", '' "CONNECTION_TEXT2",
        '' "CONNECTION_TEXT3", '1' "VERSION_NUM",
        '' "SRC_CREATE_DT", '' "SRC_UPDATE_DT",
        ''  "EFF_FROM_DT", '' "EFF_TO_DT"
    from OPB_REPOSIT repo where repo.RECID = 1
GO
