SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_ELMNT_TGTS]') IS NULL EXEC('CREATE VIEW [dbo].[V_ELMNT_TGTS] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_ELMNT_TGTS]
AS
select
' ' "REPOSITORY_ID",
'com.informatica.powercenter.map.TargetDefinition' "CLASS_ID",
       'Target Definition_' + ltrim(str(targ.TARGET_ID)) "ELEMENT_ID", targ.VERSION_NUMBER "VERSION_NUM",
	   targ.TARGET_NAME "ELEMENT_NAME", targ.TARGET_NAME "ELEMENT_LABEL",
	   '' "ELEMENT_ALIAS", targ.TARGET_DESC "ELEMENT_DESC",
	   '' "ELEMENT_USAGE", 'Application' "ELEMENT_TYPE",
	  'Target Definition' "ELEMENT_SUBTYPE",
	 'BUSINESS_NAME' "ELEMENT_ATTR1", BUSINESS_NAME "ELEMENT_VALUE1",
	 'DATABASE_TYPE' "ELEMENT_ATTR2", mtype.DBTYPE_NAME "ELEMENT_VALUE2",
	 '' "ELEMENT_ATTR3", '' "ELEMENT_VALUE3",
'Y' "VALID_FLAG", 'N' "DISABLED_FLAG",
'' "SRC_CREATE_DT", LAST_SAVED "SRC_UPDATE_DT",
	 '' "EFF_FROM_DT",  '' "EFF_TO_DT",
	   targ.SUBJ_ID	"SUBJECT_ID"
    from OPB_TARG targ,  OPB_MMD_DBTYPE mtype
	where mtype.DBTYPE_ID = DBTYPE and targ.IS_VISIBLE = 1
GO
