SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO
IF OBJECT_ID('[dbo].[V_ELMNT_SRCS]') IS NULL EXEC('CREATE VIEW [dbo].[V_ELMNT_SRCS] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[V_ELMNT_SRCS]
AS
select  ' ' "REPOSITORY_ID", 
'com.informatica.powercenter.map.SourceDefinition' "CLASS_ID", 
'Source Definition_'+ ltrim(str(src.SRC_ID)) "ELEMENT_ID", 
   src.VERSION_NUMBER "VERSION_NUM",
	   src.SOURCE_NAME "ELEMENT_NAME", src.SOURCE_NAME "ELEMENT_LABEL",
	   '' "ELEMENT_ALIAS", src.SRC_DESC "ELEMENT_DESC", 
	   '' "ELEMENT_USAGE", 'Application' "ELEMENT_TYPE", 
	   'Source Definition' "ELEMENT_SUBTYPE", 
	   'BUSINESS_NAME' "ELEMENT_ATTR1", src.BUSINESS_NAME "ELEMENT_VALUE1",
	   'FILE_NAME' "ELEMENT_ATTR2", src.FILE_NAME "ELEMENT_VALUE2", 
	   'OWNER_NAME' "ELEMENT_ATTR3", src.OWNERNAME "ELEMENT_VALUE3",
         'Y' "VALID_FLAG", 'N' "DISABLED_FLAG",
	   '' "SRC_CREATE_DT", LAST_SAVED "SRC_UPDATE_DT",
	   '' "EFF_FROM_DT",  '' "EFF_TO_DT",
	   src.SUBJ_ID	"SUBJECT_ID"
    from OPB_SRC src, OPB_DBD dbd
	where 
	      dbd.DBDID = src.DBDID and dbd.VERSION_NUMBER = src.VERSION_NUMBER
and src.IS_VISIBLE = 1
GO
