
GO
--SqlScripter----[dbo].[APROBACIONES].[IX_APROBACIONES_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_APROBACIONES_2] ON [dbo].[APROBACIONES] (
	[CODIGOCARGO] ASC,
	[CODIGODOCUMENTO] ASC,
	[INSTANCIA] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[APROBACIONES].[IX_APROBACIONES_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_APROBACIONES_3] ON [dbo].[APROBACIONES] (
	[CODIGOCARGO] ASC,
	[INSTANCIA] ASC)
INCLUDE (
	[CODIGODOCUMENTO]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORSDATA_HISTORY].[IX_BS_INDICATORSDATA_HISTORY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_BS_INDICATORSDATA_HISTORY] ON [dbo].[BS_INDICATORSDATA_HISTORY] (
	[BS_INDICATORSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOS].[IX_DOCUMENTOS_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTOS_2] ON [dbo].[DOCUMENTOS] (
	[ESTADO] ASC,
	[CODIGOAPROBACION] ASC,
	[CODIGO] ASC,
	[CODIGOFORODESARROLLO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOS].[IX_DOCUMENTOS_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTOS_3] ON [dbo].[DOCUMENTOS] (
	[ESTADO] ASC,
	[CODIGOAPROBACION] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSMENSAJES].[IX_IKFOROSMENSAJES_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKFOROSMENSAJES_2] ON [dbo].[IKFOROSMENSAJES] (
	[CODIGO] ASC)
INCLUDE (
	[CODIGOUSUARIO],
	[GRADOURGENCIA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSNOVEDADES].[IX_IKFOROSNOVEDADES_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKFOROSNOVEDADES_3] ON [dbo].[IKFOROSNOVEDADES] (
	[CODIGOUSUARIO] ASC,
	[L_LEIDO] ASC,
	[CODIGOPENDIENTE] ASC,
	[CODIGOFORO] ASC)
INCLUDE (
	[CODIGOTIPOPENDIENTE]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSNOVEDADES].[IX_IKFOROSNOVEDADES_4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKFOROSNOVEDADES_4] ON [dbo].[IKFOROSNOVEDADES] (
	[CODIGOUSUARIO] ASC,
	[CODIGOFORO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSSUSCRIPTORES].[IX_IKFOROSSUSCRIPTORES_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKFOROSSUSCRIPTORES_2] ON [dbo].[IKFOROSSUSCRIPTORES] (
	[CODIGOUSUARIO] ASC,
	[CODIGOFORO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSSUSCRIPTORES].[IX_IKFOROSSUSCRIPTORES_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKFOROSSUSCRIPTORES_3] ON [dbo].[IKFOROSSUSCRIPTORES] (
	[CODIGOFORO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKUSERLOGS].[IX_IKUSERLOGS_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKUSERLOGS_1] ON [dbo].[IKUSERLOGS] (
	[INPUTDATE] ASC)
INCLUDE (
	[IKPATHTEXT],
	[IKUSERLOGSID],
	[URL],
	[USERID],
	[USERNAME]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKUSERLOGS].[IX_IKUSERLOGS_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_IKUSERLOGS_3] ON [dbo].[IKUSERLOGS] (
	[URL] ASC,
	[IKPATHTEXT] ASC)
INCLUDE (
	[INPUTDATE]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCMAINPROD].[IX_NCMAINPROD_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCMAINPROD_2] ON [dbo].[NCMAINPROD] (
	[CODIGO] ASC,
	[CODIGOCARGOADMINISTRADOR] ASC,
	[TIPO] ASC)
INCLUDE (
	[DESCRIPCION]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCMAINPROD].[IX_NCMAINPROD_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCMAINPROD_3] ON [dbo].[NCMAINPROD] (
	[TIPO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_1] ON [dbo].[NCTAREAS] (
	[L_CUMPLIDA] ASC,
	[CODIGOFORO] ASC,
	[CODIGO] ASC,
	[CODIGONC] ASC,
	[FECHA] ASC)
INCLUDE (
	[DESCRIPCION],
	[L_NOMOSTRAR],
	[MANDARENFECHA],
	[TIPO_TAREA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_2] ON [dbo].[NCTAREAS] (
	[L_CUMPLIDA] ASC,
	[CODIGOFORO] ASC,
	[CODIGO] ASC,
	[CODIGONC] ASC,
	[FECHA] ASC)
INCLUDE (
	[MANDARENFECHA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_3] ON [dbo].[NCTAREAS] (
	[CODIGONC] ASC,
	[FECHA] ASC,
	[TIPO_TAREA] ASC,
	[OPCIONENVIO] ASC,
	[CODIGO] ASC)
INCLUDE (
	[DIASVENCIMIENTO],
	[FECHALIMITE],
	[L_CUMPLIDA],
	[L_WORKINGDAYS],
	[MANDARENFECHA],
	[OPCIONVENCIMIENTO],
	[PSTARTDATE]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_4] ON [dbo].[NCTAREAS] (
	[CODIGOTAREACONDICIONAL] ASC,
	[CODIGO] ASC,
	[TIPO_TAREA] ASC,
	[CODIGOTAREACONTRIBUYE] ASC)
INCLUDE (
	[CODIGONC],
	[CUMPLIMIENTO],
	[FECHA],
	[L_CUMPLIDA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_5] ON [dbo].[NCTAREAS] (
	[L_CUMPLIDA] ASC,
	[CODIGONC] ASC,
	[TIPO_TAREA] ASC,
	[CODIGO] ASC)
INCLUDE (
	[FECHA],
	[FECHALIMITE],
	[MANDARENFECHA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_6] ON [dbo].[NCTAREAS] (
	[CODIGOTAREACONDICIONAL] ASC)
INCLUDE (
	[CODIGO],
	[DIASVENCIMIENTO],
	[FECHALIMITE],
	[L_WORKINGDAYS],
	[MANDARENFECHA],
	[OPCIONVENCIMIENTO]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_7] ON [dbo].[NCTAREAS] (
	[CODIGONC] ASC,
	[L_CUMPLIDA] ASC,
	[CODIGO] ASC)
INCLUDE (
	[CUMPLIMIENTO],
	[FECHA]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[IX_NCTAREAS_8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREAS_8] ON [dbo].[NCTAREAS] (
	[CODIGOTAREACONTRIBUYE] ASC)
INCLUDE (
	[PENDDATE]
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREASDESTINATARIOS].[IX_NCTAREASDESTINATARIOS_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_NCTAREASDESTINATARIOS_2] ON [dbo].[NCTAREASDESTINATARIOS] (
	[CODIGOCARGO] ASC,
	[CODIGOTAREA] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PERMISOSDOC].[IX_PERMISOSDOC_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_PERMISOSDOC_2] ON [dbo].[PERMISOSDOC] (
	[CODIGOUSUARIO] ASC,
	[CODIGODOCUMENTO] ASC,
	[NIVELACCESO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PERMISOSDOC].[IX_PERMISOSDOC_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_PERMISOSDOC_3] ON [dbo].[PERMISOSDOC] (
	[CODIGOUSUARIO] ASC,
	[CODIGODOCUMENTO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3RESPONSES].[IX_S3RESPONSES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_S3RESPONSES] ON [dbo].[S3RESPONSES] (
	[SURVEYDEF_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TAREASREVISION].[IX_AX_TAREASREVISION_CODIGOPROCESO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_AX_TAREASREVISION_CODIGOPROCESO] ON [dbo].[TAREASREVISION] (
	[CODIGOPROCESO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TAREASREVISION].[IX_AX_TAREASREVISION_CODIGOPROCESO_CODIGOUSUARIO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [IX_AX_TAREASREVISION_CODIGOPROCESO_CODIGOUSUARIO] ON [dbo].[TAREASREVISION] (
	[CODIGOPROCESO] ASC,
	[CODIGOUSUARIO] ASC
) ON [PRIMARY]
