
GO
--SqlScripter----[dbo].[ISP_MASTER_ELECT_LOCK].[UQ__ISP_MAST__D8D3729F32806D04].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ISP_MASTER_ELECT_LOCK] ADD CONSTRAINT [UQ__ISP_MAST__D8D3729F32806D04] UNIQUE NONCLUSTERED (
	[DOMAIN_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ISP_RUN_LOG].[ISP_RUN_LOG_INDEX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [ISP_RUN_LOG_INDEX] ON [dbo].[ISP_RUN_LOG] (
	[INTEGRATIONSERVICE] ASC,
	[REPOSITORYNAME] ASC,
	[REPOSITORYDOMAIN] ASC,
	[RUNCONTEXT] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_DBOBJECT].[PISC_NN_DBOBJECT_ORMSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISC_NN_DBOBJECT_ORMSTATE] ON [dbo].[PC_DBOBJECT] (
	[PCA_ORMSTATE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_NAMESPACE].[PISC_NN_NAMESPACE_REPOSIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISC_NN_NAMESPACE_REPOSIG] ON [dbo].[PC_NAMESPACE] (
	[PCN_REPOSIG] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_NAMESPACE_SEQUENCE].[PISC_NN_NS_SEQ_NAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISC_NN_NS_SEQ_NAMESPACE] ON [dbo].[PC_NAMESPACE_SEQUENCE] (
	[PCA_NAMESPACE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_PACKAGE].[PISC_NN_PACKAGE_REPOSIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISC_NN_PACKAGE_REPOSIG] ON [dbo].[PC_PACKAGE] (
	[PCP_REPOSIG] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ALERT].[PIA_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIA_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_ALERT] (
	[PSA_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ALERT].[UK_PO_ALERT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ALERT] ADD CONSTRAINT [UK_PO_ALERT] UNIQUE NONCLUSTERED (
	[PSA_RSID] ASC,
	[PSA_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ANNOTATION].[PIA_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIA_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_ANNOTATION] (
	[PSA_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ANNOTATION].[UK_PO_ANNOTATION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ANNOTATION] ADD CONSTRAINT [UK_PO_ANNOTATION] UNIQUE NONCLUSTERED (
	[PSA_RSID] ASC,
	[PSA_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ATTRIBUTES].[PIA_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIA_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_ATTRIBUTES] (
	[PSA_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CALUSAGE].[PIC_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_CALUSAGE] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CALUSAGE].[UK_PO_CALUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CALUSAGE] ADD CONSTRAINT [UK_PO_CALUSAGE] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDORG].[PIC_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_CLOUDORG] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDORG].[UK_PO_CLOUDORG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLOUDORG] ADD CONSTRAINT [UK_PO_CLOUDORG] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDSERVICECONFIGURAT].[PIC_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_CLOUDSERVICECONFIGURAT] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDSERVICECONFIGURAT].[UK_PO_CLOUDSERVICECONFIGURAT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLOUDSERVICECONFIGURAT] ADD CONSTRAINT [UK_PO_CLOUDSERVICECONFIGURAT] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLUSTERCONF].[PIC_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_CLUSTERCONF] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLUSTERCONF].[UK_PO_CLUSTERCONF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLUSTERCONF] ADD CONSTRAINT [UK_PO_CLUSTERCONF] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGE].[PIC_NN_PSRESOURCE_CONTA10].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA10] ON [dbo].[PO_CODEPAGE] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGE].[UK_PO_CODEPAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CODEPAGE] ADD CONSTRAINT [UK_PO_CODEPAGE] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGESYSTEM].[PIC_NN_PSRESOURCE_CONTA11].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA11] ON [dbo].[PO_CODEPAGESYSTEM] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGESYSTEM].[UK_PO_CODEPAGESYSTEM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CODEPAGESYSTEM] ADD CONSTRAINT [UK_PO_CODEPAGESYSTEM] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_0].[PIC_NN_PARENTID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTID] ON [dbo].[PO_COLLECTIONENTRY_0] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_0].[PIC_NN_PARENTTYPEID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEID] ON [dbo].[PO_COLLECTIONENTRY_0] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_0].[PIC_NN_PSRESOURCE_CONTA15].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA15] ON [dbo].[PO_COLLECTIONENTRY_0] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_1].[PIC_NN_PARENTI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI1] ON [dbo].[PO_COLLECTIONENTRY_1] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_1].[PIC_NN_PARENTTYPEI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI1] ON [dbo].[PO_COLLECTIONENTRY_1] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_1].[PIC_NN_PSRESOURCE_CONTA16].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA16] ON [dbo].[PO_COLLECTIONENTRY_1] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_2].[PIC_NN_PARENTI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI2] ON [dbo].[PO_COLLECTIONENTRY_2] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_2].[PIC_NN_PARENTTYPEI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI2] ON [dbo].[PO_COLLECTIONENTRY_2] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_2].[PIC_NN_PSRESOURCE_CONTA17].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA17] ON [dbo].[PO_COLLECTIONENTRY_2] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_3].[PIC_NN_PARENTI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI3] ON [dbo].[PO_COLLECTIONENTRY_3] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_3].[PIC_NN_PARENTTYPEI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI3] ON [dbo].[PO_COLLECTIONENTRY_3] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_3].[PIC_NN_PSRESOURCE_CONTA18].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA18] ON [dbo].[PO_COLLECTIONENTRY_3] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_4].[PIC_NN_PARENTI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI4] ON [dbo].[PO_COLLECTIONENTRY_4] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_4].[PIC_NN_PARENTTYPEI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI4] ON [dbo].[PO_COLLECTIONENTRY_4] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_4].[PIC_NN_PSRESOURCE_CONTA19].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA19] ON [dbo].[PO_COLLECTIONENTRY_4] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_5].[PIC_NN_PARENTI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI5] ON [dbo].[PO_COLLECTIONENTRY_5] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_5].[PIC_NN_PARENTTYPEI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI5] ON [dbo].[PO_COLLECTIONENTRY_5] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_5].[PIC_NN_PSRESOURCE_CONTA20].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA20] ON [dbo].[PO_COLLECTIONENTRY_5] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_6].[PIC_NN_PARENTI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI6] ON [dbo].[PO_COLLECTIONENTRY_6] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_6].[PIC_NN_PARENTTYPEI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI6] ON [dbo].[PO_COLLECTIONENTRY_6] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_6].[PIC_NN_PSRESOURCE_CONTA21].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA21] ON [dbo].[PO_COLLECTIONENTRY_6] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_7].[PIC_NN_PARENTI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI7] ON [dbo].[PO_COLLECTIONENTRY_7] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_7].[PIC_NN_PARENTTYPEI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI7] ON [dbo].[PO_COLLECTIONENTRY_7] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_7].[PIC_NN_PSRESOURCE_CONTA22].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA22] ON [dbo].[PO_COLLECTIONENTRY_7] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_8].[PIC_NN_PARENTI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI8] ON [dbo].[PO_COLLECTIONENTRY_8] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_8].[PIC_NN_PARENTTYPEI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI8] ON [dbo].[PO_COLLECTIONENTRY_8] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_8].[PIC_NN_PSRESOURCE_CONTA23].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA23] ON [dbo].[PO_COLLECTIONENTRY_8] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_9].[PIC_NN_PARENTI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTI9] ON [dbo].[PO_COLLECTIONENTRY_9] (
	[POC_GENERIC_REF_PAR_ENTITY] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_9].[PIC_NN_PARENTTYPEI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PARENTTYPEI9] ON [dbo].[PO_COLLECTIONENTRY_9] (
	[POC_GENERIC_REF_PAR_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_9].[PIC_NN_PSRESOURCE_CONTA24].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA24] ON [dbo].[PO_COLLECTIONENTRY_9] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMMAND].[PIC_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_COMMAND] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMMAND].[UK_PO_COMMAND].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COMMAND] ADD CONSTRAINT [UK_PO_COMMAND] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMPUTENODECONFIGURATI].[PIC_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_COMPUTENODECONFIGURATI] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMPUTENODECONFIGURATI].[UK_PO_COMPUTENODECONFIGURATI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COMPUTENODECONFIGURATI] ADD CONSTRAINT [UK_PO_COMPUTENODECONFIGURATI] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFFETCHERPARAMETER].[PIC_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_CONFFETCHERPARAMETER] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFFETCHERPARAMETER].[UK_PO_CONFFETCHERPARAMETER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFFETCHERPARAMETER] ADD CONSTRAINT [UK_PO_CONFFETCHERPARAMETER] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFNAMESPACE].[PIC_NN_PSRESOURCE_CONTAI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI8] ON [dbo].[PO_CONFNAMESPACE] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFNAMESPACE].[UK_PO_CONFNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFNAMESPACE] ADD CONSTRAINT [UK_PO_CONFNAMESPACE] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFPROPERTY].[PIC_NN_PSRESOURCE_CONTAI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI9] ON [dbo].[PO_CONFPROPERTY] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFPROPERTY].[UK_PO_CONFPROPERTY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFPROPERTY] ADD CONSTRAINT [UK_PO_CONFPROPERTY] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTINFO].[PIC_NN_PSRESOURCE_CONTA12].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA12] ON [dbo].[PO_CONNECTINFO] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTINFO].[UK_PO_CONNECTINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONNECTINFO] ADD CONSTRAINT [UK_PO_CONNECTINFO] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTINFOCLASSIFIERC].[PIC_NN_PSRESOURCE_CONTA13].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA13] ON [dbo].[PO_CONNECTINFOCLASSIFIERC] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTIONPOOLATTRIBUT].[PIC_NN_PSRESOURCE_CONTA14].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTA14] ON [dbo].[PO_CONNECTIONPOOLATTRIBUT] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTIONPOOLATTRIBUT].[UK_PO_CONNECTIONPOOLATTRIBUT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONNECTIONPOOLATTRIBUT] ADD CONSTRAINT [UK_PO_CONNECTIONPOOLATTRIBUT] UNIQUE NONCLUSTERED (
	[PSC_NSID] ASC,
	[PSC_EXTERNID] ASC,
	[PSC_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONTEXT].[PIC_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIC_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_CONTEXT] (
	[PSC_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONTEXT].[UK_PO_CONTEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONTEXT] ADD CONSTRAINT [UK_PO_CONTEXT] UNIQUE NONCLUSTERED (
	[PSC_RSID] ASC,
	[PSC_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DATAMAPTYPE].[PID_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_DATAMAPTYPE] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DATAMAPTYPE].[UK_PO_DATAMAPTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DATAMAPTYPE] ADD CONSTRAINT [UK_PO_DATAMAPTYPE] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DBCONNECTIVITY].[PID_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_DBCONNECTIVITY] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DBCONNECTIVITY].[UK_PO_DBCONNECTIVITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DBCONNECTIVITY] ADD CONSTRAINT [UK_PO_DBCONNECTIVITY] UNIQUE NONCLUSTERED (
	[PSD_RSID] ASC,
	[PSD_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DEFAULTOSPROFILE].[PID_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_DEFAULTOSPROFILE] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DEFAULTOSPROFILE].[UK_PO_DEFAULTOSPROFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DEFAULTOSPROFILE] ADD CONSTRAINT [UK_PO_DEFAULTOSPROFILE] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJ].[PID_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_DOMAINOBJ] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJ].[UK_PO_DOMAINOBJ].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINOBJ] ADD CONSTRAINT [UK_PO_DOMAINOBJ] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJECTLOCATE].[PID_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_DOMAINOBJECTLOCATE] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJECTLOCATE].[UK_PO_DOMAINOBJECTLOCATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINOBJECTLOCATE] ADD CONSTRAINT [UK_PO_DOMAINOBJECTLOCATE] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINSERVICECONFIG].[PID_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_DOMAINSERVICECONFIG] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINSERVICECONFIG].[UK_PO_DOMAINSERVICECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINSERVICECONFIG] ADD CONSTRAINT [UK_PO_DOMAINSERVICECONFIG] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINUSAGE].[PID_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PID_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_DOMAINUSAGE] (
	[PSD_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINUSAGE].[UK_PO_DOMAINUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINUSAGE] ADD CONSTRAINT [UK_PO_DOMAINUSAGE] UNIQUE NONCLUSTERED (
	[PSD_NSID] ASC,
	[PSD_EXTERNID] ASC,
	[PSD_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERINFAHOMECONFIG].[PIE_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIE_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_EARLIERINFAHOMECONFIG] (
	[PSE_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERINFAHOMECONFIG].[UK_PO_EARLIERINFAHOMECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EARLIERINFAHOMECONFIG] ADD CONSTRAINT [UK_PO_EARLIERINFAHOMECONFIG] UNIQUE NONCLUSTERED (
	[PSE_RSID] ASC,
	[PSE_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERVERSIONDOMAINOB].[PIE_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIE_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_EARLIERVERSIONDOMAINOB] (
	[PSE_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERVERSIONDOMAINOB].[UK_PO_EARLIERVERSIONDOMAINOB].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EARLIERVERSIONDOMAINOB] ADD CONSTRAINT [UK_PO_EARLIERVERSIONDOMAINOB] UNIQUE NONCLUSTERED (
	[PSE_NSID] ASC,
	[PSE_EXTERNID] ASC,
	[PSE_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ENDPOINT].[PIE_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIE_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_ENDPOINT] (
	[PSE_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ENDPOINT].[UK_PO_ENDPOINT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ENDPOINT] ADD CONSTRAINT [UK_PO_ENDPOINT] UNIQUE NONCLUSTERED (
	[PSE_NSID] ASC,
	[PSE_EXTERNID] ASC,
	[PSE_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONATTRIBUTE].[PIE_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIE_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_EXTENSIONATTRIBUTE] (
	[PSE_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONATTRIBUTE].[UK_PO_EXTENSIONATTRIBUTE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EXTENSIONATTRIBUTE] ADD CONSTRAINT [UK_PO_EXTENSIONATTRIBUTE] UNIQUE NONCLUSTERED (
	[PSE_RSID] ASC,
	[PSE_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONCONTAINER].[PIE_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIE_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_EXTENSIONCONTAINER] (
	[PSE_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONCONTAINER].[UK_PO_EXTENSIONCONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EXTENSIONCONTAINER] ADD CONSTRAINT [UK_PO_EXTENSIONCONTAINER] UNIQUE NONCLUSTERED (
	[PSE_RSID] ASC,
	[PSE_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FEATURE].[PIF_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIF_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_FEATURE] (
	[PSF_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FEATURE].[UK_PO_FEATURE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FEATURE] ADD CONSTRAINT [UK_PO_FEATURE] UNIQUE NONCLUSTERED (
	[PSF_NSID] ASC,
	[PSF_EXTERNID] ASC,
	[PSF_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FILEINF1].[PIF_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIF_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_FILEINF1] (
	[PSF_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FILEINF1].[UK_PO_FILEINF1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FILEINF1] ADD CONSTRAINT [UK_PO_FILEINF1] UNIQUE NONCLUSTERED (
	[PSF_RSID] ASC,
	[PSF_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FILEINFO].[PIF_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIF_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_FILEINFO] (
	[PSF_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FOLDER].[PIF_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIF_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_FOLDER] (
	[PSF_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FOLDER].[UK_PO_FOLDER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FOLDER] ADD CONSTRAINT [UK_PO_FOLDER] UNIQUE NONCLUSTERED (
	[PSF_NSID] ASC,
	[PSF_EXTERNID] ASC,
	[PSF_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FTPCONNECTIONATTRIBUTE].[PIF_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIF_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_FTPCONNECTIONATTRIBUTE] (
	[PSF_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FTPCONNECTIONATTRIBUTE].[UK_PO_FTPCONNECTIONATTRIBUTE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FTPCONNECTIONATTRIBUTE] ADD CONSTRAINT [UK_PO_FTPCONNECTIONATTRIBUTE] UNIQUE NONCLUSTERED (
	[PSF_RSID] ASC,
	[PSF_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_GLOSSARY].[PIG_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIG_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_GLOSSARY] (
	[PSG_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_GLOSSARY].[UK_PO_GLOSSARY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_GLOSSARY] ADD CONSTRAINT [UK_PO_GLOSSARY] UNIQUE NONCLUSTERED (
	[PSG_NSID] ASC,
	[PSG_EXTERNID] ASC,
	[PSG_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPDISTRIBUTION].[PIH_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIH_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_HADOOPDISTRIBUTION] (
	[PSH_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPDISTRIBUTION].[UK_PO_HADOOPDISTRIBUTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HADOOPDISTRIBUTION] ADD CONSTRAINT [UK_PO_HADOOPDISTRIBUTION] UNIQUE NONCLUSTERED (
	[PSH_NSID] ASC,
	[PSH_EXTERNID] ASC,
	[PSH_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPIMPERSONATIONPRO].[PIH_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIH_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_HADOOPIMPERSONATIONPRO] (
	[PSH_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPIMPERSONATIONPRO].[UK_PO_HADOOPIMPERSONATIONPRO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HADOOPIMPERSONATIONPRO] ADD CONSTRAINT [UK_PO_HADOOPIMPERSONATIONPRO] UNIQUE NONCLUSTERED (
	[PSH_RSID] ASC,
	[PSH_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HOSTUSAGE].[PIH_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIH_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_HOSTUSAGE] (
	[PSH_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HOSTUSAGE].[UK_PO_HOSTUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HOSTUSAGE] ADD CONSTRAINT [UK_PO_HOSTUSAGE] UNIQUE NONCLUSTERED (
	[PSH_NSID] ASC,
	[PSH_EXTERNID] ASC,
	[PSH_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPFILEINFO].[PIH_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIH_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_HTTPFILEINFO] (
	[PSH_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPFILEINFO].[UK_PO_HTTPFILEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HTTPFILEINFO] ADD CONSTRAINT [UK_PO_HTTPFILEINFO] UNIQUE NONCLUSTERED (
	[PSH_RSID] ASC,
	[PSH_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPSINFO].[PIH_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIH_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_HTTPSINFO] (
	[PSH_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPSINFO].[UK_PO_HTTPSINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HTTPSINFO] ADD CONSTRAINT [UK_PO_HTTPSINFO] UNIQUE NONCLUSTERED (
	[PSH_RSID] ASC,
	[PSH_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IDOBJ].[PII_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_IDOBJ] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IDOBJ].[UK_PO_IDOBJ].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_IDOBJ] ADD CONSTRAINT [UK_PO_IDOBJ] UNIQUE NONCLUSTERED (
	[PSI_NSID] ASC,
	[PSI_EXTERNID] ASC,
	[PSI_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IMFPACKAGEUPGRADEINFO].[PII_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_IMFPACKAGEUPGRADEINFO] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IMFPACKAGEUPGRADEINFO].[UK_PO_IMFPACKAGEUPGRADEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_IMFPACKAGEUPGRADEINFO] ADD CONSTRAINT [UK_PO_IMFPACKAGEUPGRADEINFO] UNIQUE NONCLUSTERED (
	[PSI_RSID] ASC,
	[PSI_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPBOOLEAN].[PII_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_ISPBOOLEAN] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPBOOLEAN].[UK_PO_ISPBOOLEAN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPBOOLEAN] ADD CONSTRAINT [UK_PO_ISPBOOLEAN] UNIQUE NONCLUSTERED (
	[PSI_NSID] ASC,
	[PSI_EXTERNID] ASC,
	[PSI_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPINTEGER].[PII_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_ISPINTEGER] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPINTEGER].[UK_PO_ISPINTEGER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPINTEGER] ADD CONSTRAINT [UK_PO_ISPINTEGER] UNIQUE NONCLUSTERED (
	[PSI_NSID] ASC,
	[PSI_EXTERNID] ASC,
	[PSI_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPLONG].[PII_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_ISPLONG] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPLONG].[UK_PO_ISPLONG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPLONG] ADD CONSTRAINT [UK_PO_ISPLONG] UNIQUE NONCLUSTERED (
	[PSI_NSID] ASC,
	[PSI_EXTERNID] ASC,
	[PSI_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPSTRING].[PII_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PII_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_ISPSTRING] (
	[PSI_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPSTRING].[UK_PO_ISPSTRING].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPSTRING] ADD CONSTRAINT [UK_PO_ISPSTRING] UNIQUE NONCLUSTERED (
	[PSI_NSID] ASC,
	[PSI_EXTERNID] ASC,
	[PSI_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPNAMESPACE].[PIL_NN_PSRESOURCE_CONTA11].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTA11] ON [dbo].[PO_LDAPNAMESPACE] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPNAMESPACE].[UK_PO_LDAPNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LDAPNAMESPACE] ADD CONSTRAINT [UK_PO_LDAPNAMESPACE] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPOPTIONS].[PIL_NN_PSRESOURCE_CONTA12].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTA12] ON [dbo].[PO_LDAPOPTIONS] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPOPTIONS].[UK_PO_LDAPOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LDAPOPTIONS] ADD CONSTRAINT [UK_PO_LDAPOPTIONS] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEDSERVICE].[PIL_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_LICENSEDSERVICE] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEDSERVICE].[UK_PO_LICENSEDSERVICE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEDSERVICE] ADD CONSTRAINT [UK_PO_LICENSEDSERVICE] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEFEATURES].[PIL_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_LICENSEFEATURES] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEFEATURES].[UK_PO_LICENSEFEATURES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEFEATURES] ADD CONSTRAINT [UK_PO_LICENSEFEATURES] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEHOSTSERVICES].[PIL_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_LICENSEHOSTSERVICES] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEHOSTSERVICES].[UK_PO_LICENSEHOSTSERVICES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEHOSTSERVICES] ADD CONSTRAINT [UK_PO_LICENSEHOSTSERVICES] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEOPTION].[PIL_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_LICENSEOPTION] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEOPTION].[UK_PO_LICENSEOPTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEOPTION] ADD CONSTRAINT [UK_PO_LICENSEOPTION] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEUSAGE].[PIL_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_LICENSEUSAGE] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEUSAGE].[UK_PO_LICENSEUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEUSAGE] ADD CONSTRAINT [UK_PO_LICENSEUSAGE] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINK].[PIL_NN_PSRESOURCE_CONTA13].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTA13] ON [dbo].[PO_LINK] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINK].[UK_PO_LINK].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINK] ADD CONSTRAINT [UK_PO_LINK] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKATTRIBUTES].[PIL_NN_PSRESOURCE_CONTA14].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTA14] ON [dbo].[PO_LINKATTRIBUTES] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKATTRIBUTES].[UK_PO_LINKATTRIBUTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINKATTRIBUTES] ADD CONSTRAINT [UK_PO_LINKATTRIBUTES] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKEDDOMAINSTORAGE].[PIL_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_LINKEDDOMAINSTORAGE] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKEDDOMAINSTORAGE].[UK_PO_LINKEDDOMAINSTORAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINKEDDOMAINSTORAGE] ADD CONSTRAINT [UK_PO_LINKEDDOMAINSTORAGE] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGCALLCONTEXT].[PIL_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_LOGCALLCONTEXT] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGCALLCONTEXT].[UK_PO_LOGCALLCONTEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGCALLCONTEXT] ADD CONSTRAINT [UK_PO_LOGCALLCONTEXT] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGEVENT].[PIL_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_LOGEVENT] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGEVENT].[UK_PO_LOGEVENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGEVENT] ADD CONSTRAINT [UK_PO_LOGEVENT] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICECONFIGURATIO].[PIL_NN_PSRESOURCE_CONTAI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI8] ON [dbo].[PO_LOGSERVICECONFIGURATIO] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICECONFIGURATIO].[UK_PO_LOGSERVICECONFIGURATIO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICECONFIGURATIO] ADD CONSTRAINT [UK_PO_LOGSERVICECONFIGURATIO] UNIQUE NONCLUSTERED (
	[PSL_NSID] ASC,
	[PSL_EXTERNID] ASC,
	[PSL_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEOPTIONS].[PIL_NN_PSRESOURCE_CONTAI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTAI9] ON [dbo].[PO_LOGSERVICEOPTIONS] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEOPTIONS].[UK_PO_LOGSERVICEOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICEOPTIONS] ADD CONSTRAINT [UK_PO_LOGSERVICEOPTIONS] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEPROCESS].[PIL_NN_PSRESOURCE_CONTA10].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIL_NN_PSRESOURCE_CONTA10] ON [dbo].[PO_LOGSERVICEPROCESS] (
	[PSL_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEPROCESS].[UK_PO_LOGSERVICEPROCESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICEPROCESS] ADD CONSTRAINT [UK_PO_LOGSERVICEPROCESS] UNIQUE NONCLUSTERED (
	[PSL_RSID] ASC,
	[PSL_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRY].[PIM_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_MACCESSCONTROLENTRY] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRY].[UK_PO_MACCESSCONTROLENTRY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLENTRY] ADD CONSTRAINT [UK_PO_MACCESSCONTROLENTRY] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRYANN].[PIM_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_MACCESSCONTROLENTRYANN] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRYANN].[UK_PO_MACCESSCONTROLENTRYANN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLENTRYANN] ADD CONSTRAINT [UK_PO_MACCESSCONTROLENTRYANN] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLLIST].[PIM_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_MACCESSCONTROLLIST] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLLIST].[UK_PO_MACCESSCONTROLLIST].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLLIST] ADD CONSTRAINT [UK_PO_MACCESSCONTROLLIST] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MONITORINGSERVICECONFI].[PIM_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_MONITORINGSERVICECONFI] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MONITORINGSERVICECONFI].[UK_PO_MONITORINGSERVICECONFI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MONITORINGSERVICECONFI] ADD CONSTRAINT [UK_PO_MONITORINGSERVICECONFI] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROCESSEDDATAUPGRADE].[PIM_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_MPPROCESSEDDATAUPGRADE] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROCESSEDDATAUPGRADE].[UK_PO_MPPROCESSEDDATAUPGRADE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROCESSEDDATAUPGRADE] ADD CONSTRAINT [UK_PO_MPPROCESSEDDATAUPGRADE] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECT].[PIM_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_MPPROJECT] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECT].[UK_PO_MPPROJECT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROJECT] ADD CONSTRAINT [UK_PO_MPPROJECT] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECTGROUP].[PIM_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_MPPROJECTGROUP] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECTGROUP].[UK_PO_MPPROJECTGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROJECTGROUP] ADD CONSTRAINT [UK_PO_MPPROJECTGROUP] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPSERVICEINFO].[PIM_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIM_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_MPSERVICEINFO] (
	[PSM_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPSERVICEINFO].[UK_PO_MPSERVICEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPSERVICEINFO] ADD CONSTRAINT [UK_PO_MPSERVICEINFO] UNIQUE NONCLUSTERED (
	[PSM_NSID] ASC,
	[PSM_EXTERNID] ASC,
	[PSM_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NAMEVALUEPAIR].[PIN_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_NAMEVALUEPAIR] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NAMEVALUEPAIR].[UK_PO_NAMEVALUEPAIR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NAMEVALUEPAIR] ADD CONSTRAINT [UK_PO_NAMEVALUEPAIR] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEADDRESS].[PIN_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_NODEADDRESS] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEADDRESS].[UK_PO_NODEADDRESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODEADDRESS] ADD CONSTRAINT [UK_PO_NODEADDRESS] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECAPABILITY].[PIN_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_NODECAPABILITY] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECAPABILITY].[UK_PO_NODECAPABILITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODECAPABILITY] ADD CONSTRAINT [UK_PO_NODECAPABILITY] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECONFIG].[PIN_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_NODECONFIG] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECONFIG].[UK_PO_NODECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODECONFIG] ADD CONSTRAINT [UK_PO_NODECONFIG] UNIQUE NONCLUSTERED (
	[PSN_NSID] ASC,
	[PSN_EXTERNID] ASC,
	[PSN_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEREF].[PIN_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_NODEREF] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEREF].[UK_PO_NODEREF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODEREF] ADD CONSTRAINT [UK_PO_NODEREF] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODERESOURCE].[PIN_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_NODERESOURCE] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODERESOURCE].[UK_PO_NODERESOURCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODERESOURCE] ADD CONSTRAINT [UK_PO_NODERESOURCE] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESAMLCONFIG].[PIN_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_NODESAMLCONFIG] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESAMLCONFIG].[UK_PO_NODESAMLCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODESAMLCONFIG] ADD CONSTRAINT [UK_PO_NODESAMLCONFIG] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESERVICES].[PIN_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIN_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_NODESERVICES] (
	[PSN_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESERVICES].[UK_PO_NODESERVICES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODESERVICES] ADD CONSTRAINT [UK_PO_NODESERVICES] UNIQUE NONCLUSTERED (
	[PSN_RSID] ASC,
	[PSN_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTGRAPHDECORATION].[PIO_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_OBJECTGRAPHDECORATION] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTGRAPHDECORATION].[UK_PO_OBJECTGRAPHDECORATION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OBJECTGRAPHDECORATION] ADD CONSTRAINT [UK_PO_OBJECTGRAPHDECORATION] UNIQUE NONCLUSTERED (
	[PSO_NSID] ASC,
	[PSO_EXTERNID] ASC,
	[PSO_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTREFERENCE].[PIO_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_OBJECTREFERENCE] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTREFERENCE].[UK_PO_OBJECTREFERENCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OBJECTREFERENCE] ADD CONSTRAINT [UK_PO_OBJECTREFERENCE] UNIQUE NONCLUSTERED (
	[PSO_NSID] ASC,
	[PSO_EXTERNID] ASC,
	[PSO_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTION].[PIO_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_OPTION] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTION].[UK_PO_OPTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OPTION] ADD CONSTRAINT [UK_PO_OPTION] UNIQUE NONCLUSTERED (
	[PSO_RSID] ASC,
	[PSO_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTIONGROUP].[PIO_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_OPTIONGROUP] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTIONGROUP].[UK_PO_OPTIONGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OPTIONGROUP] ADD CONSTRAINT [UK_PO_OPTIONGROUP] UNIQUE NONCLUSTERED (
	[PSO_NSID] ASC,
	[PSO_EXTERNID] ASC,
	[PSO_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILE].[PIO_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_OSPROFILE] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILE].[UK_PO_OSPROFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OSPROFILE] ADD CONSTRAINT [UK_PO_OSPROFILE] UNIQUE NONCLUSTERED (
	[PSO_NSID] ASC,
	[PSO_EXTERNID] ASC,
	[PSO_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILEPRODUCTEXTENS].[PIO_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIO_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_OSPROFILEPRODUCTEXTENS] (
	[PSO_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILEPRODUCTEXTENS].[UK_PO_OSPROFILEPRODUCTEXTENS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OSPROFILEPRODUCTEXTENS] ADD CONSTRAINT [UK_PO_OSPROFILEPRODUCTEXTENS] UNIQUE NONCLUSTERED (
	[PSO_RSID] ASC,
	[PSO_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETER].[PIP_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_PARAMETER] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETER].[UK_PO_PARAMETER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETER] ADD CONSTRAINT [UK_PO_PARAMETER] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERCONTAINER].[PIP_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_PARAMETERCONTAINER] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERCONTAINER].[UK_PO_PARAMETERCONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERCONTAINER] ADD CONSTRAINT [UK_PO_PARAMETERCONTAINER] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERREFERENCE].[PIP_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_PARAMETERREFERENCE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERTYPE].[PIP_NN_PSRESOURCE_CONTAI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI8] ON [dbo].[PO_PARAMETERTYPE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERTYPE].[UK_PO_PARAMETERTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERTYPE] ADD CONSTRAINT [UK_PO_PARAMETERTYPE] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERVALUE].[PIP_NN_PSRESOURCE_CONTAI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI9] ON [dbo].[PO_PARAMETERVALUE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERVALUE].[UK_PO_PARAMETERVALUE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERVALUE] ADD CONSTRAINT [UK_PO_PARAMETERVALUE] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PCAPABILITYINFO].[PIP_NN_PSRESOURCE_CONTA11].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTA11] ON [dbo].[PO_PCAPABILITYINFO] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PCAPABILITYINFO].[UK_PO_PCAPABILITYINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PCAPABILITYINFO] ADD CONSTRAINT [UK_PO_PCAPABILITYINFO] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PIMFPACKAGEINFO].[PIP_NN_PSRESOURCE_CONTA12].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTA12] ON [dbo].[PO_PIMFPACKAGEINFO] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PIMFPACKAGEINFO].[UK_PO_PIMFPACKAGEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PIMFPACKAGEINFO] ADD CONSTRAINT [UK_PO_PIMFPACKAGEINFO] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PLUGIN].[PIP_NN_PSRESOURCE_CONTA10].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTA10] ON [dbo].[PO_PLUGIN] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PLUGIN].[UK_PO_PLUGIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PLUGIN] ADD CONSTRAINT [UK_PO_PLUGIN] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREFERENCE].[PIP_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_PREFERENCE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREFERENCEGROUP].[PIP_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_PREFERENCEGROUP] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREFERENCEGROUP].[UK_PO_PREFERENCEGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PREFERENCEGROUP] ADD CONSTRAINT [UK_PO_PREFERENCEGROUP] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREGISTEREDCAPABILITIE].[PIP_NN_PSRESOURCE_CONTA13].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTA13] ON [dbo].[PO_PREGISTEREDCAPABILITIE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREGISTEREDCAPABILITIE].[UK_PO_PREGISTEREDCAPABILITIE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PREGISTEREDCAPABILITIE] ADD CONSTRAINT [UK_PO_PREGISTEREDCAPABILITIE] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PRIVILEGE].[PIP_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_PRIVILEGE] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PRIVILEGE].[UK_PO_PRIVILEGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PRIVILEGE] ADD CONSTRAINT [UK_PO_PRIVILEGE] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESS].[PIP_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_PROCESS] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESS].[UK_PO_PROCESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PROCESS] ADD CONSTRAINT [UK_PO_PROCESS] UNIQUE NONCLUSTERED (
	[PSP_NSID] ASC,
	[PSP_EXTERNID] ASC,
	[PSP_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESSRUNTIME].[PIP_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIP_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_PROCESSRUNTIME] (
	[PSP_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESSRUNTIME].[UK_PO_PROCESSRUNTIME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PROCESSRUNTIME] ADD CONSTRAINT [UK_PO_PROCESSRUNTIME] UNIQUE NONCLUSTERED (
	[PSP_RSID] ASC,
	[PSP_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDLOGFILE].[PIR_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_REGISTEREDLOGFILE] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDLOGFILE].[UK_PO_REGISTEREDLOGFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDLOGFILE] ADD CONSTRAINT [UK_PO_REGISTEREDLOGFILE] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUN].[PIR_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_REGISTEREDRUN] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUN].[UK_PO_REGISTEREDRUN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDRUN] ADD CONSTRAINT [UK_PO_REGISTEREDRUN] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUNLOG].[PIR_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_REGISTEREDRUNLOG] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUNLOG].[UK_PO_REGISTEREDRUNLOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDRUNLOG] ADD CONSTRAINT [UK_PO_REGISTEREDRUNLOG] UNIQUE NONCLUSTERED (
	[PSR_NSID] ASC,
	[PSR_EXTERNID] ASC,
	[PSR_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPORTSELECTIONGROUP].[PIR_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_REPORTSELECTIONGROUP] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPORTSELECTIONGROUP].[UK_PO_REPORTSELECTIONGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPORTSELECTIONGROUP] ADD CONSTRAINT [UK_PO_REPORTSELECTIONGROUP] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYOPERATIONALI].[PIR_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_REPOSITORYOPERATIONALI] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYOPERATIONALI].[UK_PO_REPOSITORYOPERATIONALI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPOSITORYOPERATIONALI] ADD CONSTRAINT [UK_PO_REPOSITORYOPERATIONALI] UNIQUE NONCLUSTERED (
	[PSR_NSID] ASC,
	[PSR_EXTERNID] ASC,
	[PSR_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYUPGRADEINFO].[PIR_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_REPOSITORYUPGRADEINFO] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYUPGRADEINFO].[UK_PO_REPOSITORYUPGRADEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPOSITORYUPGRADEINFO] ADD CONSTRAINT [UK_PO_REPOSITORYUPGRADEINFO] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_RESOURCESTRING].[PIR_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_RESOURCESTRING] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_RESOURCESTRING].[UK_PO_RESOURCESTRING].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_RESOURCESTRING] ADD CONSTRAINT [UK_PO_RESOURCESTRING] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ROLETYPECONTAINER].[PIR_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIR_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_ROLETYPECONTAINER] (
	[PSR_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ROLETYPECONTAINER].[UK_PO_ROLETYPECONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ROLETYPECONTAINER] ADD CONSTRAINT [UK_PO_ROLETYPECONTAINER] UNIQUE NONCLUSTERED (
	[PSR_RSID] ASC,
	[PSR_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SAMLCONFIG].[PIS_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_SAMLCONFIG] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SAMLCONFIG].[UK_PO_SAMLCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SAMLCONFIG] ADD CONSTRAINT [UK_PO_SAMLCONFIG] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTBASEATTRIBUT].[PIS_NN_PSRESOURCE_CONTA13].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA13] ON [dbo].[PO_SDKCONNECTBASEATTRIBUT] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTBASEATTRIBUT].[UK_PO_SDKCONNECTBASEATTRIBUT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTBASEATTRIBUT] ADD CONSTRAINT [UK_PO_SDKCONNECTBASEATTRIBUT] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOATTR].[PIS_NN_PSRESOURCE_CONTA17].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA17] ON [dbo].[PO_SDKCONNECTINFOATTR] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOATTR].[UK_PO_SDKCONNECTINFOATTR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTINFOATTR] ADD CONSTRAINT [UK_PO_SDKCONNECTINFOATTR] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOMODELEXT].[PIS_NN_PSRESOURCE_CONTA14].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA14] ON [dbo].[PO_SDKCONNECTINFOMODELEXT] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOMODELEXT].[UK_PO_SDKCONNECTINFOMODELEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTINFOMODELEXT] ADD CONSTRAINT [UK_PO_SDKCONNECTINFOMODELEXT] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONATTRDEF].[PIS_NN_PSRESOURCE_CONTA18].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA18] ON [dbo].[PO_SDKCONNECTIONATTRDEF] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONATTRDEF].[UK_PO_SDKCONNECTIONATTRDEF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTIONATTRDEF] ADD CONSTRAINT [UK_PO_SDKCONNECTIONATTRDEF] UNIQUE NONCLUSTERED (
	[PSS_NSID] ASC,
	[PSS_EXTERNID] ASC,
	[PSS_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONTYPE].[PIS_NN_PSRESOURCE_CONTA19].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA19] ON [dbo].[PO_SDKCONNECTIONTYPE] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONTYPE].[UK_PO_SDKCONNECTIONTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTIONTYPE] ADD CONSTRAINT [UK_PO_SDKCONNECTIONTYPE] UNIQUE NONCLUSTERED (
	[PSS_NSID] ASC,
	[PSS_EXTERNID] ASC,
	[PSS_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYCONFIG].[PIS_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_SECURITYCONFIG] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYCONFIG].[UK_PO_SECURITYCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SECURITYCONFIG] ADD CONSTRAINT [UK_PO_SECURITYCONFIG] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYDOMAIN].[PIS_NN_PSRESOURCE_CONTAI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI8] ON [dbo].[PO_SECURITYDOMAIN] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYDOMAIN].[UK_PO_SECURITYDOMAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SECURITYDOMAIN] ADD CONSTRAINT [UK_PO_SECURITYDOMAIN] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPRIVILEGEDEF].[PIS_NN_PSRESOURCE_CONTAI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI9] ON [dbo].[PO_SERVICEPRIVILEGEDEF] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPRIVILEGEDEF].[UK_PO_SERVICEPRIVILEGEDEF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEPRIVILEGEDEF] ADD CONSTRAINT [UK_PO_SERVICEPRIVILEGEDEF] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPROCESSSTARTUPS].[PIS_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_SERVICEPROCESSSTARTUPS] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPROCESSSTARTUPS].[UK_PO_SERVICEPROCESSSTARTUPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEPROCESSSTARTUPS] ADD CONSTRAINT [UK_PO_SERVICEPROCESSSTARTUPS] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEREF].[PIS_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_SERVICEREF] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEREF].[UK_PO_SERVICEREF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEREF] ADD CONSTRAINT [UK_PO_SERVICEREF] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICERUNTIME].[PIS_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_SERVICERUNTIME] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICERUNTIME].[UK_PO_SERVICERUNTIME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICERUNTIME] ADD CONSTRAINT [UK_PO_SERVICERUNTIME] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICESTARTUPSTATE].[PIS_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_SERVICESTARTUPSTATE] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICESTARTUPSTATE].[UK_PO_SERVICESTARTUPSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICESTARTUPSTATE] ADD CONSTRAINT [UK_PO_SERVICESTARTUPSTATE] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SMTPOPTIONS].[PIS_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_SMTPOPTIONS] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SMTPOPTIONS].[UK_PO_SMTPOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SMTPOPTIONS] ADD CONSTRAINT [UK_PO_SMTPOPTIONS] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORT].[PIS_NN_PSRESOURCE_CONTA10].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA10] ON [dbo].[PO_SORT] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORT].[UK_PO_SORT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORT] ADD CONSTRAINT [UK_PO_SORT] UNIQUE NONCLUSTERED (
	[PSS_NSID] ASC,
	[PSS_EXTERNID] ASC,
	[PSS_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTPORT].[PIS_NN_PSRESOURCE_CONTA12].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA12] ON [dbo].[PO_SORTPORT] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTPORT].[UK_PO_SORTPORT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORTPORT] ADD CONSTRAINT [UK_PO_SORTPORT] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTSYSTEM].[PIS_NN_PSRESOURCE_CONTA11].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA11] ON [dbo].[PO_SORTSYSTEM] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTSYSTEM].[UK_PO_SORTSYSTEM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORTSYSTEM] ADD CONSTRAINT [UK_PO_SORTSYSTEM] UNIQUE NONCLUSTERED (
	[PSS_NSID] ASC,
	[PSS_EXTERNID] ASC,
	[PSS_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STAGINGINFOATTRIBUTES].[PIS_NN_PSRESOURCE_CONTA16].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA16] ON [dbo].[PO_STAGINGINFOATTRIBUTES] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STAGINGINFOATTRIBUTES].[UK_PO_STAGINGINFOATTRIBUTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_STAGINGINFOATTRIBUTES] ADD CONSTRAINT [UK_PO_STAGINGINFOATTRIBUTES] UNIQUE NONCLUSTERED (
	[PSS_RSID] ASC,
	[PSS_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STOREDSTARTUPSTATE].[PIS_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_STOREDSTARTUPSTATE] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STOREDSTARTUPSTATE].[UK_PO_STOREDSTARTUPSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_STOREDSTARTUPSTATE] ADD CONSTRAINT [UK_PO_STOREDSTARTUPSTATE] UNIQUE NONCLUSTERED (
	[PSS_NSID] ASC,
	[PSS_EXTERNID] ASC,
	[PSS_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STRINGVALUE].[PIS_NN_PSRESOURCE_CONTA15].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA15] ON [dbo].[PO_STRINGVALUE] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SUBSTITUTEHOLDER].[PIS_NN_PSRESOURCE_CONTA20].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIS_NN_PSRESOURCE_CONTA20] ON [dbo].[PO_SUBSTITUTEHOLDER] (
	[PSS_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAG].[PIT_NN_PSRESOURCE_CONTAI8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI8] ON [dbo].[PO_TAG] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAG].[UK_PO_TAG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TAG] ADD CONSTRAINT [UK_PO_TAG] UNIQUE NONCLUSTERED (
	[PST_NSID] ASC,
	[PST_EXTERNID] ASC,
	[PST_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAGLINKS].[PIT_NN_PSRESOURCE_CONTAI9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI9] ON [dbo].[PO_TAGLINKS] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAGLINKS].[UK_PO_TAGLINKS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TAGLINKS] ADD CONSTRAINT [UK_PO_TAGLINKS] UNIQUE NONCLUSTERED (
	[PST_NSID] ASC,
	[PST_EXTERNID] ASC,
	[PST_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TIMEOFDAY].[PIT_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_TIMEOFDAY] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TIMEOFDAY].[UK_PO_TIMEOFDAY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TIMEOFDAY] ADD CONSTRAINT [UK_PO_TIMEOFDAY] UNIQUE NONCLUSTERED (
	[PST_RSID] ASC,
	[PST_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPE].[PIT_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_TYPE] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPE].[UK_PO_TYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPE] ADD CONSTRAINT [UK_PO_TYPE] UNIQUE NONCLUSTERED (
	[PST_NSID] ASC,
	[PST_EXTERNID] ASC,
	[PST_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEACONNECTIONATTRIBU].[PIT_NN_PSRESOURCE_CONTAI5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI5] ON [dbo].[PO_TYPEACONNECTIONATTRIBU] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEACONNECTIONATTRIBU].[UK_PO_TYPEACONNECTIONATTRIBU].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEACONNECTIONATTRIBU] ADD CONSTRAINT [UK_PO_TYPEACONNECTIONATTRIBU] UNIQUE NONCLUSTERED (
	[PST_RSID] ASC,
	[PST_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEBCONNECTIONATTRIBU].[PIT_NN_PSRESOURCE_CONTAI6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI6] ON [dbo].[PO_TYPEBCONNECTIONATTRIBU] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEBCONNECTIONATTRIBU].[UK_PO_TYPEBCONNECTIONATTRIBU].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEBCONNECTIONATTRIBU] ADD CONSTRAINT [UK_PO_TYPEBCONNECTIONATTRIBU] UNIQUE NONCLUSTERED (
	[PST_RSID] ASC,
	[PST_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONFIG].[PIT_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_TYPECONFIG] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONFIG].[UK_PO_TYPECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPECONFIG] ADD CONSTRAINT [UK_PO_TYPECONFIG] UNIQUE NONCLUSTERED (
	[PST_RSID] ASC,
	[PST_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONTAINER].[PIT_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_TYPECONTAINER] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONTAINER].[UK_PO_TYPECONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPECONTAINER] ADD CONSTRAINT [UK_PO_TYPECONTAINER] UNIQUE NONCLUSTERED (
	[PST_NSID] ASC,
	[PST_EXTERNID] ASC,
	[PST_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEDELEMENT].[PIT_NN_PSRESOURCE_CONTAI4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI4] ON [dbo].[PO_TYPEDELEMENT] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEDELEMENT].[UK_PO_TYPEDELEMENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEDELEMENT] ADD CONSTRAINT [UK_PO_TYPEDELEMENT] UNIQUE NONCLUSTERED (
	[PST_NSID] ASC,
	[PST_EXTERNID] ASC,
	[PST_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPERCONNECTIONATTRIBU].[PIT_NN_PSRESOURCE_CONTAI7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIT_NN_PSRESOURCE_CONTAI7] ON [dbo].[PO_TYPERCONNECTIONATTRIBU] (
	[PST_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPERCONNECTIONATTRIBU].[UK_PO_TYPERCONNECTIONATTRIBU].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPERCONNECTIONATTRIBU] ADD CONSTRAINT [UK_PO_TYPERCONNECTIONATTRIBU] UNIQUE NONCLUSTERED (
	[PST_RSID] ASC,
	[PST_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UMSERVICECONFIG].[PIU_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIU_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_UMSERVICECONFIG] (
	[PSU_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UMSERVICECONFIG].[UK_PO_UMSERVICECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_UMSERVICECONFIG] ADD CONSTRAINT [UK_PO_UMSERVICECONFIG] UNIQUE NONCLUSTERED (
	[PSU_NSID] ASC,
	[PSU_EXTERNID] ASC,
	[PSU_PRSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERACCOUNTSECURITYCON].[PIU_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIU_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_USERACCOUNTSECURITYCON] (
	[PSU_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERACCOUNTSECURITYCON].[UK_PO_USERACCOUNTSECURITYCON].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_USERACCOUNTSECURITYCON] ADD CONSTRAINT [UK_PO_USERACCOUNTSECURITYCON] UNIQUE NONCLUSTERED (
	[PSU_RSID] ASC,
	[PSU_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERINFO].[PIU_NN_PSRESOURCE_CONTAI2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIU_NN_PSRESOURCE_CONTAI2] ON [dbo].[PO_USERINFO] (
	[PSU_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERINFO].[UK_PO_USERINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_USERINFO] ADD CONSTRAINT [UK_PO_USERINFO] UNIQUE NONCLUSTERED (
	[PSU_RSID] ASC,
	[PSU_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UUMNAMESPACE].[PIU_NN_PSRESOURCE_CONTAI3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIU_NN_PSRESOURCE_CONTAI3] ON [dbo].[PO_UUMNAMESPACE] (
	[PSU_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UUMNAMESPACE].[UK_PO_UUMNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_UUMNAMESPACE] ADD CONSTRAINT [UK_PO_UUMNAMESPACE] UNIQUE NONCLUSTERED (
	[PSU_RSID] ASC,
	[PSU_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_VALUE].[PIV_NN_PSRESOURCE_CONTAI1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIV_NN_PSRESOURCE_CONTAI1] ON [dbo].[PO_VALUE] (
	[PSV_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_VALUETYPE].[PIV_NN_PSRESOURCE_CONTAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIV_NN_PSRESOURCE_CONTAIN] ON [dbo].[PO_VALUETYPE] (
	[PSV_CONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_VALUETYPE].[UK_PO_VALUETYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_VALUETYPE] ADD CONSTRAINT [UK_PO_VALUETYPE] UNIQUE NONCLUSTERED (
	[PSV_RSID] ASC,
	[PSV_INTERNID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[PIA_ATTRIBUTE_VALUEPARENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIA_ATTRIBUTE_VALUEPARENT] ON [dbo].[PR_ATTRIBUTE] (
	[PRD_ATTR_VALUE] ASC,
	[PRD_PARENTCONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[PIA_NN_ATTRIBUTE_RESOURCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PIA_NN_ATTRIBUTE_RESOURCE] ON [dbo].[PR_ATTRIBUTE] (
	[PRA_RESOURCE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[PISR_NN_ATTR_RS_PARENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_ATTR_RS_PARENT] ON [dbo].[PR_ATTRIBUTE] (
	[PRD_PARENTCONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[PISR_NN_ATTRIBUTE_NAME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_ATTRIBUTE_NAME] ON [dbo].[PR_ATTRIBUTE] (
	[PRD_ATTR_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_ATTRIBUTE].[PISR_NN_ATTRIBUTE_VALUE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_ATTRIBUTE_VALUE] ON [dbo].[PR_ATTRIBUTE] (
	[PRD_ATTR_VALUE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_GANNOTATIONS].[PISR_NN_ANNOT_RESOURCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_ANNOT_RESOURCE] ON [dbo].[PR_GANNOTATIONS] (
	[PRA_RESOURCE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_NAME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_NAME] ON [dbo].[PR_RESOURCE] (
	[PRR_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_NSID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_NSID] ON [dbo].[PR_RESOURCE] (
	[PRR_NSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_PARENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_PARENT] ON [dbo].[PR_RESOURCE] (
	[PRR_PARENTCONTAINER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_PARENTID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_PARENTID] ON [dbo].[PR_RESOURCE] (
	[PRR_PARENTID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_PARENTPATH].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_PARENTPATH] ON [dbo].[PR_RESOURCE] (
	[PRR_PARENTPATH] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_NN_RESOURCE_RELROOT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_RESOURCE_RELROOT] ON [dbo].[PR_RESOURCE] (
	[PRR_RELROOT] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_UN_UNIQUERSBYPPATH].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [PISR_UN_UNIQUERSBYPPATH] ON [dbo].[PR_RESOURCE] (
	[PRR_NSID] ASC,
	[PRR_RELROOT] ASC,
	[PRR_PARENTPATH] ASC,
	[PRR_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PK_PR_RESOURCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PR_RESOURCE] ADD CONSTRAINT [PK_PR_RESOURCE] PRIMARY KEY NONCLUSTERED (
	[PRR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RSID_TXID].[PISR_NN_TXID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [PISR_NN_TXID] ON [dbo].[PR_RSID_TXID] (
	[PRD_TXID] ASC
) ON [PRIMARY]
