
GO
--SqlScripter----[dbo].[OPB_ANALYZE_DEP].[OPB_ANAL_DEP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_ANAL_DEP_IDX] ON [dbo].[OPB_ANALYZE_DEP] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_ATTR].[OPB_ATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_ATTR_IDX] ON [dbo].[OPB_ATTR] (
	[OBJECT_TYPE_ID] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_ATTR_CATEGORY].[OPB_ATTRCAT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_ATTRCAT_IDX] ON [dbo].[OPB_ATTR_CATEGORY] (
	[CATEGORY_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_BCF_BUSCOMPS].[OPB_BCFBCOMPS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_BCFBCOMPS_IDX] ON [dbo].[OPB_BCF_BUSCOMPS] (
	[BUSCOMP_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_BCF_TREE].[OPB_BCF_TREE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_BCF_TREE_IDX] ON [dbo].[OPB_BCF_TREE] (
	[BCFNODE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CFG_ATTR].[OPB_CFG_ATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_CFG_ATTR_IDX] ON [dbo].[OPB_CFG_ATTR] (
	[SESSION_ID] ASC,
	[CONFIG_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CLIENT_CONN].[OPB_CCONN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_CCONN] ON [dbo].[OPB_CLIENT_CONN] (
	[CNX_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPDETAIL].[OPB_DEPDETAIL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DEPDETAIL_IDX] ON [dbo].[OPB_CM_DEPDETAIL] (
	[DEP_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPLOY].[OPB_DEPLOY_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_DEPLOY_IDX] ON [dbo].[OPB_CM_DEPLOY] (
	[DEP_GROUP_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPLOY_LOG].[OPB_DEP_LOG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DEP_LOG_IDX] ON [dbo].[OPB_CM_DEPLOY_LOG] (
	[DEP_GROUP_ID] ASC,
	[DEPLOY_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPLOY_REF].[OPB_DEPLOYREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DEPLOYREF_IDX] ON [dbo].[OPB_CM_DEPLOY_REF] (
	[DEP_GROUP_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPLOY_REF].[OPB_DEPLOYREF_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DEPLOYREF_IDX2] ON [dbo].[OPB_CM_DEPLOY_REF] (
	[SUBJECT_ID] ASC,
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_DEPLOY_REF].[OPB_DEPLOYREF_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_DEPLOYREF_IDX3] ON [dbo].[OPB_CM_DEPLOY_REF] (
	[DEP_GROUP_ID] ASC,
	[SUBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[OBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_LABEL].[OPB_CM_LABEL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_CM_LABEL_IDX] ON [dbo].[OPB_CM_LABEL] (
	[LABEL_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_LABEL_REF].[OPB_LABELREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LABELREF_IDX] ON [dbo].[OPB_CM_LABEL_REF] (
	[LABEL_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_LABEL_REF].[OPB_LABELREF_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LABELREF_IDX2] ON [dbo].[OPB_CM_LABEL_REF] (
	[SUBJECT_ID] ASC,
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_QUERY].[OPB_CM_QUERY_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_CM_QUERY_IDX] ON [dbo].[OPB_CM_QUERY] (
	[QUERY_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CM_QUERY_PARAM].[OPB_QUERYPARAM_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_QUERYPARAM_IDX] ON [dbo].[OPB_CM_QUERY_PARAM] (
	[QUERY_ID] ASC,
	[DISPLAY_ORDER] ASC,
	[LINE_NO] ASC,
	[LEVEL_NO] ASC,
	[INPUT_NO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CNX].[OPB_CNX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_CNX_IDX] ON [dbo].[OPB_CNX] (
	[OBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_CNX].[OPB_CNX_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_CNX_IDX2] ON [dbo].[OPB_CNX] (
	[OBJECT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_COMPONENT].[OPB_SESCOMP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCOMP_IDX] ON [dbo].[OPB_COMPONENT] (
	[WORKFLOW_ID] ASC,
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_COMPONENT].[OPB_SESCOMP_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCOMP_IDX2] ON [dbo].[OPB_COMPONENT] (
	[REF_OBJ_ID] ASC,
	[OBJECT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_COMPONENT].[OPB_SESCOMP_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCOMP_IDX3] ON [dbo].[OPB_COMPONENT] (
	[TASK_ID] ASC,
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC,
	[TASK_INST_ID] ASC,
	[REF_VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_COMPONENT].[OPB_SESCOMP_IDX4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCOMP_IDX4] ON [dbo].[OPB_COMPONENT] (
	[WORKFLOW_ID] ASC,
	[REF_OBJ_ID] ASC,
	[TASK_INST_ID] ASC,
	[OBJECT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_COMPONENT].[OPB_SESCOMP_IDX5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCOMP_IDX5] ON [dbo].[OPB_COMPONENT] (
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC,
	[OBJECT_TYPE] ASC,
	[REF_OBJ_ID] ASC,
	[WORKFLOW_ID] ASC,
	[TASK_INST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_DBD].[OPB_DBD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_DBD_IDX] ON [dbo].[OPB_DBD] (
	[DBDID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_DBD].[OPB_DBD2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DBD2] ON [dbo].[OPB_DBD] (
	[SUBJ_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_DBDS].[OPB_DBDS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DBDS_IDX] ON [dbo].[OPB_DBDS] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_DTL_SWIDG_LOG].[OPB_DTLWIDLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DTLWIDLG_IDX] ON [dbo].[OPB_DTL_SWIDG_LOG] (
	[WORKFLOW_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EVENT].[OPB_EVENT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_EVENT_IDX] ON [dbo].[OPB_EVENT] (
	[EVENT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EVENT].[OPB_EVENT_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_EVENT_IDX2] ON [dbo].[OPB_EVENT] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EXPRESSION].[OPB_EXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_EXPR_IDX] ON [dbo].[OPB_EXPRESSION] (
	[EXPR_ID] ASC,
	[LINE_NO] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EXPRESSION].[OPB_EXPR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_EXPR_IDX2] ON [dbo].[OPB_EXPRESSION] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EXTN_ATTR].[OPB_EXTNATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_EXTNATTR_IDX] ON [dbo].[OPB_EXTN_ATTR] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_EXTN_ATTR].[OPB_EXTNATTR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_EXTNATTR_IDX2] ON [dbo].[OPB_EXTN_ATTR] (
	[WORKFLOW_ID] ASC,
	[SESSION_INST_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_FILE_DESC].[OPB_FILEDESC_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_FILEDESC_IDX] ON [dbo].[OPB_FILE_DESC] (
	[SUBJECT_ID] ASC,
	[FILE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_FILE_DESC].[OPB_FILEDESC_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_FILEDESC_IDX2] ON [dbo].[OPB_FILE_DESC] (
	[FILE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_GEN_OBJECT].[OPB_GENOBJ_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_GENOBJ_IDX] ON [dbo].[OPB_GEN_OBJECT] (
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_GEN_OBJECT].[OPB_GENOBJ_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_GENOBJ_IDX2] ON [dbo].[OPB_GEN_OBJECT] (
	[SUBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_GROUPS].[OPB_GROUP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_GROUP_IDX] ON [dbo].[OPB_GROUPS] (
	[GROUP_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_HASH_KEY].[OPB_HASHKEY_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_HASHKEY_IDX] ON [dbo].[OPB_HASH_KEY] (
	[SESSION_ID] ASC,
	[SWIDGET_INST_ID] ASC,
	[KEY_NAME] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_KEY_RANGE].[OPB_KEYRANGE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_KEYRANGE_IDX] ON [dbo].[OPB_KEY_RANGE] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_KEYWORD].[OPB_KEYWORD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_KEYWORD_IDX] ON [dbo].[OPB_KEYWORD] (
	[TARGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_LINK_MCR_DEP].[OPB_LINK_MCR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LINK_MCR_IDX] ON [dbo].[OPB_LINK_MCR_DEP] (
	[WORKFLOW_ID] ASC,
	[CONDITION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_LINK_MCR_DEP].[OPB_LINK_MCR_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LINK_MCR_IDX1] ON [dbo].[OPB_LINK_MCR_DEP] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_LINK_MCR_DEP].[OPB_LINK_MCR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LINK_MCR_IDX2] ON [dbo].[OPB_LINK_MCR_DEP] (
	[SUBJECT_ID] ASC,
	[MACRO_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MACRO].[OPB_MACRO_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MACRO_IDX] ON [dbo].[OPB_MACRO] (
	[MACRO_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MACRO].[OPB_MACRO_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MACRO_IDX1] ON [dbo].[OPB_MACRO] (
	[SUBJECT_ID] ASC,
	[MACRO_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MACRO_ARGS].[OPB_MACRO_ARGS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MACRO_ARGS_IDX] ON [dbo].[OPB_MACRO_ARGS] (
	[MACRO_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MACRO_EXPR].[OPB_MACRO_EXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MACRO_EXPR_IDX] ON [dbo].[OPB_MACRO_EXPR] (
	[MACRO_ID] ASC,
	[VERSION_NUMBER] ASC,
	[LINE_NO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MACRO_REF].[OPB_MACRO_REF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MACRO_REF_IDX] ON [dbo].[OPB_MACRO_REF] (
	[MACRO_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAP_OPTIONS].[OPB_MAP_OPT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MAP_OPT_IDX] ON [dbo].[OPB_MAP_OPTIONS] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAP_PARMVAR].[OPB_MAP_PV_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MAP_PV_IDX] ON [dbo].[OPB_MAP_PARMVAR] (
	[MAPPING_ID] ASC,
	[SUBJECT_ID] ASC,
	[PV_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAP_PERSISVAL].[OPB_MAPPSV_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MAPPSV_IDX] ON [dbo].[OPB_MAP_PERSISVAL] (
	[SESSION_INST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAP_TARG_INFO].[OPB_MAPTARGINF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MAPTARGINF_IDX] ON [dbo].[OPB_MAP_TARG_INFO] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAPPING].[OPB_MAPPING_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MAPPING_IDX] ON [dbo].[OPB_MAPPING] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MAPPING].[OPB_MAPPING_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MAPPING_IDX2] ON [dbo].[OPB_MAPPING] (
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_CUBE].[OPB_CUBE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_CUBE_IDX] ON [dbo].[OPB_MD_CUBE] (
	[CUBE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_CUBE].[OPB_CUBE_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_CUBE_IDX2] ON [dbo].[OPB_MD_CUBE] (
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_CUBE_FIELD].[OPB_CUBEFLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_CUBEFLD_IDX] ON [dbo].[OPB_MD_CUBE_FIELD] (
	[CUBE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_DIMENSION].[OPB_DIMENSION_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_DIMENSION_IDX] ON [dbo].[OPB_MD_DIMENSION] (
	[DIMENSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_DIMENSION].[OPB_DIMN_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_DIMN_IDX2] ON [dbo].[OPB_MD_DIMENSION] (
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_FACT].[OPB_FACT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_FACT_IDX] ON [dbo].[OPB_MD_FACT] (
	[CUBE_ID] ASC,
	[FACT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_FACT_FIELD].[OPB_FACTFLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_FACTFLD_IDX] ON [dbo].[OPB_MD_FACT_FIELD] (
	[CUBE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_FACT_LEVEL].[OPB_FACTLVL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_FACTLVL_IDX] ON [dbo].[OPB_MD_FACT_LEVEL] (
	[CUBE_ID] ASC,
	[DIMENSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_HIERARCHY].[OPB_HIERARCHY_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_HIERARCHY_IDX] ON [dbo].[OPB_MD_HIERARCHY] (
	[DIMENSION_ID] ASC,
	[HIERARCHY_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_LEVEL].[OPB_DIM_LEVEL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_DIM_LEVEL] ON [dbo].[OPB_MD_LEVEL] (
	[DIMENSION_ID] ASC,
	[LEVEL_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_LEVEL_FIELD].[OPB_LEVEL_FLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LEVEL_FLD_IDX] ON [dbo].[OPB_MD_LEVEL_FIELD] (
	[DIMENSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MD_LVL_HRCHY].[OPB_LVLHRCHY_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_LVLHRCHY_IDX] ON [dbo].[OPB_MD_LVL_HRCHY] (
	[DIMENSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_METAEXT_VAL].[OPB_MXTN_VAL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MXTN_VAL_IDX] ON [dbo].[OPB_METAEXT_VAL] (
	[SUBJECT_ID] ASC,
	[VENDOR_ID] ASC,
	[DOMAIN_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_METAEXT_VAL].[OPB_MXTN_VAL_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MXTN_VAL_IDX2] ON [dbo].[OPB_METAEXT_VAL] (
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_CATALOG].[OPB_MMDCTLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDCTLG_IDX] ON [dbo].[OPB_MMD_CATALOG] (
	[VENDOR_ID] ASC,
	[PLG_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_CATTR_VAL].[OPB_MMDCATTV_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDCATTV_IDX] ON [dbo].[OPB_MMD_CATTR_VAL] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[ATTR_ID] ASC,
	[ATTR_INDEX] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_CNX].[OPB_MMDCNX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDCNX_IDX] ON [dbo].[OPB_MMD_CNX] (
	[CNX_OBJECT_TYPE] ASC,
	[CNX_OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_CNX_ATTR].[OPB_MMDCNXAT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDCNXAT_IDX] ON [dbo].[OPB_MMD_CNX_ATTR] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DATATYPE].[OPB_MMDDTYP_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDDTYP_IDX2] ON [dbo].[OPB_MMD_DATATYPE] (
	[DBTYPE_ID] ASC,
	[ORDER_NUM] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DBSUBTYPE].[OPB_MMDDBSUB_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDDBSUB_IDX] ON [dbo].[OPB_MMD_DBSUBTYPE] (
	[DBTYPE_ID] ASC,
	[DBSUBTYPE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DBTY2WATTR].[OPB_MMDDBWATT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDDBWATT_IDX] ON [dbo].[OPB_MMD_DBTY2WATTR] (
	[DBTYPE_ID] ASC,
	[DBSUBTYPE_ID] ASC,
	[OBJECT_TYPE] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DBTY2WAVAL].[OPB_MMDDBWAVL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDDBWAVL_IDX] ON [dbo].[OPB_MMD_DBTY2WAVAL] (
	[DBTYPE_ID] ASC,
	[DBSUBTYPE_ID] ASC,
	[OBJECT_TYPE] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DBTYP2EXTN].[OPB_MMDDBEX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDDBEX_IDX] ON [dbo].[OPB_MMD_DBTYP2EXTN] (
	[DB_TYPE] ASC,
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DBTYPE].[OPB_MMDDBTYP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDDBTYP_IDX] ON [dbo].[OPB_MMD_DBTYPE] (
	[DBTYPE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_DOMAIN].[OPB_MMD_DMN_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMD_DMN_IDX] ON [dbo].[OPB_MMD_DOMAIN] (
	[VENDOR_ID] ASC,
	[DOMAIN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_EATTR_VAL].[OPB_MMDEATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDEATTR_IDX] ON [dbo].[OPB_MMD_EATTR_VAL] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[ATTR_ID] ASC,
	[ATTR_INDEX] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_ECNXN_REF].[OPB_MMDECNXR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDECNXR_IDX] ON [dbo].[OPB_MMD_ECNXN_REF] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[CONNECTION_NUM] ASC,
	[REF_OBJ_TYPE] ASC,
	[REF_OBJ_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_EXTN_ATTR].[OPB_MMDEXAT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDEXAT_IDX] ON [dbo].[OPB_MMD_EXTN_ATTR] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_EXTN_CNXN].[OPB_MMDEXCNX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDEXCNX_IDX] ON [dbo].[OPB_MMD_EXTN_CNXN] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC,
	[CONNECTION_NUM] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_EXTN_WATTR].[OPB_MMDEWATT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDEWATT_IDX] ON [dbo].[OPB_MMD_EXTN_WATTR] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_FLDATTR].[OPB_MMDFLDATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDFLDATTR_IDX] ON [dbo].[OPB_MMD_FLDATTR] (
	[DBTYPE_ID] ASC,
	[DBSUBTYPE_ID] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_FUNC_GRP].[OPB_MMDFUNCGRP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDFUNCGRP_IDX] ON [dbo].[OPB_MMD_FUNC_GRP] (
	[FUNC_GRP_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_FUNCTION].[OPB_MMDFUNC_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDFUNC_IDX] ON [dbo].[OPB_MMD_FUNCTION] (
	[FUNC_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_KEYTYPE].[OPB_MMDKTYP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDKTYP_IDX] ON [dbo].[OPB_MMD_KEYTYPE] (
	[DBTYPE_ID] ASC,
	[KEY_NAME] ASC,
	[SRCTGT_FLAGS] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_LIBS].[OPB_MMDLIB_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDLIB_IDX] ON [dbo].[OPB_MMD_LIBS] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_LIBS].[OPB_MMDLIB_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDLIB_IDX2] ON [dbo].[OPB_MMD_LIBS] (
	[COMPONENT_ID] ASC,
	[COMPONENT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_METAEXT].[OPB_MMD_MXTN_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMD_MXTN_IDX] ON [dbo].[OPB_MMD_METAEXT] (
	[VENDOR_ID] ASC,
	[DOMAIN_ID] ASC,
	[OBJECT_TYPE] ASC,
	[METAEXT_NAME] ASC,
	[DBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_PLGCOMP].[OPB_MMDPLGC_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDPLGC_IDX] ON [dbo].[OPB_MMD_PLGCOMP] (
	[VENDOR_ID] ASC,
	[PLG_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_SESS_EXTNS].[OPB_MMDSESEX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDSESEX_IDX] ON [dbo].[OPB_MMD_SESS_EXTNS] (
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_SLVL_ATTR].[OPB_MMDSLATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDSLATTR_IDX] ON [dbo].[OPB_MMD_SLVL_ATTR] (
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_TEMPLATE].[OPB_MMDTMPL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDTMPL_IDX] ON [dbo].[OPB_MMD_TEMPLATE] (
	[TEMPLATE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_TMPL_ATTR].[OPB_MMDTMPLATT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_MMDTMPLATT_IDX] ON [dbo].[OPB_MMD_TMPL_ATTR] (
	[TEMPLATE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_MMD_TMPL2EXTN].[OPB_MMDTMPLEX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_MMDTMPLEX_IDX] ON [dbo].[OPB_MMD_TMPL2EXTN] (
	[TEMPLATE_ID] ASC,
	[OBJECT_TYPE] ASC,
	[OBJECT_SUBTYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_NORM_FLD].[OPB_NORMFLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_NORMFLD_IDX] ON [dbo].[OPB_NORM_FLD] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_NOTIF_MSG].[OPB_NOTIFMSG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_NOTIFMSG_IDX] ON [dbo].[OPB_NOTIF_MSG] (
	[NOTIFICATION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_OBJECT_ACCESS].[OPB_OBJACCESS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_OBJACCESS_IDX] ON [dbo].[OPB_OBJECT_ACCESS] (
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[PERMISSIONS] ASC,
	[USER_TYPE] ASC,
	[USER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_OBJECT_LOCKS].[OPB_OBJLOCKS1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_OBJLOCKS1] ON [dbo].[OPB_OBJECT_LOCKS] (
	[OBJECT_TYPE_ID] ASC,
	[OBJECT_ID] ASC,
	[SUBJECT_ID] ASC,
	[REPOSIT_ID] ASC,
	[USER_ID] ASC,
	[CNX_ID] ASC,
	[LOCK_OP] ASC,
	[LOCK_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_OBJECT_LOCKS].[OPB_OBJLOCKS2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_OBJLOCKS2] ON [dbo].[OPB_OBJECT_LOCKS] (
	[CNX_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_OBJECT_NOTIF].[OPB_OBJNOTIF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_OBJNOTIF_IDX] ON [dbo].[OPB_OBJECT_NOTIF] (
	[NOTIFICATION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_OBJECT_TYPE].[OPB_OBJTYPE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_OBJTYPE_IDX] ON [dbo].[OPB_OBJECT_TYPE] (
	[OBJECT_TYPE_ID] ASC,
	[OBJECT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PARTITION_DEF].[OPB_PARTDEF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PARTDEF_IDX] ON [dbo].[OPB_PARTITION_DEF] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PCIS_SERVICE_LEASE].[OPB_PCIS_SERVICE_LEASE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_PCIS_SERVICE_LEASE_IDX] ON [dbo].[OPB_PCIS_SERVICE_LEASE] (
	[SERVICE_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PCIS_SESSION_LEASE].[OPB_PCIS_SESSION_LEASE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_PCIS_SESSION_LEASE_IDX] ON [dbo].[OPB_PCIS_SESSION_LEASE] (
	[SERVICE_NAME] ASC,
	[SESS_INST_PATH] ASC,
	[RUN_INST_NAME] ASC,
	[GEN_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PERF_COUNT].[OPB_PF_COUNT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PF_COUNT_IDX] ON [dbo].[OPB_PERF_COUNT] (
	[SUBJECT_ID] ASC,
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC,
	[WORKLET_ID] ASC,
	[TASK_ID] ASC,
	[TASK_INST_ID] ASC,
	[WIDGET_ID] ASC,
	[WIDGET_INST_ID] ASC,
	[PARTITION_ID] ASC,
	[FRAGMENT_ID] ASC,
	[GROUP_ID] ASC,
	[ATTR_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PERF_COUNT].[OPB_PF_COUNT_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PF_COUNT_IDX2] ON [dbo].[OPB_PERF_COUNT] (
	[TIME_STAMP] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PICDSC].[OPB_PICDSC_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_PICDSC_IDX] ON [dbo].[OPB_PICDSC] (
	[PICID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_METADATA].[OPB_PROFMD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROFMD_IDX] ON [dbo].[OPB_PROF_METADATA] (
	[RULESET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_RES_DATA].[OPB_PROFRD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROFRD_IDX] ON [dbo].[OPB_PROF_RES_DATA] (
	[RESOURCE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_RES_REF].[OPB_PROFRR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROFRR_IDX] ON [dbo].[OPB_PROF_RES_REF] (
	[RULESET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_RESOURCE].[OPB_PROF_RES_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_PROF_RES_IDX] ON [dbo].[OPB_PROF_RESOURCE] (
	[RESOURCE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_RULESET].[OPB_PROFRS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_PROFRS_IDX] ON [dbo].[OPB_PROF_RULESET] (
	[RULESET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROF_SRC_REF].[OPB_PROFSR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROFSR_IDX] ON [dbo].[OPB_PROF_SRC_REF] (
	[RULESET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROGRAM_INFO].[OPB_PROG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROG_IDX] ON [dbo].[OPB_PROGRAM_INFO] (
	[SUBJECT_ID] ASC,
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_PROXYUSER_INFO].[OPB_PROXYUSR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_PROXYUSR_IDX] ON [dbo].[OPB_PROXYUSER_INFO] (
	[CNX_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_REPOSIT_INFO].[OPB_REP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_REP_IDX] ON [dbo].[OPB_REPOSIT_INFO] (
	[REPOSITORY_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_REQ_REPLY].[OPB_REQREPLY1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_REQREPLY1] ON [dbo].[OPB_REQ_REPLY] (
	[CNX_ID] ASC,
	[REQUEST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_REQ_REPLY].[OPB_REQREPLY2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_REQREPLY2] ON [dbo].[OPB_REQ_REPLY] (
	[UTC_REQ_TIME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_ROLE].[OPB_ROLE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_ROLE_IDX] ON [dbo].[OPB_ROLE] (
	[ID] ASC,
	[TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_RTSEQ].[OPB_RTSEQ_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_RTSEQ_IDX] ON [dbo].[OPB_RTSEQ] (
	[SEQNAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SAP_FUNC].[OPB_SAP_F_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SAP_F_IDX] ON [dbo].[OPB_SAP_FUNC] (
	[FUNC_ID] ASC,
	[SUBJECT_ID] ASC,
	[VERSION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SAP_FUNC_PARAM].[OPB_SAP_FP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SAP_FP_IDX] ON [dbo].[OPB_SAP_FUNC_PARAM] (
	[FUNC_ID] ASC,
	[SUBJECT_ID] ASC,
	[VERSION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SAP_STRUCT].[OPB_SAP_ST_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SAP_ST_IDX] ON [dbo].[OPB_SAP_STRUCT] (
	[STRUCT_ID] ASC,
	[SUBJECT_ID] ASC,
	[VERSION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SCHEDULER].[OPB_SCHD_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SCHD_IDX2] ON [dbo].[OPB_SCHEDULER] (
	[SUBJECT_ID] ASC,
	[SCHEDULER_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SCHEMA_DEPLOY].[OPB_SCHEMADEP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SCHEMADEP_IDX] ON [dbo].[OPB_SCHEMA_DEPLOY] (
	[SUBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SCHEMA_IDS].[OPB_SCHEMAIDS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SCHEMAIDS_IDX] ON [dbo].[OPB_SCHEMA_IDS] (
	[SUBJECT_ID] ASC,
	[SEQ_TYPE] ASC,
	[OLD_PARENT_ID] ASC,
	[OLD_ID] ASC,
	[RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SEBL_MVL_ATTR].[OPB_SEBL_MVLA_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SEBL_MVLA_IDX] ON [dbo].[OPB_SEBL_MVL_ATTR] (
	[SUBJECT_ID] ASC,
	[SRC_ID] ASC,
	[MVLINK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SEBL_MVL_LREL].[OPB_SEBL_MVL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SEBL_MVL_IDX] ON [dbo].[OPB_SEBL_MVL_LREL] (
	[SUBJECT_ID] ASC,
	[SRC_ID] ASC,
	[FIELD_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SELINFO].[OPB_SELINFO_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SELINFO_IDX] ON [dbo].[OPB_SELINFO] (
	[SELID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVER_INFO].[OPB_SERV_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SERV_IDX] ON [dbo].[OPB_SERVER_INFO] (
	[SERVER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVER_NET].[OPB_SRVNET_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SRVNET_IDX] ON [dbo].[OPB_SERVER_NET] (
	[SERVER_NET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVER_NET_REF].[OPB_SRVNETREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SRVNETREF_IDX] ON [dbo].[OPB_SERVER_NET_REF] (
	[SERVER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVER_NODE].[OPB_SERVNODE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SERVNODE_IDX] ON [dbo].[OPB_SERVER_NODE] (
	[SERVER_ID] ASC,
	[NODE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVICE_LEVEL].[OPB_SERVLEVEL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SERVLEVEL_IDX] ON [dbo].[OPB_SERVICE_LEVEL] (
	[OBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVICED_REQ].[OPB_SERVREQ1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SERVREQ1] ON [dbo].[OPB_SERVICED_REQ] (
	[CNX_ID] ASC,
	[REQUEST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SERVICED_REQ].[OPB_SERVREQ2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SERVREQ2] ON [dbo].[OPB_SERVICED_REQ] (
	[UTC_REQ_TIME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_CNX_REFS].[OPB_SESCXREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCXREF_IDX] ON [dbo].[OPB_SESS_CNX_REFS] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_CNX_REFS].[OPB_SESCXREF_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCXREF_IDX2] ON [dbo].[OPB_SESS_CNX_REFS] (
	[WORKFLOW_ID] ASC,
	[SESSION_INST_ID] ASC,
	[REF_OBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_EXTNS].[OPB_SESEXTN_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESEXTN_IDX] ON [dbo].[OPB_SESS_EXTNS] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_FILE_REF].[OPB_SESFLREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESFLREF_IDX] ON [dbo].[OPB_SESS_FILE_REF] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_PER_FILES].[OPB_SPERFILES_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SPERFILES_IDX] ON [dbo].[OPB_SESS_PER_FILES] (
	[SERVER_ID] ASC,
	[SESSION_INST_ID] ASC,
	[WIDGET_INST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESS_TASK_LOG].[OPB_STASKLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_STASKLG_IDX] ON [dbo].[OPB_SESS_TASK_LOG] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESSION].[OPB_SESSION_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SESSION_IDX] ON [dbo].[OPB_SESSION] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SESSION_CONFIG].[OPB_SESCFG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESCFG_IDX] ON [dbo].[OPB_SESSION_CONFIG] (
	[SUBJECT_ID] ASC,
	[CONFIG_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SHORTCUT].[OPB_SHORTCUT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SHORTCUT_IDX] ON [dbo].[OPB_SHORTCUT] (
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SHORTCUT].[OPB_SHORTCUT_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SHORTCUT_IDX2] ON [dbo].[OPB_SHORTCUT] (
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SHORTCUT].[OPB_SHORTCUT_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SHORTCUT_IDX3] ON [dbo].[OPB_SHORTCUT] (
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SLEVEL_ATTR].[OPB_SLATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SLATTR_IDX] ON [dbo].[OPB_SLEVEL_ATTR] (
	[OBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SRC].[OPB_SRC_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SRC_IDX] ON [dbo].[OPB_SRC] (
	[SRC_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SRC].[OPB_SRC_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SRC_IDX1] ON [dbo].[OPB_SRC] (
	[SUBJ_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SRC_FLD].[OPB_SRC_FLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SRC_FLD_IDX] ON [dbo].[OPB_SRC_FLD] (
	[FLDID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SRC_FLD].[OPB_SRC_FLD_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SRC_FLD_IDX1] ON [dbo].[OPB_SRC_FLD] (
	[SRC_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SRV_LOC_VARS].[OPB_SRVVARS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SRVVARS_IDX] ON [dbo].[OPB_SRV_LOC_VARS] (
	[SERVER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SUBJECT].[OPB_SUBJ_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_SUBJ_IDX] ON [dbo].[OPB_SUBJECT] (
	[SUBJ_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDG_GROUP].[OPB_SWIDGGRP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SWIDGGRP_IDX] ON [dbo].[OPB_SWIDG_GROUP] (
	[SESSION_ID] ASC,
	[SESS_WIDG_INST_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDGET_ATTR].[OPB_SWIDGATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SWIDGATTR_IDX] ON [dbo].[OPB_SWIDGET_ATTR] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDGET_ATTR].[OPB_SWIDGATTR_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SWIDGATTR_IDX1] ON [dbo].[OPB_SWIDGET_ATTR] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC,
	[ATTR_ID] ASC,
	[SESS_WIDG_INST_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDGET_INST].[OPB_SESWINST_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESWINST_IDX] ON [dbo].[OPB_SWIDGET_INST] (
	[SESSION_ID] ASC,
	[SESS_WIDG_INST_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDGET_INST].[OPB_SESWINST_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SESWINST_IDX1] ON [dbo].[OPB_SWIDGET_INST] (
	[WIDGET_TYPE] ASC,
	[SESSION_ID] ASC,
	[SESS_WIDG_INST_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_SWIDGINST_LOG].[OPB_SWINSTLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_SWINSTLG_IDX] ON [dbo].[OPB_SWIDGINST_LOG] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TABLE_GROUP].[OPB_TABLE_GRP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TABLE_GRP_IDX] ON [dbo].[OPB_TABLE_GROUP] (
	[OBJECT_TYPE] ASC,
	[OBJECT_ID] ASC,
	[GROUP_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG].[OPB_TARG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TARG_IDX] ON [dbo].[OPB_TARG] (
	[TARGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG].[OPB_TARG_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARG_IDX1] ON [dbo].[OPB_TARG] (
	[SUBJ_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG_FLD].[OPB_TARG_FLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TARG_FLD_IDX] ON [dbo].[OPB_TARG_FLD] (
	[FLDID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG_FLD].[OPB_TARG_FLD_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARG_FLD_IDX1] ON [dbo].[OPB_TARG_FLD] (
	[TARGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG_FLD].[OPB_TARG_FLD_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARG_FLD_IDX2] ON [dbo].[OPB_TARG_FLD] (
	[DFLDID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG_FLD_EXPR].[OPB_TARGFLDXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARGFLDXPR_IDX] ON [dbo].[OPB_TARG_FLD_EXPR] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARG_TBL_EXPR].[OPB_TARGTBLXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARGTBLXPR_IDX] ON [dbo].[OPB_TARG_TBL_EXPR] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARGINDEX].[OPB_TARGINDEX_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TARGINDEX_IDX] ON [dbo].[OPB_TARGINDEX] (
	[INDEXID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARGINDEX].[OPB_TARGINDEX_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TARGINDEX_IDX2] ON [dbo].[OPB_TARGINDEX] (
	[TARGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARGINDEXFLD].[OPB_TINDEXFLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TINDEXFLD_IDX] ON [dbo].[OPB_TARGINDEXFLD] (
	[FLDID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TARGINDEXFLD].[OPB_TINDEXFLD_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TINDEXFLD_IDX2] ON [dbo].[OPB_TARGINDEXFLD] (
	[INDEXID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK].[OPB_TASK_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TASK_IDX] ON [dbo].[OPB_TASK] (
	[SUBJECT_ID] ASC,
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK].[OPB_TASK_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_IDX2] ON [dbo].[OPB_TASK] (
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK].[OPB_TASK_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_IDX3] ON [dbo].[OPB_TASK] (
	[TASK_ID] ASC,
	[TASK_TYPE] ASC,
	[VERSION_NUMBER] ASC,
	[IS_VISIBLE] ASC,
	[SUBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_ATTR].[OPB_TASK_ATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_ATTR_IDX] ON [dbo].[OPB_TASK_ATTR] (
	[WORKFLOW_ID] ASC,
	[TASK_ID] ASC,
	[TASK_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_ATTR].[OPB_TASK_ATTR_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_ATTR_IDX3] ON [dbo].[OPB_TASK_ATTR] (
	[TASK_TYPE] ASC,
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_ATTR].[OPB_TASK_ATTR_IDX4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_ATTR_IDX4] ON [dbo].[OPB_TASK_ATTR] (
	[WORKFLOW_ID] ASC,
	[TASK_ID] ASC,
	[TASK_TYPE] ASC,
	[ATTR_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_ATTR].[OPB_TASK_ATTR_IDX5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_ATTR_IDX5] ON [dbo].[OPB_TASK_ATTR] (
	[INSTANCE_ID] ASC,
	[REF_SESSION_ID] ASC,
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC,
	[TASK_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_ATTR].[OPB_TASKATTR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASKATTR_IDX2] ON [dbo].[OPB_TASK_ATTR] (
	[REF_SESSION_ID] ASC,
	[COMPONENT_TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST].[OPB_TASK_INST_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_TASK_INST_IDX] ON [dbo].[OPB_TASK_INST] (
	[WORKFLOW_ID] ASC,
	[INSTANCE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST].[OPB_TASK_INST_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_INST_IDX2] ON [dbo].[OPB_TASK_INST] (
	[TASK_TYPE] ASC,
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST].[OPB_TASK_INST_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_INST_IDX3] ON [dbo].[OPB_TASK_INST] (
	[TASK_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST_BRK].[OPB_TINSBRK_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TINSBRK_IDX] ON [dbo].[OPB_TASK_INST_BRK] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST_RUN].[OPB_TINSTLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TINSTLG_IDX] ON [dbo].[OPB_TASK_INST_RUN] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_INST_RUN].[OPB_TINSTLG_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TINSTLG_IDX2] ON [dbo].[OPB_TASK_INST_RUN] (
	[WORKFLOW_RUN_ID] ASC,
	[WORKLET_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_MCR_DEP].[OPB_TASK_MCR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_MCR_IDX] ON [dbo].[OPB_TASK_MCR_DEP] (
	[TASK_ID] ASC,
	[WORKFLOW_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_MCR_DEP].[OPB_TASK_MCR_IDX1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_MCR_IDX1] ON [dbo].[OPB_TASK_MCR_DEP] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_MCR_DEP].[OPB_TASK_MCR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASK_MCR_IDX2] ON [dbo].[OPB_TASK_MCR_DEP] (
	[SUBJECT_ID] ASC,
	[MACRO_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_RES_REFS].[OPB_RESREF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_RESREF_IDX] ON [dbo].[OPB_TASK_RES_REFS] (
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_RES_REFS].[OPB_RESREF_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_RESREF_IDX2] ON [dbo].[OPB_TASK_RES_REFS] (
	[WORKFLOW_ID] ASC,
	[TASK_INST_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_STATS].[OPB_TASKSTATS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TASKSTATS_IDX] ON [dbo].[OPB_TASK_STATS] (
	[WORKFLOW_ID] ASC,
	[WORKLET_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TASK_VAL_LIST].[OPB_TSKVALST_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TSKVALST_IDX] ON [dbo].[OPB_TASK_VAL_LIST] (
	[TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_TDS].[OPB_TDS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_TDS_IDX] ON [dbo].[OPB_TDS] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_USER_GROUP].[OPB_USR_GRP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_USR_GRP_IDX] ON [dbo].[OPB_USER_GROUP] (
	[NAME_SPACE] ASC,
	[NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_USER_GROUP].[OPB_USR_GRP_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_USR_GRP_IDX2] ON [dbo].[OPB_USER_GROUP] (
	[ID] ASC,
	[TYPE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_USERS].[OPB_USER_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_USER_IDX] ON [dbo].[OPB_USERS] (
	[USER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_VALIDATE].[OPB_VALIDATE_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_VALIDATE_IDX] ON [dbo].[OPB_VALIDATE] (
	[SUBJECT_ID] ASC,
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_VERSION_PROPS].[OPB_VER_PROPS_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_VER_PROPS_IDX] ON [dbo].[OPB_VERSION_PROPS] (
	[OBJECT_ID] ASC,
	[OBJECT_TYPE] ASC,
	[VERSION_NUMBER] ASC,
	[SUBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WF_RUNINFO].[OPB_WF_RUNINFO_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WF_RUNINFO_IDX] ON [dbo].[OPB_WF_RUNINFO] (
	[SUBJECT_ID] ASC,
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLD_ATTR].[OPB_WFATT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFATT_IDX] ON [dbo].[OPB_WFLD_ATTR] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLD_ATTR_DEF].[OPB_WFATTDEF_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFATTDEF_IDX] ON [dbo].[OPB_WFLD_ATTR_DEF] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLD_INOUTDEP].[OPB_WFOUTDEP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFOUTDEP_IDX] ON [dbo].[OPB_WFLD_INOUTDEP] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_CACHE].[OPB_WFCACHELG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFCACHELG_IDX] ON [dbo].[OPB_WFLOW_CACHE] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_DEP].[OPB_WFDEP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFDEP_IDX] ON [dbo].[OPB_WFLOW_DEP] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_DEP_RUN].[OPB_WFDEPLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFDEPLG_IDX] ON [dbo].[OPB_WFLOW_DEP_RUN] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_DEP_RUN].[OPB_WFDEPLG_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFDEPLG_IDX2] ON [dbo].[OPB_WFLOW_DEP_RUN] (
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_EXPR].[OPB_WFEXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFEXPR_IDX] ON [dbo].[OPB_WFLOW_EXPR] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_RUN].[OPB_WFLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFLG_IDX] ON [dbo].[OPB_WFLOW_RUN] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_RUN].[OPB_WFLG_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFLG_IDX2] ON [dbo].[OPB_WFLOW_RUN] (
	[WORKFLOW_RUN_ID] ASC,
	[VERSION_NUMBER] ASC,
	[SUBJECT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_RUN].[OPB_WFLG_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFLG_IDX3] ON [dbo].[OPB_WFLOW_RUN] (
	[SERVER_ID] ASC,
	[SUBJECT_ID] ASC,
	[START_TIME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_RUN_BRK].[OPB_WFBRK_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFBRK_IDX] ON [dbo].[OPB_WFLOW_RUN_BRK] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_VAR].[OPB_WFVAR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFVAR_IDX] ON [dbo].[OPB_WFLOW_VAR] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WFLOW_VAR_RUN].[OPB_WFVARLG_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WFVARLG_IDX] ON [dbo].[OPB_WFLOW_VAR_RUN] (
	[WORKFLOW_ID] ASC,
	[WORKFLOW_RUN_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDG_FLD_ATTR].[OPB_WIDFLDATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_WIDFLDATTR_IDX] ON [dbo].[OPB_WIDG_FLD_ATTR] (
	[OBJECT_TYPE] ASC,
	[OBJECT_ID] ASC,
	[FIELD_ID] ASC,
	[ATTR_ID] ASC,
	[LINE_NO] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDG_MCR_DEP].[OPB_WIDG_MCR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_MCR_IDX] ON [dbo].[OPB_WIDG_MCR_DEP] (
	[WIDGET_ID] ASC,
	[WIDGET_TYPE] ASC,
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDG_MCR_DEP].[OPB_WIDG_MCR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_MCR_IDX2] ON [dbo].[OPB_WIDG_MCR_DEP] (
	[MAPPING_ID] ASC,
	[INSTANCE_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDG_MCR_DEP].[OPB_WIDG_MCR_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_MCR_IDX3] ON [dbo].[OPB_WIDG_MCR_DEP] (
	[SESSION_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDG_MCR_DEP].[OPB_WIDG_MCR_IDX4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_MCR_IDX4] ON [dbo].[OPB_WIDG_MCR_DEP] (
	[SUBJECT_ID] ASC,
	[MACRO_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET].[OPB_WIDGET_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_WIDGET_IDX] ON [dbo].[OPB_WIDGET] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET].[OPB_WIDGET_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGET_IDX2] ON [dbo].[OPB_WIDGET] (
	[SUBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET].[OPB_WIDGET_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGET_IDX3] ON [dbo].[OPB_WIDGET] (
	[SUBJECT_ID] ASC,
	[WIDGET_ID] ASC,
	[WIDGET_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_ATTR].[OPB_WIDG_ATTR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_ATTR_IDX] ON [dbo].[OPB_WIDGET_ATTR] (
	[WIDGET_ID] ASC,
	[WIDGET_TYPE] ASC,
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_ATTR].[OPB_WIDG_ATTR_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_ATTR_IDX2] ON [dbo].[OPB_WIDGET_ATTR] (
	[MAPPING_ID] ASC,
	[INSTANCE_ID] ASC,
	[SESSION_TASK_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_ATTR].[OPB_WIDG_ATTR_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_ATTR_IDX3] ON [dbo].[OPB_WIDGET_ATTR] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_ATTR].[OPB_WIDG_ATTR_IDX4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_ATTR_IDX4] ON [dbo].[OPB_WIDGET_ATTR] (
	[WIDGET_TYPE] ASC,
	[ATTR_ID] ASC,
	[SESSION_TASK_ID] ASC,
	[MAPPING_ID] ASC,
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_DEP].[OPB_WIDGET_DEP_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGET_DEP_IDX] ON [dbo].[OPB_WIDGET_DEP] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_EXPR].[OPB_WIDGEXPR_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGEXPR_IDX] ON [dbo].[OPB_WIDGET_EXPR] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_FIELD].[OPB_WIDGFLD_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGFLD_IDX] ON [dbo].[OPB_WIDGET_FIELD] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_INIT].[OPB_WIDGINIT_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGINIT_IDX] ON [dbo].[OPB_WIDGET_INIT] (
	[WIDGET_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_INIT].[OPB_WIDGINIT_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDGINIT_IDX2] ON [dbo].[OPB_WIDGET_INIT] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_INST].[OPB_WIDG_INST_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_INST_IDX] ON [dbo].[OPB_WIDGET_INST] (
	[MAPPING_ID] ASC,
	[WIDGET_ID] ASC,
	[WIDGET_TYPE] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_INST].[OPB_WIDG_INST_IDX2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_INST_IDX2] ON [dbo].[OPB_WIDGET_INST] (
	[MAPPING_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WIDGET_INST].[OPB_WIDG_INST_IDX3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_WIDG_INST_IDX3] ON [dbo].[OPB_WIDGET_INST] (
	[WIDGET_ID] ASC,
	[WIDGET_TYPE] ASC,
	[REF_VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_WORKFLOW].[OPB_WFLOW_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPB_WFLOW_IDX] ON [dbo].[OPB_WORKFLOW] (
	[WORKFLOW_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_XML_INFO].[OPB_XML_INFO_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_XML_INFO_IDX] ON [dbo].[OPB_XML_INFO] (
	[OBJECT_TYPE] ASC,
	[OBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[OPB_XML_QUAL].[OPB_XML_QUAL_IDX].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [OPB_XML_QUAL_IDX] ON [dbo].[OPB_XML_QUAL] (
	[OBJECT_TYPE] ASC,
	[OBJECT_ID] ASC,
	[VERSION_NUMBER] ASC
) ON [PRIMARY]
