SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MRI_FOLDER]') IS NULL EXEC('CREATE VIEW [dbo].[MRI_FOLDER] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[MRI_FOLDER]
( PID, NSID, EID, CID, DISCRIMINATOR, NAME ) as select a1.PSF_OPID, a1.PSF_NSID, a1.PSF_EXTERNID, a1.PSF_CONTAINER, a1.PSF_DISCRIMINATOR, a1.POF_NAME from "dbo".PO_FOLDER a1  where a1.PSF_PRSID = 0 AND (a1.PSF_DISCRIMINATOR = 'com.informatica.metadata.common.folder.impl.FolderImpl' OR a1.PSF_DISCRIMINATOR = 'MPROOTFOLDERMARKER')
GO
