SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MRI_CR_REPOSITORY]') IS NULL EXEC('CREATE VIEW [dbo].[MRI_CR_REPOSITORY] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[MRI_CR_REPOSITORY]
( FROM_PID, FROM_NSID, FROM_EID, TO_PID, TO_TYPE, PROP_NAME ) as (select -1, -1, a1.PCN_REPOSIG, a1.PCN_NSID, '', 'com.informatica.repository.persistence.databasemodel.DatabaseRepository.namespaces' from "dbo".PC_NAMESPACE a1 )
GO
