SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MRI_CR_PROJECT_GROUP]') IS NULL EXEC('CREATE VIEW [dbo].[MRI_CR_PROJECT_GROUP] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[MRI_CR_PROJECT_GROUP]
( FROM_PID, FROM_NSID, FROM_EID, TO_PID, TO_TYPE, PROP_NAME ) as (select a2.PSM_OPID, a2.PSM_NSID, a2.PSM_EXTERNID, a4.PRR_OID, '', 'com.informatica.project.repository.models.prsconcepts.persistent.MPProjectGroup.projects' from "dbo".PO_MPPROJECTGROUP a2  left join "dbo".PR_RESOURCE a3 on a2.PSM_CONTAINER = a3.PRR_ID left join "dbo".PR_RESOURCE a4 on a3.PRR_ID = a4.PRR_PARENTCONTAINER join "dbo".PR_ATTRIBUTE a5 on (a4.PRR_ID = a5.PRA_RESOURCE and a5.PRD_ATTR_NAME = 'REPO.SYSTEM.PRS_AGGREGATOR_PROP_NAME_ATTR' and a5.PRD_ATTR_VALUE = 'projects')  where a2.PSM_PRSID = 0 )
GO
