
GO
--SqlScripter----[dbo].[PC_AUDITLOG].[PK_PC_AUDITLOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_AUDITLOG] ADD CONSTRAINT [PK_PC_AUDITLOG] PRIMARY KEY CLUSTERED (
	[PCA_AUDITLOGID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_DBRCONFIG].[PK_PC_DBRCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_DBRCONFIG] ADD CONSTRAINT [PK_PC_DBRCONFIG] PRIMARY KEY CLUSTERED (
	[PCD_DBRCONFIGID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_ICLASS_SIG].[PK_PC_ICLASS_SIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_ICLASS_SIG] ADD CONSTRAINT [PK_PC_ICLASS_SIG] PRIMARY KEY CLUSTERED (
	[PCI_QNAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_NAMESPACE].[PK_PC_NAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_NAMESPACE] ADD CONSTRAINT [PK_PC_NAMESPACE] PRIMARY KEY CLUSTERED (
	[PCN_NSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_NAMESPACE_SEQUENCE].[PK_PC_NAMESPACE_SEQUENCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_NAMESPACE_SEQUENCE] ADD CONSTRAINT [PK_PC_NAMESPACE_SEQUENCE] PRIMARY KEY CLUSTERED (
	[PCS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_ORMSTATE].[PK_PC_ORMSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_ORMSTATE] ADD CONSTRAINT [PK_PC_ORMSTATE] PRIMARY KEY CLUSTERED (
	[PCO_ORMSTATEID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_PACKAGE].[PK_PC_PACKAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_PACKAGE] ADD CONSTRAINT [PK_PC_PACKAGE] PRIMARY KEY CLUSTERED (
	[PCP_PKGID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_PREPROCESS_KV_ENTRY].[PK_PC_PREPROCESS_KV_ENTRY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_PREPROCESS_KV_ENTRY] ADD CONSTRAINT [PK_PC_PREPROCESS_KV_ENTRY] PRIMARY KEY CLUSTERED (
	[PCP_EID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_REPOSITORY].[PK_PC_REPOSITORY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_REPOSITORY] ADD CONSTRAINT [PK_PC_REPOSITORY] PRIMARY KEY CLUSTERED (
	[PCR_SIGNATURE] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PC_UPGRADE_LOG].[PK_PC_UPGRADE_LOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PC_UPGRADE_LOG] ADD CONSTRAINT [PK_PC_UPGRADE_LOG] PRIMARY KEY CLUSTERED (
	[PCU_ORDERNO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ALERT].[PK_PO_ALERT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ALERT] ADD CONSTRAINT [PK_PO_ALERT] PRIMARY KEY CLUSTERED (
	[PSA_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ANNOTATION].[PK_PO_ANNOTATION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ANNOTATION] ADD CONSTRAINT [PK_PO_ANNOTATION] PRIMARY KEY CLUSTERED (
	[PSA_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ATTRIBUTES].[PK_PO_ATTRIBUTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ATTRIBUTES] ADD CONSTRAINT [PK_PO_ATTRIBUTES] PRIMARY KEY CLUSTERED (
	[PSA_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CALUSAGE].[PK_PO_CALUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CALUSAGE] ADD CONSTRAINT [PK_PO_CALUSAGE] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDORG].[PK_PO_CLOUDORG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLOUDORG] ADD CONSTRAINT [PK_PO_CLOUDORG] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLOUDSERVICECONFIGURAT].[PK_PO_CLOUDSERVICECONFIGU].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLOUDSERVICECONFIGURAT] ADD CONSTRAINT [PK_PO_CLOUDSERVICECONFIGU] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CLUSTERCONF].[PK_PO_CLUSTERCONF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CLUSTERCONF] ADD CONSTRAINT [PK_PO_CLUSTERCONF] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGE].[PK_PO_CODEPAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CODEPAGE] ADD CONSTRAINT [PK_PO_CODEPAGE] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CODEPAGESYSTEM].[PK_PO_CODEPAGESYSTEM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CODEPAGESYSTEM] ADD CONSTRAINT [PK_PO_CODEPAGESYSTEM] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_0].[PK_PO_COLLECTIONENTRY_0].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_0] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_0] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_1].[PK_PO_COLLECTIONENTRY_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_1] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_1] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_2].[PK_PO_COLLECTIONENTRY_2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_2] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_2] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_3].[PK_PO_COLLECTIONENTRY_3].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_3] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_3] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_4].[PK_PO_COLLECTIONENTRY_4].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_4] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_4] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_5].[PK_PO_COLLECTIONENTRY_5].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_5] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_5] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_6].[PK_PO_COLLECTIONENTRY_6].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_6] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_6] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_7].[PK_PO_COLLECTIONENTRY_7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_7] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_7] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_8].[PK_PO_COLLECTIONENTRY_8].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_8] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_8] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COLLECTIONENTRY_9].[PK_PO_COLLECTIONENTRY_9].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COLLECTIONENTRY_9] ADD CONSTRAINT [PK_PO_COLLECTIONENTRY_9] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMMAND].[PK_PO_COMMAND].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COMMAND] ADD CONSTRAINT [PK_PO_COMMAND] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_COMPUTENODECONFIGURATI].[PK_PO_COMPUTENODECONFIGUR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_COMPUTENODECONFIGURATI] ADD CONSTRAINT [PK_PO_COMPUTENODECONFIGUR] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFFETCHERPARAMETER].[PK_PO_CONFFETCHERPARAMETE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFFETCHERPARAMETER] ADD CONSTRAINT [PK_PO_CONFFETCHERPARAMETE] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFNAMESPACE].[PK_PO_CONFNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFNAMESPACE] ADD CONSTRAINT [PK_PO_CONFNAMESPACE] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONFPROPERTY].[PK_PO_CONFPROPERTY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONFPROPERTY] ADD CONSTRAINT [PK_PO_CONFPROPERTY] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTINFO].[PK_PO_CONNECTINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONNECTINFO] ADD CONSTRAINT [PK_PO_CONNECTINFO] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTINFOCLASSIFIERC].[PK_PO_CONNECTINFOCLASSIFI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONNECTINFOCLASSIFIERC] ADD CONSTRAINT [PK_PO_CONNECTINFOCLASSIFI] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONNECTIONPOOLATTRIBUT].[PK_PO_CONNECTIONPOOLATTRI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONNECTIONPOOLATTRIBUT] ADD CONSTRAINT [PK_PO_CONNECTIONPOOLATTRI] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_CONTEXT].[PK_PO_CONTEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_CONTEXT] ADD CONSTRAINT [PK_PO_CONTEXT] PRIMARY KEY CLUSTERED (
	[PSC_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DATAMAPTYPE].[PK_PO_DATAMAPTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DATAMAPTYPE] ADD CONSTRAINT [PK_PO_DATAMAPTYPE] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DBCONNECTIVITY].[PK_PO_DBCONNECTIVITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DBCONNECTIVITY] ADD CONSTRAINT [PK_PO_DBCONNECTIVITY] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DEFAULTOSPROFILE].[PK_PO_DEFAULTOSPROFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DEFAULTOSPROFILE] ADD CONSTRAINT [PK_PO_DEFAULTOSPROFILE] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJ].[PK_PO_DOMAINOBJ].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINOBJ] ADD CONSTRAINT [PK_PO_DOMAINOBJ] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINOBJECTLOCATE].[PK_PO_DOMAINOBJECTLOCATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINOBJECTLOCATE] ADD CONSTRAINT [PK_PO_DOMAINOBJECTLOCATE] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINSERVICECONFIG].[PK_PO_DOMAINSERVICECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINSERVICECONFIG] ADD CONSTRAINT [PK_PO_DOMAINSERVICECONFIG] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_DOMAINUSAGE].[PK_PO_DOMAINUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_DOMAINUSAGE] ADD CONSTRAINT [PK_PO_DOMAINUSAGE] PRIMARY KEY CLUSTERED (
	[PSD_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERINFAHOMECONFIG].[PK_PO_EARLIERINFAHOMECONF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EARLIERINFAHOMECONFIG] ADD CONSTRAINT [PK_PO_EARLIERINFAHOMECONF] PRIMARY KEY CLUSTERED (
	[PSE_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EARLIERVERSIONDOMAINOB].[PK_PO_EARLIERVERSIONDOMAI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EARLIERVERSIONDOMAINOB] ADD CONSTRAINT [PK_PO_EARLIERVERSIONDOMAI] PRIMARY KEY CLUSTERED (
	[PSE_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ENDPOINT].[PK_PO_ENDPOINT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ENDPOINT] ADD CONSTRAINT [PK_PO_ENDPOINT] PRIMARY KEY CLUSTERED (
	[PSE_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONATTRIBUTE].[PK_PO_EXTENSIONATTRIBUTE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EXTENSIONATTRIBUTE] ADD CONSTRAINT [PK_PO_EXTENSIONATTRIBUTE] PRIMARY KEY CLUSTERED (
	[PSE_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_EXTENSIONCONTAINER].[PK_PO_EXTENSIONCONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_EXTENSIONCONTAINER] ADD CONSTRAINT [PK_PO_EXTENSIONCONTAINER] PRIMARY KEY CLUSTERED (
	[PSE_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FEATURE].[PK_PO_FEATURE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FEATURE] ADD CONSTRAINT [PK_PO_FEATURE] PRIMARY KEY CLUSTERED (
	[PSF_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FILEINF1].[PK_PO_FILEINF1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FILEINF1] ADD CONSTRAINT [PK_PO_FILEINF1] PRIMARY KEY CLUSTERED (
	[PSF_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FILEINFO].[PK_PO_FILEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FILEINFO] ADD CONSTRAINT [PK_PO_FILEINFO] PRIMARY KEY CLUSTERED (
	[PSF_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FOLDER].[PK_PO_FOLDER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FOLDER] ADD CONSTRAINT [PK_PO_FOLDER] PRIMARY KEY CLUSTERED (
	[PSF_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_FTPCONNECTIONATTRIBUTE].[PK_PO_FTPCONNECTIONATTRIB].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_FTPCONNECTIONATTRIBUTE] ADD CONSTRAINT [PK_PO_FTPCONNECTIONATTRIB] PRIMARY KEY CLUSTERED (
	[PSF_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_GLOSSARY].[PK_PO_GLOSSARY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_GLOSSARY] ADD CONSTRAINT [PK_PO_GLOSSARY] PRIMARY KEY CLUSTERED (
	[PSG_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPDISTRIBUTION].[PK_PO_HADOOPDISTRIBUTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HADOOPDISTRIBUTION] ADD CONSTRAINT [PK_PO_HADOOPDISTRIBUTION] PRIMARY KEY CLUSTERED (
	[PSH_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HADOOPIMPERSONATIONPRO].[PK_PO_HADOOPIMPERSONATION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HADOOPIMPERSONATIONPRO] ADD CONSTRAINT [PK_PO_HADOOPIMPERSONATION] PRIMARY KEY CLUSTERED (
	[PSH_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HOSTUSAGE].[PK_PO_HOSTUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HOSTUSAGE] ADD CONSTRAINT [PK_PO_HOSTUSAGE] PRIMARY KEY CLUSTERED (
	[PSH_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPFILEINFO].[PK_PO_HTTPFILEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HTTPFILEINFO] ADD CONSTRAINT [PK_PO_HTTPFILEINFO] PRIMARY KEY CLUSTERED (
	[PSH_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_HTTPSINFO].[PK_PO_HTTPSINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_HTTPSINFO] ADD CONSTRAINT [PK_PO_HTTPSINFO] PRIMARY KEY CLUSTERED (
	[PSH_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IDOBJ].[PK_PO_IDOBJ].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_IDOBJ] ADD CONSTRAINT [PK_PO_IDOBJ] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IDTOQUALNAMES].[PK_PO_IDTOQUALNAMES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_IDTOQUALNAMES] ADD CONSTRAINT [PK_PO_IDTOQUALNAMES] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_IMFPACKAGEUPGRADEINFO].[PK_PO_IMFPACKAGEUPGRADEIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_IMFPACKAGEUPGRADEINFO] ADD CONSTRAINT [PK_PO_IMFPACKAGEUPGRADEIN] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPBOOLEAN].[PK_PO_ISPBOOLEAN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPBOOLEAN] ADD CONSTRAINT [PK_PO_ISPBOOLEAN] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPINTEGER].[PK_PO_ISPINTEGER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPINTEGER] ADD CONSTRAINT [PK_PO_ISPINTEGER] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPLONG].[PK_PO_ISPLONG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPLONG] ADD CONSTRAINT [PK_PO_ISPLONG] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ISPSTRING].[PK_PO_ISPSTRING].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ISPSTRING] ADD CONSTRAINT [PK_PO_ISPSTRING] PRIMARY KEY CLUSTERED (
	[PSI_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPNAMESPACE].[PK_PO_LDAPNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LDAPNAMESPACE] ADD CONSTRAINT [PK_PO_LDAPNAMESPACE] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LDAPOPTIONS].[PK_PO_LDAPOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LDAPOPTIONS] ADD CONSTRAINT [PK_PO_LDAPOPTIONS] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEDSERVICE].[PK_PO_LICENSEDSERVICE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEDSERVICE] ADD CONSTRAINT [PK_PO_LICENSEDSERVICE] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEFEATURES].[PK_PO_LICENSEFEATURES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEFEATURES] ADD CONSTRAINT [PK_PO_LICENSEFEATURES] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEHOSTSERVICES].[PK_PO_LICENSEHOSTSERVICES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEHOSTSERVICES] ADD CONSTRAINT [PK_PO_LICENSEHOSTSERVICES] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEOPTION].[PK_PO_LICENSEOPTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEOPTION] ADD CONSTRAINT [PK_PO_LICENSEOPTION] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LICENSEUSAGE].[PK_PO_LICENSEUSAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LICENSEUSAGE] ADD CONSTRAINT [PK_PO_LICENSEUSAGE] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINK].[PK_PO_LINK].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINK] ADD CONSTRAINT [PK_PO_LINK] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKATTRIBUTES].[PK_PO_LINKATTRIBUTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINKATTRIBUTES] ADD CONSTRAINT [PK_PO_LINKATTRIBUTES] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LINKEDDOMAINSTORAGE].[PK_PO_LINKEDDOMAINSTORAGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LINKEDDOMAINSTORAGE] ADD CONSTRAINT [PK_PO_LINKEDDOMAINSTORAGE] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGCALLCONTEXT].[PK_PO_LOGCALLCONTEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGCALLCONTEXT] ADD CONSTRAINT [PK_PO_LOGCALLCONTEXT] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGEVENT].[PK_PO_LOGEVENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGEVENT] ADD CONSTRAINT [PK_PO_LOGEVENT] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICECONFIGURATIO].[PK_PO_LOGSERVICECONFIGURA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICECONFIGURATIO] ADD CONSTRAINT [PK_PO_LOGSERVICECONFIGURA] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEOPTIONS].[PK_PO_LOGSERVICEOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICEOPTIONS] ADD CONSTRAINT [PK_PO_LOGSERVICEOPTIONS] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_LOGSERVICEPROCESS].[PK_PO_LOGSERVICEPROCESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_LOGSERVICEPROCESS] ADD CONSTRAINT [PK_PO_LOGSERVICEPROCESS] PRIMARY KEY CLUSTERED (
	[PSL_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRY].[PK_PO_MACCESSCONTROLENTRY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLENTRY] ADD CONSTRAINT [PK_PO_MACCESSCONTROLENTRY] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLENTRYANN].[PK_PO_MACCESSCONTROLENTR1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLENTRYANN] ADD CONSTRAINT [PK_PO_MACCESSCONTROLENTR1] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MACCESSCONTROLLIST].[PK_PO_MACCESSCONTROLLIST].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MACCESSCONTROLLIST] ADD CONSTRAINT [PK_PO_MACCESSCONTROLLIST] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MONITORINGSERVICECONFI].[PK_PO_MONITORINGSERVICECO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MONITORINGSERVICECONFI] ADD CONSTRAINT [PK_PO_MONITORINGSERVICECO] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROCESSEDDATAUPGRADE].[PK_PO_MPPROCESSEDDATAUPGR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROCESSEDDATAUPGRADE] ADD CONSTRAINT [PK_PO_MPPROCESSEDDATAUPGR] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECT].[PK_PO_MPPROJECT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROJECT] ADD CONSTRAINT [PK_PO_MPPROJECT] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPPROJECTGROUP].[PK_PO_MPPROJECTGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPPROJECTGROUP] ADD CONSTRAINT [PK_PO_MPPROJECTGROUP] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_MPSERVICEINFO].[PK_PO_MPSERVICEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_MPSERVICEINFO] ADD CONSTRAINT [PK_PO_MPSERVICEINFO] PRIMARY KEY CLUSTERED (
	[PSM_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NAMEVALUEPAIR].[PK_PO_NAMEVALUEPAIR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NAMEVALUEPAIR] ADD CONSTRAINT [PK_PO_NAMEVALUEPAIR] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEADDRESS].[PK_PO_NODEADDRESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODEADDRESS] ADD CONSTRAINT [PK_PO_NODEADDRESS] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECAPABILITY].[PK_PO_NODECAPABILITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODECAPABILITY] ADD CONSTRAINT [PK_PO_NODECAPABILITY] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODECONFIG].[PK_PO_NODECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODECONFIG] ADD CONSTRAINT [PK_PO_NODECONFIG] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODEREF].[PK_PO_NODEREF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODEREF] ADD CONSTRAINT [PK_PO_NODEREF] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODERESOURCE].[PK_PO_NODERESOURCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODERESOURCE] ADD CONSTRAINT [PK_PO_NODERESOURCE] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESAMLCONFIG].[PK_PO_NODESAMLCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODESAMLCONFIG] ADD CONSTRAINT [PK_PO_NODESAMLCONFIG] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_NODESERVICES].[PK_PO_NODESERVICES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_NODESERVICES] ADD CONSTRAINT [PK_PO_NODESERVICES] PRIMARY KEY CLUSTERED (
	[PSN_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTGRAPHDECORATION].[PK_PO_OBJECTGRAPHDECORATI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OBJECTGRAPHDECORATION] ADD CONSTRAINT [PK_PO_OBJECTGRAPHDECORATI] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OBJECTREFERENCE].[PK_PO_OBJECTREFERENCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OBJECTREFERENCE] ADD CONSTRAINT [PK_PO_OBJECTREFERENCE] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTION].[PK_PO_OPTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OPTION] ADD CONSTRAINT [PK_PO_OPTION] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OPTIONGROUP].[PK_PO_OPTIONGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OPTIONGROUP] ADD CONSTRAINT [PK_PO_OPTIONGROUP] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILE].[PK_PO_OSPROFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OSPROFILE] ADD CONSTRAINT [PK_PO_OSPROFILE] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_OSPROFILEPRODUCTEXTENS].[PK_PO_OSPROFILEPRODUCTEXT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_OSPROFILEPRODUCTEXTENS] ADD CONSTRAINT [PK_PO_OSPROFILEPRODUCTEXT] PRIMARY KEY CLUSTERED (
	[PSO_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETER].[PK_PO_PARAMETER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETER] ADD CONSTRAINT [PK_PO_PARAMETER] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERCONTAINER].[PK_PO_PARAMETERCONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERCONTAINER] ADD CONSTRAINT [PK_PO_PARAMETERCONTAINER] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERREFERENCE].[PK_PO_PARAMETERREFERENCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERREFERENCE] ADD CONSTRAINT [PK_PO_PARAMETERREFERENCE] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERTYPE].[PK_PO_PARAMETERTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERTYPE] ADD CONSTRAINT [PK_PO_PARAMETERTYPE] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PARAMETERVALUE].[PK_PO_PARAMETERVALUE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PARAMETERVALUE] ADD CONSTRAINT [PK_PO_PARAMETERVALUE] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PCAPABILITYINFO].[PK_PO_PCAPABILITYINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PCAPABILITYINFO] ADD CONSTRAINT [PK_PO_PCAPABILITYINFO] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PIMFPACKAGEINFO].[PK_PO_PIMFPACKAGEINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PIMFPACKAGEINFO] ADD CONSTRAINT [PK_PO_PIMFPACKAGEINFO] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PLUGIN].[PK_PO_PLUGIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PLUGIN] ADD CONSTRAINT [PK_PO_PLUGIN] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREFERENCE].[PK_PO_PREFERENCE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PREFERENCE] ADD CONSTRAINT [PK_PO_PREFERENCE] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREFERENCEGROUP].[PK_PO_PREFERENCEGROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PREFERENCEGROUP] ADD CONSTRAINT [PK_PO_PREFERENCEGROUP] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PREGISTEREDCAPABILITIE].[PK_PO_PREGISTEREDCAPABILI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PREGISTEREDCAPABILITIE] ADD CONSTRAINT [PK_PO_PREGISTEREDCAPABILI] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PRIVILEGE].[PK_PO_PRIVILEGE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PRIVILEGE] ADD CONSTRAINT [PK_PO_PRIVILEGE] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESS].[PK_PO_PROCESS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PROCESS] ADD CONSTRAINT [PK_PO_PROCESS] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROCESSRUNTIME].[PK_PO_PROCESSRUNTIME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PROCESSRUNTIME] ADD CONSTRAINT [PK_PO_PROCESSRUNTIME] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_PROPIDTOCOLUMN].[PK_PO_PROPIDTOCOLUMN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_PROPIDTOCOLUMN] ADD CONSTRAINT [PK_PO_PROPIDTOCOLUMN] PRIMARY KEY CLUSTERED (
	[PSP_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDLOGFILE].[PK_PO_REGISTEREDLOGFILE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDLOGFILE] ADD CONSTRAINT [PK_PO_REGISTEREDLOGFILE] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUN].[PK_PO_REGISTEREDRUN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDRUN] ADD CONSTRAINT [PK_PO_REGISTEREDRUN] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REGISTEREDRUNLOG].[PK_PO_REGISTEREDRUNLOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REGISTEREDRUNLOG] ADD CONSTRAINT [PK_PO_REGISTEREDRUNLOG] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPORTSELECTIONGROUP].[PK_PO_REPORTSELECTIONGROU].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPORTSELECTIONGROUP] ADD CONSTRAINT [PK_PO_REPORTSELECTIONGROU] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYOPERATIONALI].[PK_PO_REPOSITORYOPERATION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPOSITORYOPERATIONALI] ADD CONSTRAINT [PK_PO_REPOSITORYOPERATION] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_REPOSITORYUPGRADEINFO].[PK_PO_REPOSITORYUPGRADEIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_REPOSITORYUPGRADEINFO] ADD CONSTRAINT [PK_PO_REPOSITORYUPGRADEIN] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_RESOURCESTRING].[PK_PO_RESOURCESTRING].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_RESOURCESTRING] ADD CONSTRAINT [PK_PO_RESOURCESTRING] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_ROLETYPECONTAINER].[PK_PO_ROLETYPECONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_ROLETYPECONTAINER] ADD CONSTRAINT [PK_PO_ROLETYPECONTAINER] PRIMARY KEY CLUSTERED (
	[PSR_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SAMLCONFIG].[PK_PO_SAMLCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SAMLCONFIG] ADD CONSTRAINT [PK_PO_SAMLCONFIG] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTBASEATTRIBUT].[PK_PO_SDKCONNECTBASEATTRI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTBASEATTRIBUT] ADD CONSTRAINT [PK_PO_SDKCONNECTBASEATTRI] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOATTR].[PK_PO_SDKCONNECTINFOATTR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTINFOATTR] ADD CONSTRAINT [PK_PO_SDKCONNECTINFOATTR] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTINFOMODELEXT].[PK_PO_SDKCONNECTINFOMODEL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTINFOMODELEXT] ADD CONSTRAINT [PK_PO_SDKCONNECTINFOMODEL] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONATTRDEF].[PK_PO_SDKCONNECTIONATTRDE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTIONATTRDEF] ADD CONSTRAINT [PK_PO_SDKCONNECTIONATTRDE] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SDKCONNECTIONTYPE].[PK_PO_SDKCONNECTIONTYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SDKCONNECTIONTYPE] ADD CONSTRAINT [PK_PO_SDKCONNECTIONTYPE] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYCONFIG].[PK_PO_SECURITYCONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SECURITYCONFIG] ADD CONSTRAINT [PK_PO_SECURITYCONFIG] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SECURITYDOMAIN].[PK_PO_SECURITYDOMAIN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SECURITYDOMAIN] ADD CONSTRAINT [PK_PO_SECURITYDOMAIN] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPRIVILEGEDEF].[PK_PO_SERVICEPRIVILEGEDEF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEPRIVILEGEDEF] ADD CONSTRAINT [PK_PO_SERVICEPRIVILEGEDEF] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEPROCESSSTARTUPS].[PK_PO_SERVICEPROCESSSTART].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEPROCESSSTARTUPS] ADD CONSTRAINT [PK_PO_SERVICEPROCESSSTART] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICEREF].[PK_PO_SERVICEREF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICEREF] ADD CONSTRAINT [PK_PO_SERVICEREF] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICERUNTIME].[PK_PO_SERVICERUNTIME].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICERUNTIME] ADD CONSTRAINT [PK_PO_SERVICERUNTIME] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SERVICESTARTUPSTATE].[PK_PO_SERVICESTARTUPSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SERVICESTARTUPSTATE] ADD CONSTRAINT [PK_PO_SERVICESTARTUPSTATE] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SMTPOPTIONS].[PK_PO_SMTPOPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SMTPOPTIONS] ADD CONSTRAINT [PK_PO_SMTPOPTIONS] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORT].[PK_PO_SORT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORT] ADD CONSTRAINT [PK_PO_SORT] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTPORT].[PK_PO_SORTPORT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORTPORT] ADD CONSTRAINT [PK_PO_SORTPORT] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SORTSYSTEM].[PK_PO_SORTSYSTEM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SORTSYSTEM] ADD CONSTRAINT [PK_PO_SORTSYSTEM] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STAGINGINFOATTRIBUTES].[PK_PO_STAGINGINFOATTRIBUT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_STAGINGINFOATTRIBUTES] ADD CONSTRAINT [PK_PO_STAGINGINFOATTRIBUT] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STOREDSTARTUPSTATE].[PK_PO_STOREDSTARTUPSTATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_STOREDSTARTUPSTATE] ADD CONSTRAINT [PK_PO_STOREDSTARTUPSTATE] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_STRINGVALUE].[PK_PO_STRINGVALUE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_STRINGVALUE] ADD CONSTRAINT [PK_PO_STRINGVALUE] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_SUBSTITUTEHOLDER].[PK_PO_SUBSTITUTEHOLDER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_SUBSTITUTEHOLDER] ADD CONSTRAINT [PK_PO_SUBSTITUTEHOLDER] PRIMARY KEY CLUSTERED (
	[PSS_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAG].[PK_PO_TAG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TAG] ADD CONSTRAINT [PK_PO_TAG] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TAGLINKS].[PK_PO_TAGLINKS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TAGLINKS] ADD CONSTRAINT [PK_PO_TAGLINKS] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TIMEOFDAY].[PK_PO_TIMEOFDAY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TIMEOFDAY] ADD CONSTRAINT [PK_PO_TIMEOFDAY] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPE].[PK_PO_TYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPE] ADD CONSTRAINT [PK_PO_TYPE] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEACONNECTIONATTRIBU].[PK_PO_TYPEACONNECTIONATTR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEACONNECTIONATTRIBU] ADD CONSTRAINT [PK_PO_TYPEACONNECTIONATTR] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEBCONNECTIONATTRIBU].[PK_PO_TYPEBCONNECTIONATTR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEBCONNECTIONATTRIBU] ADD CONSTRAINT [PK_PO_TYPEBCONNECTIONATTR] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONFIG].[PK_PO_TYPECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPECONFIG] ADD CONSTRAINT [PK_PO_TYPECONFIG] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPECONTAINER].[PK_PO_TYPECONTAINER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPECONTAINER] ADD CONSTRAINT [PK_PO_TYPECONTAINER] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPEDELEMENT].[PK_PO_TYPEDELEMENT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPEDELEMENT] ADD CONSTRAINT [PK_PO_TYPEDELEMENT] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_TYPERCONNECTIONATTRIBU].[PK_PO_TYPERCONNECTIONATTR].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_TYPERCONNECTIONATTRIBU] ADD CONSTRAINT [PK_PO_TYPERCONNECTIONATTR] PRIMARY KEY CLUSTERED (
	[PST_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UMSERVICECONFIG].[PK_PO_UMSERVICECONFIG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_UMSERVICECONFIG] ADD CONSTRAINT [PK_PO_UMSERVICECONFIG] PRIMARY KEY CLUSTERED (
	[PSU_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERACCOUNTSECURITYCON].[PK_PO_USERACCOUNTSECURITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_USERACCOUNTSECURITYCON] ADD CONSTRAINT [PK_PO_USERACCOUNTSECURITY] PRIMARY KEY CLUSTERED (
	[PSU_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_USERINFO].[PK_PO_USERINFO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_USERINFO] ADD CONSTRAINT [PK_PO_USERINFO] PRIMARY KEY CLUSTERED (
	[PSU_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_UUMNAMESPACE].[PK_PO_UUMNAMESPACE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_UUMNAMESPACE] ADD CONSTRAINT [PK_PO_UUMNAMESPACE] PRIMARY KEY CLUSTERED (
	[PSU_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_VALUE].[PK_PO_VALUE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_VALUE] ADD CONSTRAINT [PK_PO_VALUE] PRIMARY KEY CLUSTERED (
	[PSV_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PO_VALUETYPE].[PK_PO_VALUETYPE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PO_VALUETYPE] ADD CONSTRAINT [PK_PO_VALUETYPE] PRIMARY KEY CLUSTERED (
	[PSV_OPID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_B_RSID_TXID].[PK_PR_B_RSID_TXID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PR_B_RSID_TXID] ADD CONSTRAINT [PK_PR_B_RSID_TXID] PRIMARY KEY CLUSTERED (
	[PRB_TXID] ASC,
	[PRB_RSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RESOURCE].[PISR_C_UNIQUERS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PR_RESOURCE] ADD CONSTRAINT [PISR_C_UNIQUERS] UNIQUE CLUSTERED (
	[PRR_NSID] ASC,
	[PRR_PARENTID] ASC,
	[PRR_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PR_RSID_TXID].[PK_PR_RSID_TXID].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PR_RSID_TXID] ADD CONSTRAINT [PK_PR_RSID_TXID] PRIMARY KEY CLUSTERED (
	[PRR_ID] ASC
) ON [PRIMARY]
