
GO
--SqlScripter----[dbo].[TOP_FIELD].[TOP_FIELDI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [TOP_FIELDI] ON [dbo].[TOP_FIELD] (
	[FIELD_TABLE] ASC,
	[FIELD_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TOP_IDXSTATS].[TOP_IDXSTATSI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [TOP_IDXSTATSI] ON [dbo].[TOP_IDXSTATS] (
	[IDX_ENV] ASC,
	[IDX_USE] ASC,
	[IDX_TABLE] ASC,
	[IDX_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TOP_PARAM].[TOP_PARAM1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE NONCLUSTERED INDEX [TOP_PARAM1] ON [dbo].[TOP_PARAM] (
	[PARAM_SESSION] ASC,
	[PARAM_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TOP_VIRTUALIDX].[TOP_VIRTUALIDXI].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [TOP_VIRTUALIDXI] ON [dbo].[TOP_VIRTUALIDX] (
	[IDX_ENV] ASC,
	[IDX_TABLE] ASC,
	[IDX_NAME] ASC
) ON [PRIMARY]
