SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS_bkp](
	[USERNAME] [nvarchar](10) NULL,
	[PASSWORD] [nvarchar](10) NULL,
	[NOMBRE] [nvarchar](50) NULL
)
ON [PRIMARY]
