
GO
--SqlScripter----[dbo].[COR_SIGA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[COR_SIGA]') IS NULL EXEC('CREATE VIEW [dbo].[COR_SIGA] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[COR_SIGA]
AS SELECT f1_corrsin AS correlativo FROM SF1010 WHERE D_E_L_E_T_ <> '*' AND F1_ESPECIE = 'NF' UNION SELECT f2_corrsin AS correlativo FROM SF2010 WHERE D_E_L_E_T_ <> '*' AND F2_ESPECIE = 'NCP'
GO

GO
--SqlScripter----[dbo].[COR_SIGA2].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[COR_SIGA2]') IS NULL EXEC('CREATE VIEW [dbo].[COR_SIGA2] AS /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ SELECT 0 C1')
GO
ALTER VIEW [dbo].[COR_SIGA2]
AS SELECT f1_corrsin AS correlativo FROM SF1030 WHERE D_E_L_E_T_ <> '*' AND F1_ESPECIE = 'NF' UNION SELECT f2_corrsin AS correlativo FROM SF2030 WHERE D_E_L_E_T_ <> '*' AND F2_ESPECIE = 'NCP'
GO
