SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaPrivilegiosPerfil]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaPrivilegiosPerfil] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaPrivilegiosPerfil]
@error varchar(255)  OUTPUT,
   @vcCodigoPrivilegio varchar(10)
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaPrivilegiosPerfil
   *    *  Objetivo:       Consulta sobre los privilegios y los perfiles relacionados.
   *    *  Autor Creacin: Andrea Zarabia.
   *    *  Fecha Creacin: 30/09/2010
   *   
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        @vcCodigoPrivilegio    Codigo del privilegio.
   *    *
   *    *  Salida:         @error          error de salida
   *    *
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT rpp.vcCodigoPerfil, pe.vcDescripcionPerfil
      FROM dbo.tblRelPrivilegioPerfil  AS rpp, dbo.tblPrivilegio  AS pr, dbo.tblPerfil  AS pe
      WHERE 
         rpp.vcCodigoPrivilegio = @vcCodigoPrivilegio AND 
         pr.vcCodigoPrivilegio = rpp.vcCodigoPrivilegio AND 
         pe.vcCodigoPerfil = rpp.vcCodigoPerfil
      ORDER BY rpp.vcCodigoPerfil
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
