SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaDestinataEmailFT3]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaDestinataEmailFT3] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaDestinataEmailFT3]
@error varchar(255)  OUTPUT,
   @vcCodigoCasilla varchar(8)
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaDestinataEmailFT3
   *    *  Objetivo:       Consulta sobre los posibles destinatarios, de acuerdo a la casilla.
   *    *  Autor Creación: Andrea Zarabia V.
   *    *  Fecha Creación: 15/10/2010
   *   
   *    *  Autor Modific.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        @vcCodigoCasilla   Codigo casilla.
   *    *
   *    *  Salida:         @error         error de salida
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT u.vcCodigoUsuario, u.vcNombreUsuario, u.vcDireccionEmail, u.vcCodigoInstitucion
      FROM dbo.tblUsuario  AS u, dbo.tbl_inst  AS i, dbo.tbl_casi  AS c
      WHERE 
         c.cod_casi = @vcCodigoCasilla AND 
         i.cod_inst = c.cod_inst AND 
         u.vcCodigoInstitucion = i.cod_inst
      ORDER BY u.vcCodigoUsuario
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
