SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[spFT3ConsultaInstitucCasilla]') IS NULL EXEC('CREATE PROCEDURE [dbo].[spFT3ConsultaInstitucCasilla] AS PRINT ''TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED''')
GO
ALTER PROCEDURE [dbo].[spFT3ConsultaInstitucCasilla]
@error varchar(255)  OUTPUT
AS 
   
   /*
   *   Generated by SQL Server Migration Assistant for Sybase version 5.2.1260.
   *   
   *    *  Servicio:       spFT3ConsultaInstitucCasilla
   *    *  Objetivo:       Consulta instituciones.
   *    *  Autor Creacion: Andrea Zarabia.
   *    *  Fecha Creacion: 18/08/2010
   *   
   *    *  Autor Modifi.:
   *    *  Fecha Modific.:
   *    *
   *    *  Entrada:        No hay
   *    *
   *    *  Salida:         @error          error de salida
   *    *
   *    *  Comentario:     No hay.
   *
   */
   BEGIN
      SELECT i.cod_inst AS vcCodigoInstitucion, i.nom_inst AS vc_nom_inst, c.cod_casi, c.usu_cnxn
      FROM dbo.tbl_inst  AS i, dbo.tbl_casi  AS c
      WHERE i.cod_inst = c.cod_inst
      ORDER BY i.nom_inst, c.cod_casi
   END
   IF @@ROWCOUNT < 1
      BEGIN

         SELECT @error = 'NO EXISTEN DATOS'

         RETURN 1

      END
   SELECT @error = ''
   RETURN 0
GO
