SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_EXTN_ATTR](
	[WORKFLOW_ID] [int] NULL,
	[SESSION_ID] [int] NULL,
	[SESSION_INST_ID] [int] NULL,
	[SESS_WIDG_INST_ID] [int] NULL,
	[PROC_INSTANCE_ID] [int] NULL,
	[ATTR_ID] [int] NULL,
	[ATTR_VALUE] [text] NULL,
	[LINE_NO] [int] NULL,
	[PARTITION_ID] [int] NULL,
	[OPB_OBJECT_ID] [int] NULL,
	[VERSION_NUMBER] [int] NULL,
	[OBJECT_TYPE] [int] NULL,
	[OBJECT_SUBTYPE] [int] NULL,
	[COMP_VERSION] [int] NULL
)
ON [PRIMARY]
