SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_SWIDGINST_LOG](
	[WORKFLOW_ID] [int] NULL,
	[WORKFLOW_RUN_ID] [int] NULL,
	[WORKLET_RUN_ID] [int] NULL,
	[TASK_INSTANCE_ID] [int] NULL,
	[PARTITION_ID] [int] NULL,
	[PARTITION_NAME] [varchar](240) NULL,
	[SESSION_ID] [int] NULL,
	[SESSWIDG_INST_ID] [int] NULL,
	[WIDGET_TYPE] [int] NULL,
	[INSTANCE_NAME] [varchar](240) NULL,
	[MAPPLET_INST_NAME] [varchar](240) NULL,
	[WIDGET_NAME] [varchar](240) NULL,
	[GROUP_ID] [int] NULL,
	[GROUP_NAME] [varchar](240) NULL,
	[APPLIED_ROWS] [int] NULL,
	[AFFECTED_ROWS] [int] NULL,
	[REJECTED_ROWS] [int] NULL,
	[THRUPUT] [int] NULL,
	[LAST_ERR_MSG] [text] NULL,
	[LAST_ERR_CODE] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL
)
ON [PRIMARY]
