SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_WIDGET_ATTR](
	[WIDGET_ID] [int] NULL,
	[WIDGET_TYPE] [int] NULL,
	[MAPPING_ID] [int] NULL,
	[INSTANCE_ID] [int] NULL,
	[SESSION_ID] [int] NULL,
	[ATTR_ID] [int] NULL,
	[LINE_NO] [int] NULL,
	[ATTR_VALUE] [text] NULL,
	[PARTITION_ID] [int] NULL,
	[SESSION_TASK_ID] [int] NULL,
	[VERSION_NUMBER] [int] NULL
)
ON [PRIMARY]
