SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_DTL_SWIDG_LOG](
	[WORKFLOW_ID] [int] NULL,
	[WORKFLOW_RUN_ID] [int] NULL,
	[WORKLET_RUN_ID] [int] NULL,
	[TASK_INSTANCE_ID] [int] NULL,
	[SESSION_ID] [int] NULL,
	[SESSWIDG_INST_ID] [int] NULL,
	[PARTITION_ID] [int] NULL,
	[GROUP_ID] [int] NULL,
	[SRC_SWIDGINST_ID] [int] NULL,
	[CONNECTION_ID] [int] NULL,
	[LOCATION_NAME] [text] NULL,
	[LOCATION_TYPE] [int] NULL,
	[LINE_NUMBER] [int] NULL
)
ON [PRIMARY]
