SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_WIDGET_FIELD](
	[WIDGET_ID] [int] NULL,
	[FIELD_NAME] [varchar](240) NULL,
	[FIELD_ID] [int] NULL,
	[WGT_PREC] [int] NULL,
	[WGT_SCALE] [int] NULL,
	[WGT_DATATYPE] [int] NULL,
	[PORTTYPE] [int] NULL,
	[FIELD_ORDER] [int] NULL,
	[COMMENTS] [text] NULL,
	[WIDGET_FLD_PROP] [int] NULL,
	[DEFAULT_VALUE] [text] NULL,
	[SRC_FIELD_ID] [int] NULL,
	[GROUP_ID] [int] NULL,
	[WIDGET_FLD_PROP2] [int] NULL,
	[VERSION_NUMBER] [int] NULL,
	[OUTGROUP_ID] [int] NULL,
	[PICTXT] [varchar](240) NULL
)
ON [PRIMARY]
