SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPB_TASK_INST_RUN](
	[SUBJECT_ID] [int] NULL,
	[WORKFLOW_ID] [int] NULL,
	[WORKFLOW_RUN_ID] [int] NULL,
	[WORKLET_RUN_ID] [int] NULL,
	[CHILD_RUN_ID] [int] NULL,
	[INSTANCE_ID] [int] NULL,
	[INSTANCE_NAME] [varchar](240) NULL,
	[TASK_ID] [int] NULL,
	[TASK_TYPE] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[RUN_ERR_CODE] [int] NULL,
	[RUN_ERR_MSG] [text] NULL,
	[RUN_STATUS_CODE] [int] NULL,
	[TASK_NAME] [varchar](240) NULL,
	[RUN_MODE] [int] NULL,
	[VERSION_NUMBER] [int] NULL,
	[SERVER_ID] [int] NULL,
	[SERVER_NAME] [varchar](240) NULL,
	[FRAGMENT_ID] [int] NULL,
	[SERVER_NODE_ID] [int] NULL,
	[SERVER_NODE_NAME] [varchar](240) NULL
)
ON [PRIMARY]
