
GO
--SqlScripter----[dbo].[ADHOCAPPROVALS].[PK_ADHOCAPPROVALS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ADHOCAPPROVALS] ADD CONSTRAINT [PK_ADHOCAPPROVALS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ADMIN_IMPORT_USERS_LOGS].[PK_ADMIN_IMPORT_USERS_LOGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ADMIN_IMPORT_USERS_LOGS] ADD CONSTRAINT [PK_ADMIN_IMPORT_USERS_LOGS] PRIMARY KEY CLUSTERED (
	[IMPORT_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ALMACEN_ARCHIVOS].[PK_ALMACEN_ARCHIVOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ALMACEN_ARCHIVOS] ADD CONSTRAINT [PK_ALMACEN_ARCHIVOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[APROBACIONES].[PK_APROBACIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[APROBACIONES] ADD CONSTRAINT [PK_APROBACIONES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ARCHIVOS].[PK_ARCHIVOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ARCHIVOS] ADD CONSTRAINT [PK_ARCHIVOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUD_RELATEDITEMS].[PK_AUD_RELATEDITEMS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUD_RELATEDITEMS] ADD CONSTRAINT [PK_AUD_RELATEDITEMS] PRIMARY KEY CLUSTERED (
	[A_ID] ASC,
	[ITEM_MASK] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUDITEDS].[PK_AUDITEDS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUDITEDS] ADD CONSTRAINT [PK_AUDITEDS] PRIMARY KEY CLUSTERED (
	[AUDITEDS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUDITORIAS].[PK_AUDITORIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUDITORIAS] ADD CONSTRAINT [PK_AUDITORIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUDITORIASARCHIVOS].[PK_AUDITORIASARCHIVOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUDITORIASARCHIVOS] ADD CONSTRAINT [PK_AUDITORIASARCHIVOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUDITORIASTIPOS].[PK_AUDITORIASTIPOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUDITORIASTIPOS] ADD CONSTRAINT [PK_AUDITORIASTIPOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[AUDITORS].[PK_AUDITORS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[AUDITORS] ADD CONSTRAINT [PK_AUDITORS] PRIMARY KEY CLUSTERED (
	[AUDITORS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_IND_ASSESMENTS].[PK_BS_IND_ASSESMENTS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_IND_ASSESMENTS] ADD CONSTRAINT [PK_BS_IND_ASSESMENTS] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC,
	[PERIODID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_IND_STATE_CACHE].[PK_BS_IND_STATE_CACHE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_IND_STATE_CACHE] ADD CONSTRAINT [PK_BS_IND_STATE_CACHE] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC,
	[PERIODID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS].[PK_BS_INDICATORS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS] ADD CONSTRAINT [PK_BS_INDICATORS] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS_DATA_ARCHIVED].[PK_BSINDICATORS_DATA_ARCHIVED].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS_DATA_ARCHIVED] ADD CONSTRAINT [PK_BSINDICATORS_DATA_ARCHIVED] PRIMARY KEY CLUSTERED (
	[BS_INDICATORS_DATA_ARCHIVEDID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS_LAST_CALCULATE].[PK_BS_INDICATORS_LAST_CALCULATE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS_LAST_CALCULATE] ADD CONSTRAINT [PK_BS_INDICATORS_LAST_CALCULATE] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS_NOTIFICATIONS].[PK_BS_INDICATORS_NOTIFICATIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS_NOTIFICATIONS] ADD CONSTRAINT [PK_BS_INDICATORS_NOTIFICATIONS] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC,
	[USERID] ASC,
	[PERIODID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS_OPTIONS].[PK_BS_INDICATORS_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS_OPTIONS] ADD CONSTRAINT [PK_BS_INDICATORS_OPTIONS] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORS_RECALC_LOGS].[PK_BS_INDICATORS_RECALCULATION_LOGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORS_RECALC_LOGS] ADD CONSTRAINT [PK_BS_INDICATORS_RECALCULATION_LOGS] PRIMARY KEY CLUSTERED (
	[BS_LOGS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORSCATEGORIES].[PK_BS_INDICATORSCATEGORIES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORSCATEGORIES] ADD CONSTRAINT [PK_BS_INDICATORSCATEGORIES] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSCATEGORIESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORSDATA].[PK_BS_INDICATORSDATA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORSDATA] ADD CONSTRAINT [PK_BS_INDICATORSDATA] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSDATAID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_INDICATORSREL].[PK_BS_INDICATORSREL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_INDICATORSREL] ADD CONSTRAINT [PK_BS_INDICATORSREL] PRIMARY KEY CLUSTERED (
	[BS_INDICATORSID] ASC,
	[REL_BS_INDICATORSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_LOCATIONS].[PK_BS_LOCATIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_LOCATIONS] ADD CONSTRAINT [PK_BS_LOCATIONS] PRIMARY KEY CLUSTERED (
	[BS_LOCATIONSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODE_TYPES].[PK_BSSTRAT_NODETYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODE_TYPES] ADD CONSTRAINT [PK_BSSTRAT_NODETYPES] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODE_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODES].[PK_IK_STRAT_NODES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODES] ADD CONSTRAINT [PK_IK_STRAT_NODES] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODES_OPTIONS].[PK_BS_STRAT_NODES_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_OPTIONS] ADD CONSTRAINT [PK_BS_STRAT_NODES_OPTIONS] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODESID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS].[PK_BS_STRAT_NODES_RELATIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS] ADD CONSTRAINT [PK_BS_STRAT_NODES_RELATIONS] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODESID_SOURCE] ASC,
	[BS_STRAT_NODESID_TARGET] ASC,
	[BS_STRAT_NODES_RELS_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELATIONS_TYPES].[PK_BS_STRAT_NODES_RELATION_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELATIONS_TYPES] ADD CONSTRAINT [PK_BS_STRAT_NODES_RELATION_TYPES] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODES_RELS_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_NODES_RELS_STRENGTH].[PK_BS_STRAT_NODES_RELATIONS_STRENGHT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_NODES_RELS_STRENGTH] ADD CONSTRAINT [PK_BS_STRAT_NODES_RELATIONS_STRENGHT] PRIMARY KEY CLUSTERED (
	[BS_STRAT_NODES_RELS_STRENGTHID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_PLANS].[PK_BS_STRAT_PLAN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS] ADD CONSTRAINT [PK_BS_STRAT_PLAN] PRIMARY KEY CLUSTERED (
	[BS_STRAT_PLANSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRAT_PLANS_OPTIONS].[PK_BS_STRAT_PLANS_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRAT_PLANS_OPTIONS] ADD CONSTRAINT [PK_BS_STRAT_PLANS_OPTIONS] PRIMARY KEY CLUSTERED (
	[BS_STRAT_PLANSID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_STRATINITIATIVESTYPES].[PK_BS_STRATINITIATIVESTYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_STRATINITIATIVESTYPES] ADD CONSTRAINT [PK_BS_STRATINITIATIVESTYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_SVG].[PK_BS_SVG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_SVG] ADD CONSTRAINT [PK_BS_SVG] PRIMARY KEY CLUSTERED (
	[BS_SVGID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[BS_SVG_OPTIONS].[PK_BS_SVG_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[BS_SVG_OPTIONS] ADD CONSTRAINT [PK_BS_SVG_OPTIONS] PRIMARY KEY CLUSTERED (
	[BS_SVGID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[CARGOS_CANTIDAD_PERSONAS].[PK_CARGOS_CANTIDAD_PERSONAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[CARGOS_CANTIDAD_PERSONAS] ADD CONSTRAINT [PK_CARGOS_CANTIDAD_PERSONAS] PRIMARY KEY CLUSTERED (
	[CODIGO_CARGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[CARGOSUSUARIOS].[PK_CARGOSUSUARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[CARGOSUSUARIOS] ADD CONSTRAINT [PK_CARGOSUSUARIOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[CRITICAS].[PK_CRITICAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[CRITICAS] ADD CONSTRAINT [PK_CRITICAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DATOSUSUARIOS].[PK_DATOSUSUARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DATOSUSUARIOS] ADD CONSTRAINT [PK_DATOSUSUARIOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DISTRIBUCION].[PK_DISTRIBUCION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DISTRIBUCION] ADD CONSTRAINT [PK_DISTRIBUCION] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOS].[PK_DOCUMENTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOS] ADD CONSTRAINT [PK_DOCUMENTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOS_CHANGELOG].[PK_DOCUMENTOS_CHANGELOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOS_CHANGELOG] ADD CONSTRAINT [PK_DOCUMENTOS_CHANGELOG] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOS_EXTRADATA].[PK_DOCUMENTOS_EXTRADATA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOS_EXTRADATA] ADD CONSTRAINT [PK_DOCUMENTOS_EXTRADATA] PRIMARY KEY CLUSTERED (
	[CODIGODOCUMENTO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOSCATEGORIAS].[PK_DOCUMENTOSCATEGORIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOSCATEGORIAS] ADD CONSTRAINT [PK_DOCUMENTOSCATEGORIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOSHISTORIA].[PK_DOCUMENTOSHISTORIA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOSHISTORIA] ADD CONSTRAINT [PK_DOCUMENTOSHISTORIA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOSREL].[PK_DOCUMENTOSREL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOSREL] ADD CONSTRAINT [PK_DOCUMENTOSREL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[DOCUMENTOSRELTRANS].[PK_DOCUMENTOSRELTRANS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[DOCUMENTOSRELTRANS] ADD CONSTRAINT [PK_DOCUMENTOSRELTRANS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ESTADOS].[PK_ESTADOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ESTADOS] ADD CONSTRAINT [PK_ESTADOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ESTADOSPROCESOS].[PK_ESTADOSPROCESOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ESTADOSPROCESOS] ADD CONSTRAINT [PK_ESTADOSPROCESOS] PRIMARY KEY CLUSTERED (
	[CODIGOESTADO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ESTADOSTAREASDOCUMENTOS].[PK_ESTADOSTAREASDOCUMENTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ESTADOSTAREASDOCUMENTOS] ADD CONSTRAINT [PK_ESTADOSTAREASDOCUMENTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[FROZEN_PRESENTATIONS_ITEMS].[PK_FROZEN_PANELS_ITEMS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[FROZEN_PRESENTATIONS_ITEMS] ADD CONSTRAINT [PK_FROZEN_PANELS_ITEMS] PRIMARY KEY CLUSTERED (
	[ITEM_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIAASUNTOS].[PK_HISTORIAASUNTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIAASUNTOS] ADD CONSTRAINT [PK_HISTORIAASUNTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIADIAGRAMAS].[PK_HISTORIADIAGRAMAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIADIAGRAMAS] ADD CONSTRAINT [PK_HISTORIADIAGRAMAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIAESTRATEGIAS].[PK_HISTORIAESTRATEGIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIAESTRATEGIAS] ADD CONSTRAINT [PK_HISTORIAESTRATEGIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIAINDICADORES].[PK_HISTORIAINDICADORES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIAINDICADORES] ADD CONSTRAINT [PK_HISTORIAINDICADORES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIANODOSESTRATEGICOS].[PK_HISTORIANODOSESTRATEGICOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIANODOSESTRATEGICOS] ADD CONSTRAINT [PK_HISTORIANODOSESTRATEGICOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIANODOSPLANESPROCESO].[PK_HISTORIANODOSPLANESPROCESO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIANODOSPLANESPROCESO] ADD CONSTRAINT [PK_HISTORIANODOSPLANESPROCESO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[HISTORIAPLANESPROCESO].[PK_HISTORIAPLANESPROCESO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[HISTORIAPLANESPROCESO] ADD CONSTRAINT [PK_HISTORIAPLANESPROCESO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IK_CLIENT_SETTINGS].[PK_IK_CLIENT_SETTINGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IK_CLIENT_SETTINGS] ADD CONSTRAINT [PK_IK_CLIENT_SETTINGS] PRIMARY KEY CLUSTERED (
	[IK_CLIENT_SETTINGS_KEY] ASC,
	[USER_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IK_DFS].[PK_IK_DFS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IK_DFS] ADD CONSTRAINT [PK_IK_DFS] PRIMARY KEY CLUSTERED (
	[IK_DFS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IK_HTMLREPORTS_OPTIONS].[PK_IK_HTMLREPORTS_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IK_HTMLREPORTS_OPTIONS] ADD CONSTRAINT [PK_IK_HTMLREPORTS_OPTIONS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IK_PEOPLE].[PK_USUARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IK_PEOPLE] ADD CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKALERTS].[PK_IKALERTS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKALERTS] ADD CONSTRAINT [PK_IKALERTS] PRIMARY KEY CLUSTERED (
	[IKALERTS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKALERTS_TARGETS].[PK_IKALERTS_TARGETS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKALERTS_TARGETS] ADD CONSTRAINT [PK_IKALERTS_TARGETS] PRIMARY KEY CLUSTERED (
	[IKALERTS_ID] ASC,
	[USERID_TARGET] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKALERTS_USERS_OPTIONS].[PK_IKALERTS_USERS_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKALERTS_USERS_OPTIONS] ADD CONSTRAINT [PK_IKALERTS_USERS_OPTIONS] PRIMARY KEY CLUSTERED (
	[IKALERTS_ID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKERRORLOG].[PK_IKERRORLOG].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKERRORLOG] ADD CONSTRAINT [PK_IKERRORLOG] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFILES].[PK_IKFILES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFILES] ADD CONSTRAINT [PK_IKFILES] PRIMARY KEY CLUSTERED (
	[IKFILESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROS].[PK_IKFORUMS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFOROS] ADD CONSTRAINT [PK_IKFORUMS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSARCHIVOS].[PK_IKFOROSARCHIVOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFOROSARCHIVOS] ADD CONSTRAINT [PK_IKFOROSARCHIVOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSMENSAJES].[PK_IKFOROSMENSAJES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFOROSMENSAJES] ADD CONSTRAINT [PK_IKFOROSMENSAJES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSNOVEDADES].[PK_IKFOROSNOVEDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFOROSNOVEDADES] ADD CONSTRAINT [PK_IKFOROSNOVEDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKFOROSSUSCRIPTORES].[PK_IKFOROSSUSCRIPTORES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKFOROSSUSCRIPTORES] ADD CONSTRAINT [PK_IKFOROSSUSCRIPTORES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_BSINDICATORS].[PK_IKI_BSINDICATORS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_BSINDICATORS] ADD CONSTRAINT [PK_IKI_BSINDICATORS] PRIMARY KEY CLUSTERED (
	[IKI_BSINDICATORSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_BSSTRATNODES].[PK_IKI_BSSTRATNODES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_BSSTRATNODES] ADD CONSTRAINT [PK_IKI_BSSTRATNODES] PRIMARY KEY CLUSTERED (
	[IKI_BSSTRATNODESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_BSSTRATPLANS].[PK_IKI_BSSTRATPLANS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_BSSTRATPLANS] ADD CONSTRAINT [PK_IKI_BSSTRATPLANS] PRIMARY KEY CLUSTERED (
	[IKI_BSSTRATPLANSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_DOCUMENTS].[PK_IKI_DOCUMENTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_DOCUMENTS] ADD CONSTRAINT [PK_IKI_DOCUMENTOS] PRIMARY KEY CLUSTERED (
	[IKI_DOCUMENTSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_FILES].[PK_IKI_FILES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_FILES] ADD CONSTRAINT [PK_IKI_FILES] PRIMARY KEY CLUSTERED (
	[IKI_FILESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_IKPEOPLE].[PK_IKI_IKPEOPLE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_IKPEOPLE] ADD CONSTRAINT [PK_IKI_IKPEOPLE] PRIMARY KEY CLUSTERED (
	[IKI_PERSONSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_ISSUES].[PK_IKI_ISSUES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_ISSUES] ADD CONSTRAINT [PK_IKI_ISSUES] PRIMARY KEY CLUSTERED (
	[IKI_ISSUESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_ISSUESTASKS].[PK_IKI_ISSUESTASKS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_ISSUESTASKS] ADD CONSTRAINT [PK_IKI_ISSUESTASKS] PRIMARY KEY CLUSTERED (
	[IKI_ISSUESTASKSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_MASTER].[PK_IKI_MASTER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_MASTER] ADD CONSTRAINT [PK_IKI_MASTER] PRIMARY KEY CLUSTERED (
	[IKI_MASTERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_NAXCHARTS].[PK_IKI_NAXCHARTS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_NAXCHARTS] ADD CONSTRAINT [PK_IKI_NAXCHARTS] PRIMARY KEY CLUSTERED (
	[IKI_NAXCHARTSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_ORGCHART].[PK_IKI_ORGCHART].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_ORGCHART] ADD CONSTRAINT [PK_IKI_ORGCHART] PRIMARY KEY CLUSTERED (
	[IKI_ORGCHARTID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_PROCNODES].[PK_IKI_PROCNODES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_PROCNODES] ADD CONSTRAINT [PK_IKI_PROCNODES] PRIMARY KEY CLUSTERED (
	[IKI_PROCNODESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_PROCPLANS].[PK_IKI_PROCPLANS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_PROCPLANS] ADD CONSTRAINT [PK_IKI_PROCPLANS] PRIMARY KEY CLUSTERED (
	[IKI_PROCPLANSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKI_SVGDRAWINGS].[PK_IKI_SVGDRAWINGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKI_SVGDRAWINGS] ADD CONSTRAINT [PK_IKI_SVGDRAWINGS] PRIMARY KEY CLUSTERED (
	[IKI_SVGDRAWINGSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKMAILS].[PK_IKMAIL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKMAILS] ADD CONSTRAINT [PK_IKMAIL] PRIMARY KEY CLUSTERED (
	[IKMAILS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKNOTIFICACIONES].[PK_IKNOTIFICACIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES] ADD CONSTRAINT [PK_IKNOTIFICACIONES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKNOTIFICACIONES_OPCIONES].[PK_IKNOTIFICACIONES_OPCIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES_OPCIONES] ADD CONSTRAINT [PK_IKNOTIFICACIONES_OPCIONES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKNOTIFICACIONES_PROFILES].[PK_IKNOTIFICACIONES_PROFILES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKNOTIFICACIONES_PROFILES] ADD CONSTRAINT [PK_IKNOTIFICACIONES_PROFILES] PRIMARY KEY CLUSTERED (
	[IKNOTIFICACIONES_PROFILESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKPOSITIONSGROUPS].[PK_DOCDISTRIBUTIONGROUPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPS] ADD CONSTRAINT [PK_DOCDISTRIBUTIONGROUPS] PRIMARY KEY CLUSTERED (
	[IKPOSITIONSGROUPSTREEID] ASC,
	[POSITIONID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKPOSITIONSGROUPSTREE].[PK_IKPOSITIONGROUPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKPOSITIONSGROUPSTREE] ADD CONSTRAINT [PK_IKPOSITIONGROUPS] PRIMARY KEY CLUSTERED (
	[IKPOSITIONSGROUPSTREEID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKPROFILES].[PK_IKPROFILES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKPROFILES] ADD CONSTRAINT [PK_IKPROFILES] PRIMARY KEY CLUSTERED (
	[IKPROFILESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES].[PK_IKROLES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES] ADD CONSTRAINT [PK_IKROLES] PRIMARY KEY CLUSTERED (
	[IKROLES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_ASUNTOS].[PK_IKROLES_ASUNTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_ASUNTOS] ADD CONSTRAINT [PK_IKROLES_ASUNTOS] PRIMARY KEY CLUSTERED (
	[ISSUE_ID] ASC,
	[IKROLES_ID] ASC,
	[NCWORKGROUPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_ASUNTOS4TPROT].[PK_IKROLES_ASUNTOS4TPROT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_ASUNTOS4TPROT] ADD CONSTRAINT [PK_IKROLES_ASUNTOS4TPROT] PRIMARY KEY CLUSTERED (
	[ISSUE_ID] ASC,
	[PROTOISSUE_ID] ASC,
	[IKROLES_ID] ASC,
	[TRANSACTION_UID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_NCINVOLUCRADOS].[PK_IKROLES_NCINVOLUCRADOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_NCINVOLUCRADOS] ADD CONSTRAINT [PK_IKROLES_NCINVOLUCRADOS] PRIMARY KEY CLUSTERED (
	[ISSUE_ID] ASC,
	[IKROLES_ID] ASC,
	[POSITION_ID] ASC,
	[NCWORKGROUPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_NCINVOLUCRADOS4TPROT].[PK_IKROLES_NCINVOLUCRADOS4TPROT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_NCINVOLUCRADOS4TPROT] ADD CONSTRAINT [PK_IKROLES_NCINVOLUCRADOS4TPROT] PRIMARY KEY CLUSTERED (
	[ISSUE_ID] ASC,
	[PROTOISSUE_ID] ASC,
	[IKROLES_ID] ASC,
	[POSITION_ID] ASC,
	[TRANSACTION_UID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_NCTAREAS].[PK_IKROLES_NCTAREAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_NCTAREAS] ADD CONSTRAINT [PK_IKROLES_NCTAREAS] PRIMARY KEY CLUSTERED (
	[NCTASK_ID] ASC,
	[IKROLES_ID] ASC,
	[NCWORKGROUPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_NCTASKSSTEPS].[PK_IKROLES_NCTASKSSTEPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_NCTASKSSTEPS] ADD CONSTRAINT [PK_IKROLES_NCTASKSSTEPS] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC,
	[IKROLES_ID] ASC,
	[NCWORKGROUPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_TPROT_TASK].[PK_IKROLES_TPROT_TASK].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_TPROT_TASK] ADD CONSTRAINT [PK_IKROLES_TPROT_TASK] PRIMARY KEY CLUSTERED (
	[NCTASK_ID] ASC,
	[IKROLES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKROLES_TPROT_TASKSSTEPS].[PK_IKROLES_TPROT_TASKSSTEPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKROLES_TPROT_TASKSSTEPS] ADD CONSTRAINT [PK_IKROLES_TPROT_TASKSSTEPS] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC,
	[IKROLES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKSAVEDSEARCHES].[PK_IKSAVEDSEARCHES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKSAVEDSEARCHES] ADD CONSTRAINT [PK_IKSAVEDSEARCHES] PRIMARY KEY CLUSTERED (
	[IKSAVEDSEARCHES_UID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKSKINS].[PK_IKSKINS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKSKINS] ADD CONSTRAINT [PK_IKSKINS] PRIMARY KEY CLUSTERED (
	[IKSKINS_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKUSERLOGINS].[PK_IKUSERLOGINS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKUSERLOGINS] ADD CONSTRAINT [PK_IKUSERLOGINS] PRIMARY KEY CLUSTERED (
	[IKUSERLOGINSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[IKUSERLOGS].[PK_IKUSERLOGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[IKUSERLOGS] ADD CONSTRAINT [PK_IKUSERLOGS] PRIMARY KEY CLUSTERED (
	[IKUSERLOGSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[INTERNACIONAL].[PK_INTERNACIONAL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[INTERNACIONAL] ADD CONSTRAINT [PK_INTERNACIONAL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[LUGARES].[PK_LUGARES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[LUGARES] ADD CONSTRAINT [PK_LUGARES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[MARCODOCUMENTOSREL].[PK_MARCODOCUMENTOSREL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[MARCODOCUMENTOSREL] ADD CONSTRAINT [PK_MARCODOCUMENTOSREL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[MATRIZ_APROBACIONES].[PK_MATRIZ_APROBACIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[MATRIZ_APROBACIONES] ADD CONSTRAINT [PK_MATRIZ_APROBACIONES] PRIMARY KEY CLUSTERED (
	[POSITION_ID] ASC,
	[TBL_SECTORES_ID] ASC,
	[TBL_CATEGORIAS_APROBACIONES_ID] ASC,
	[L_BUDGET] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[MIEMBROSGRUPO].[PK_MIEMBROSGRUPO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[MIEMBROSGRUPO] ADD CONSTRAINT [PK_MIEMBROSGRUPO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NAX_RESOURCES_EN].[PK__NAX_RESO__D9C1FA01BE0DDE8A].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NAX_RESOURCES_EN] ADD CONSTRAINT [PK__NAX_RESO__D9C1FA01BE0DDE8A] PRIMARY KEY CLUSTERED (
	[NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NAX_RESOURCES_ES].[PK__NAX_RESO__D9C1FA0147BEC6A7].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NAX_RESOURCES_ES] ADD CONSTRAINT [PK__NAX_RESO__D9C1FA0147BEC6A7] PRIMARY KEY CLUSTERED (
	[NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NAX_RESOURCES_PT].[PK__NAX_RESO__D9C1FA01CE811C5A].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NAX_RESOURCES_PT] ADD CONSTRAINT [PK__NAX_RESO__D9C1FA01CE811C5A] PRIMARY KEY CLUSTERED (
	[NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NC_FILES].[PK_ARCHIVOSASUNTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NC_FILES] ADD CONSTRAINT [PK_ARCHIVOSASUNTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NC_FILESCATEGORIES].[PK_NC_FILESCATEGORIES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NC_FILESCATEGORIES] ADD CONSTRAINT [PK_NC_FILESCATEGORIES] PRIMARY KEY CLUSTERED (
	[NC_FILESCATEGORIESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NC_TASKFILES].[PK_ARCHIVOSTAREAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NC_TASKFILES] ADD CONSTRAINT [PK_ARCHIVOSTAREAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NC_WF_ETAPAS_DISCONTINUED].[PK_NC_WF_ETAPAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NC_WF_ETAPAS_DISCONTINUED] ADD CONSTRAINT [PK_NC_WF_ETAPAS] PRIMARY KEY CLUSTERED (
	[MODULE_ID] ASC,
	[CODIGO_NC] ASC,
	[CODIGO_NCETAPAS] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCACCESSLEVELSTYPES].[PK_NCACCESSLEVELS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCACCESSLEVELSTYPES] ADD CONSTRAINT [PK_NCACCESSLEVELS] PRIMARY KEY CLUSTERED (
	[NCACCESSLEVELSTYPES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCAUSASCLASES].[PK_CAUSASCLASES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCAUSASCLASES] ADD CONSTRAINT [PK_CAUSASCLASES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCC_SECURITY].[PK_NCCC_SECURITY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCC_SECURITY] ADD CONSTRAINT [PK_NCCC_SECURITY] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCLASES].[PK_NCCLASES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCLASES] ADD CONSTRAINT [PK_NCCLASES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCOSTOS].[PK_NCCOSTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCOSTOS] ADD CONSTRAINT [PK_NCCOSTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCOSTOSCATEGORIAS].[PK_NCCOSTOSCATEGORIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCOSTOSCATEGORIAS] ADD CONSTRAINT [PK_NCCOSTOSCATEGORIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCCOSTOSCLASES].[PK_NCCOSTOSCLASES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCCOSTOSCLASES] ADD CONSTRAINT [PK_NCCOSTOSCLASES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCDEFINICIONETAPAS].[PK_NCDEFINICIONETAPAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCDEFINICIONETAPAS] ADD CONSTRAINT [PK_NCDEFINICIONETAPAS] PRIMARY KEY CLUSTERED (
	[TIPO] ASC,
	[ETAPA] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCDETECTANTES].[PK_NCDETCLIENTE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCDETECTANTES] ADD CONSTRAINT [PK_NCDETCLIENTE] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCESTADOS].[PK_NCESTADOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCESTADOS] ADD CONSTRAINT [PK_NCESTADOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCETAPAS].[PK_NCETAPAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCETAPAS] ADD CONSTRAINT [PK_NCETAPAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCINTERRELACIONES].[PK_NCINTERRELACIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCINTERRELACIONES] ADD CONSTRAINT [PK_NCINTERRELACIONES] PRIMARY KEY CLUSTERED (
	[CODIGOASUNTOORIGEN] ASC,
	[CODIGOASUNTORELACIONADO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCINVOLUCRADOS].[PK_NCINVOLUCRADOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCINVOLUCRADOS] ADD CONSTRAINT [PK_NCINVOLUCRADOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCMAINPROD].[PK_NCMAINPROD].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCMAINPROD] ADD CONSTRAINT [PK_NCMAINPROD] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCMODULESECURITYLEVELS].[PK_NCMODULESECURITYLEVELS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCMODULESECURITYLEVELS] ADD CONSTRAINT [PK_NCMODULESECURITYLEVELS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCSECURITYLEVELSDESCRIPTION].[PK_NCSECURITYLEVELSDESCRIPTION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCSECURITYLEVELSDESCRIPTION] ADD CONSTRAINT [PK_NCSECURITYLEVELSDESCRIPTION] PRIMARY KEY CLUSTERED (
	[NIVEL] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS].[PK_NCTAREAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTAREAS] ADD CONSTRAINT [PK_NCTAREAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREAS_DEPENDENCIES].[PK_NCTAREAS_DEPENDENCIES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTAREAS_DEPENDENCIES] ADD CONSTRAINT [PK_NCTAREAS_DEPENDENCIES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTAREASDESTINATARIOS].[PK_NCTAREASDESTINATARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTAREASDESTINATARIOS] ADD CONSTRAINT [PK_NCTAREASDESTINATARIOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTASKS_NOT_WORKING_DAYS].[PK_NCTASKS_NOT_WORKING_DAYS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTASKS_NOT_WORKING_DAYS] ADD CONSTRAINT [PK_NCTASKS_NOT_WORKING_DAYS] PRIMARY KEY CLUSTERED (
	[FECHA] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTASKSPEOPLE].[PK_NCTASKSPEOPLE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTASKSPEOPLE] ADD CONSTRAINT [PK_NCTASKSPEOPLE] PRIMARY KEY CLUSTERED (
	[NCTASKID] ASC,
	[IK_PEOPLEID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTASKSSTEPS].[PK_NCTASKSSTEPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTASKSSTEPS] ADD CONSTRAINT [PK_NCTASKSSTEPS] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCTASKSSTEPSRESPONSIBLES].[PK_NCTASKSSTEPSRESPONSIBLES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCTASKSSTEPSRESPONSIBLES] ADD CONSTRAINT [PK_NCTASKSSTEPSRESPONSIBLES] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC,
	[RESPONSIBLE_RANKID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[NCWORKGROUPS].[PK_NCWORKGROUPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[NCWORKGROUPS] ADD CONSTRAINT [PK_NCWORKGROUPS] PRIMARY KEY CLUSTERED (
	[ISSUE_ID] ASC,
	[NCWORKGROUPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ORGANIGRAMA].[PK_ORGANIGRAMA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ORGANIGRAMA] ADD CONSTRAINT [PK_ORGANIGRAMA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ORGANIGRAMAREL_OLD].[PK_ORGANIGRAMAREL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ORGANIGRAMAREL_OLD] ADD CONSTRAINT [PK_ORGANIGRAMAREL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ORGANIGRAMATIPOS].[PK_ORGANIGRAMATIPOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ORGANIGRAMATIPOS] ADD CONSTRAINT [PK_ORGANIGRAMATIPOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PERMISOSDOC].[PK_PERMISOSDOC].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PERMISOSDOC] ADD CONSTRAINT [PK_PERMISOSDOC] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS].[PK_PROC_FLOW_RELATIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS] ADD CONSTRAINT [PK_PROC_FLOW_RELATIONS] PRIMARY KEY CLUSTERED (
	[PROC_NODESID_SOURCE] ASC,
	[PROC_NODESID_TARGET] ASC,
	[PROC_FLOW_RELS_ELEMENTSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_FLOW_RELATIONS_ELEMENTS].[PK_PROC_FLOW_RELATIONS_ELEMENTS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_FLOW_RELATIONS_ELEMENTS] ADD CONSTRAINT [PK_PROC_FLOW_RELATIONS_ELEMENTS] PRIMARY KEY CLUSTERED (
	[PROC_FLOW_RELS_ELEMENTSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_NODE_TYPES].[PK_PROC_NODE_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_NODE_TYPES] ADD CONSTRAINT [PK_PROC_NODE_TYPES] PRIMARY KEY CLUSTERED (
	[PROC_NODE_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_NODES].[PK_PROC_NODES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_NODES] ADD CONSTRAINT [PK_PROC_NODES] PRIMARY KEY CLUSTERED (
	[PROC_NODESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_NODES_OPTIONS].[PK_PROC_NODES_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_NODES_OPTIONS] ADD CONSTRAINT [PK_PROC_NODES_OPTIONS] PRIMARY KEY CLUSTERED (
	[PROC_NODESID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS].[PK_PROC_NODES_RELATIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS] ADD CONSTRAINT [PK_PROC_NODES_RELATIONS] PRIMARY KEY CLUSTERED (
	[PROC_NODESID_SOURCE] ASC,
	[PROC_NODESID_TARGET] ASC,
	[PROC_RELATIONS_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_NODES_RELATIONS_STRENGTH].[PK_PROC_NODES_RELATIONS_STRENGTH].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_NODES_RELATIONS_STRENGTH] ADD CONSTRAINT [PK_PROC_NODES_RELATIONS_STRENGTH] PRIMARY KEY CLUSTERED (
	[PROC_NODES_RELS_STRENGTHID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_ORGCHART_RELATIONS_TYPES].[PK_PROC_ORGCHART_RELATIONS_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_ORGCHART_RELATIONS_TYPES] ADD CONSTRAINT [PK_PROC_ORGCHART_RELATIONS_TYPES] PRIMARY KEY CLUSTERED (
	[PROC_ORGCHART_RELS_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_PLANS].[PK_PROC_PLANS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_PLANS] ADD CONSTRAINT [PK_PROC_PLANS] PRIMARY KEY CLUSTERED (
	[PROC_PLANSID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_PLANS_OPTIONS].[PK_PROC_PLANS_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_PLANS_OPTIONS] ADD CONSTRAINT [PK_PROC_PLANS_OPTIONS] PRIMARY KEY CLUSTERED (
	[PROC_PLANSID] ASC,
	[USERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROC_RELATIONS_TYPES].[PK_PROC_RELATIONS_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROC_RELATIONS_TYPES] ADD CONSTRAINT [PK_PROC_RELATIONS_TYPES] PRIMARY KEY CLUSTERED (
	[PROC_RELATIONS_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[PROCESOS].[PK_PROCESOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[PROCESOS] ADD CONSTRAINT [PK_PROCESOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[ROBOTS_REPORTS_EXTRADATA].[PK_TBL_REPORTS_EXTRADATA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[ROBOTS_REPORTS_EXTRADATA] ADD CONSTRAINT [PK_TBL_REPORTS_EXTRADATA] PRIMARY KEY CLUSTERED (
	[RPT_UID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3COLUMNS].[PK_S3COLUMNS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3COLUMNS] ADD CONSTRAINT [PK_S3COLUMNS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[QUESTION_ORDER] ASC,
	[COLUMN_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3OPTIONS].[PK_S3OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3OPTIONS] ADD CONSTRAINT [PK_S3OPTIONS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[QUESTION_ORDER] ASC,
	[COLUMN_ORDER] ASC,
	[OPTION_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3QUESTIONS].[PK_S3QUESTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3QUESTIONS] ADD CONSTRAINT [PK_S3QUESTIONS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[QUESTION_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3RESPONSES].[PK_S3RESPONSES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3RESPONSES] ADD CONSTRAINT [PK_S3RESPONSES] PRIMARY KEY CLUSTERED (
	[RESPONSE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3RESPONSES_MEMOS].[PK_S3RESPONSES_MEMOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3RESPONSES_MEMOS] ADD CONSTRAINT [PK_S3RESPONSES_MEMOS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[RESPONSE_ID] ASC,
	[QUESTION_ORDER] ASC,
	[MEMO_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3RESPONSES_OPTIONS].[PK_S3RESPONSES_OPTIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3RESPONSES_OPTIONS] ADD CONSTRAINT [PK_S3RESPONSES_OPTIONS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[RESPONSE_ID] ASC,
	[QUESTION_ORDER] ASC,
	[COLUMN_ORDER] ASC,
	[ROW_ORDER] ASC,
	[OPTION_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[S3ROWS].[PK_S3ROWS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[S3ROWS] ADD CONSTRAINT [PK_S3ROWS] PRIMARY KEY CLUSTERED (
	[SURVEYDEF_ID] ASC,
	[QUESTION_ORDER] ASC,
	[ROW_ORDER] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SS_CARTS_WO].[PK_SS_CARTS_WO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SS_CARTS_WO] ADD CONSTRAINT [PK_SS_CARTS_WO] PRIMARY KEY CLUSTERED (
	[SS_CARTS_WOID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SS_REPORTS_WO].[PK_SS_REPORTS_WO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SS_REPORTS_WO] ADD CONSTRAINT [PK_SS_REPORTS_WO] PRIMARY KEY CLUSTERED (
	[SS_REPORTS_WOID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SS_WO].[PK_SO_WO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SS_WO] ADD CONSTRAINT [PK_SO_WO] PRIMARY KEY CLUSTERED (
	[SS_WO_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYDEFINITIONS].[PK_SURVEYDEFINITIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYDEFINITIONS] ADD CONSTRAINT [PK_SURVEYDEFINITIONS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYEDGROUPS].[PK_SURVEYEDGROUPS_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYEDGROUPS] ADD CONSTRAINT [PK_SURVEYEDGROUPS_1] PRIMARY KEY CLUSTERED (
	[CODIGOSURVEY] ASC,
	[CODIGOSURVEYGROUP] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYGROUPS].[PK_SURVERYGROUPS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYGROUPS] ADD CONSTRAINT [PK_SURVERYGROUPS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYGROUPSMEMBERS].[PK_SURVEYGROUPSMEMBERS_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYGROUPSMEMBERS] ADD CONSTRAINT [PK_SURVEYGROUPSMEMBERS_1] PRIMARY KEY CLUSTERED (
	[CODIGOSURVEYUSER] ASC,
	[CODIGOSURVEYGROUP] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYUSERS].[PK_SURVEYUSERS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYUSERS] ADD CONSTRAINT [PK_SURVEYUSERS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SURVEYUSERS_EXTRADATA].[PK_SURVEYUSERS_EXTRADATA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SURVEYUSERS_EXTRADATA] ADD CONSTRAINT [PK_SURVEYUSERS_EXTRADATA] PRIMARY KEY CLUSTERED (
	[SURVEYUSERID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[SVG_TYPES].[PK_SVG_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[SVG_TYPES] ADD CONSTRAINT [PK_SVG_TYPES] PRIMARY KEY CLUSTERED (
	[SVG_TYPESID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TAREASREVISION].[PK_TAREASREVISION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TAREASREVISION] ADD CONSTRAINT [PK_TAREASREVISION] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TAREASSISTEMA].[PK_TAREASSISTEMA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TAREASSISTEMA] ADD CONSTRAINT [PK_TAREASSISTEMA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TASKSCATEGORIES].[PK_TASKSCATEGORIES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TASKSCATEGORIES] ADD CONSTRAINT [PK_TASKSCATEGORIES] PRIMARY KEY CLUSTERED (
	[TASKSCATEGORIES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TASKSDELAYS].[PK_TASKSDELAYS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TASKSDELAYS] ADD CONSTRAINT [PK_TASKSDELAYS] PRIMARY KEY CLUSTERED (
	[TASKSDELAYS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TASKSDELAYSTYPES].[PK_TASKSDELAYSTYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TASKSDELAYSTYPES] ADD CONSTRAINT [PK_TASKSDELAYSTYPES] PRIMARY KEY CLUSTERED (
	[TASKSDELAYSTYPES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ACTIVIDADES].[PK_TBL_ACTIVIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ACTIVIDADES] ADD CONSTRAINT [PK_TBL_ACTIVIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ACTIVIDADESEMPRESAS].[PK_TBL_ACTIVIDADESEMPRESAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ACTIVIDADESEMPRESAS] ADD CONSTRAINT [PK_TBL_ACTIVIDADESEMPRESAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_AGENTES_SYSO].[PK_TBL_AGENTES_SYSO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_AGENTES_SYSO] ADD CONSTRAINT [PK_TBL_AGENTES_SYSO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_AREA_CAUSAS].[PK_TBL_AREA_CAUSAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_AREA_CAUSAS] ADD CONSTRAINT [PK_TBL_AREA_CAUSAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_AVAILABLE_WFS].[PK_TBL_AVAILABLE_WFS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_AVAILABLE_WFS] ADD CONSTRAINT [PK_TBL_AVAILABLE_WFS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_BS_CUSTOM_ICONS].[PK_TBL_BS_CUSTOM_ICONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_BS_CUSTOM_ICONS] ADD CONSTRAINT [PK_TBL_BS_CUSTOM_ICONS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_BSIND_PERIODS_TYPES].[PK_TBL_BSIND_PERIODS_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_BSIND_PERIODS_TYPES] ADD CONSTRAINT [PK_TBL_BSIND_PERIODS_TYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CATEGORIAS_APROBACIONES].[PK_TBL_CATEGORIAS_APROBACIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CATEGORIAS_APROBACIONES] ADD CONSTRAINT [PK_TBL_CATEGORIAS_APROBACIONES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CATEGORIASDOCUMENTOS].[PK_TBL_CATEGORIASDOCUMENTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CATEGORIASDOCUMENTOS] ADD CONSTRAINT [PK_TBL_CATEGORIASDOCUMENTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CATEGORIASUSUARIOS].[PK_TBL_CATEGORIASUSUARIOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CATEGORIASUSUARIOS] ADD CONSTRAINT [PK_TBL_CATEGORIASUSUARIOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CLAUSULA_ISO9001].[PK_TBL_CLAUSULA_ISO9001].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CLAUSULA_ISO9001] ADD CONSTRAINT [PK_TBL_CLAUSULA_ISO9001] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CLIENTES].[PK_TBL_CLIENTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CLIENTES] ADD CONSTRAINT [PK_TBL_CLIENTES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CONSECUENCIAS_CELDAS].[PK_TBL_TABLASCONSECUENCIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CONSECUENCIAS_CELDAS] ADD CONSTRAINT [PK_TBL_TABLASCONSECUENCIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CONSECUENCIAS_COLUMNAS].[PK_TBL_CONSECUENCIAS_COLUMNAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CONSECUENCIAS_COLUMNAS] ADD CONSTRAINT [PK_TBL_CONSECUENCIAS_COLUMNAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_CONSECUENCIAS_FILAS].[PK_TBL_CONSECUENCIAS_FILAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_CONSECUENCIAS_FILAS] ADD CONSTRAINT [PK_TBL_CONSECUENCIAS_FILAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENT_CHANGELOG_TYPES].[PK_TBL_DOCUMENT_CHANGELOG_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENT_CHANGELOG_TYPES] ADD CONSTRAINT [PK_TBL_DOCUMENT_CHANGELOG_TYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_EMPRESA].[PK_TBL_DOCUMENTOS_EXTRADATA_EMPRESA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_EMPRESA] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_EMPRESA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_INSTITUCION].[PK_TBL_DOCUMENTOS_EXTRADATA_INSTITUCION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_INSTITUCION] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_INSTITUCION] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_PRODUCTO].[PK_TBL_DOCUMENTOS_EXTRADATA_PRODUCTO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_PRODUCTO] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_PRODUCTO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_ACTA].[PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_ACTA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_ACTA] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_ACTA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_DOC_LEGAL].[PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_DOC_LEGAL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_DOC_LEGAL] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_DOC_LEGAL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_SERVICIO].[PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_SERVICIO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_TIPO_SERVICIO] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_TIPO_SERVICIO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_DOCUMENTOS_EXTRADATA_UNIDAD_NEGOCIO].[PK_TBL_DOCUMENTOS_EXTRADATA_UNIDAD_NEGOCIO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_DOCUMENTOS_EXTRADATA_UNIDAD_NEGOCIO] ADD CONSTRAINT [PK_TBL_DOCUMENTOS_EXTRADATA_UNIDAD_NEGOCIO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ESTADO].[PK_TBL_ESTADO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ESTADO] ADD CONSTRAINT [PK_TBL_ESTADO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_GRUPOSEMPRESARIALES].[PK_TBL_GRUPOSEMPRESARIALES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_GRUPOSEMPRESARIALES] ADD CONSTRAINT [PK_TBL_GRUPOSEMPRESARIALES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_HORAS].[PK_TBL_HORAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_HORAS] ADD CONSTRAINT [PK_TBL_HORAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_IKACTIONS_CATEGORIES].[PK_TBL_IKALERTS_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_IKACTIONS_CATEGORIES] ADD CONSTRAINT [PK_TBL_IKALERTS_TYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_IMPORTANCIA].[PK_TBL_IMPORTANCIA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_IMPORTANCIA] ADD CONSTRAINT [PK_TBL_IMPORTANCIA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_MATRICES_CONSECUENCIAS].[PK_TBL_MATRICES_CONSECUENCIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_MATRICES_CONSECUENCIAS] ADD CONSTRAINT [PK_TBL_MATRICES_CONSECUENCIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_MONEDAS].[PK_TBL_MONEDAS_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_MONEDAS] ADD CONSTRAINT [PK_TBL_MONEDAS_1] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NATURALEZA_LESIONES_SYSO].[PK_TBL_NATURALEZA_LESIONES_SYSO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NATURALEZA_LESIONES_SYSO] ADD CONSTRAINT [PK_TBL_NATURALEZA_LESIONES_SYSO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCCARACTER].[PK_TBL_NCCARACTER].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCCARACTER] ADD CONSTRAINT [PK_TBL_NCCARACTER] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCCC_CAUSAS].[PK_TBL_NO_CONFORMIDADES_CAUSAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCCC_CAUSAS] ADD CONSTRAINT [PK_TBL_NO_CONFORMIDADES_CAUSAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCCC_DESCRIPCIONES_FYC].[PK_TBL_TABLACONSECUENCIAS_DESC_COL_Y_FILA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCCC_DESCRIPCIONES_FYC] ADD CONSTRAINT [PK_TBL_TABLACONSECUENCIAS_DESC_COL_Y_FILA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCCC_MODULOS_ESPECIALES].[PK_TBL_MODULOS_TRATAMIENTO_ESPECIAL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCCC_MODULOS_ESPECIALES] ADD CONSTRAINT [PK_TBL_MODULOS_TRATAMIENTO_ESPECIAL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCCC_REQUISITOSNORMATIVOS].[PK_TBL_NO_CONFORMIDADES_REQUISITOS_NORMATIVOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCCC_REQUISITOSNORMATIVOS] ADD CONSTRAINT [PK_TBL_NO_CONFORMIDADES_REQUISITOS_NORMATIVOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_NCDETECCION].[PK_TBL_NCDETECCION].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_NCDETECCION] ADD CONSTRAINT [PK_TBL_NCDETECCION] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ORIGEN].[PK_TBL_ORIGEN].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ORIGEN] ADD CONSTRAINT [PK_TBL_ORIGEN] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ORIGEN_NC].[PK_TBL_ORIGEN_NC].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ORIGEN_NC] ADD CONSTRAINT [PK_TBL_ORIGEN_NC] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PAISES].[PK_TBL_PAISES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PAISES] ADD CONSTRAINT [PK_TBL_PAISES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PARTES_CUERPO_SYSO].[PK_TBL_PARTES_CUERPO_SYSO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PARTES_CUERPO_SYSO] ADD CONSTRAINT [PK_TBL_PARTES_CUERPO_SYSO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PEOPLE].[PK_TBL_PEOPLE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PEOPLE] ADD CONSTRAINT [PK_TBL_PEOPLE] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PERMANENCIA_CAMBIO_XT].[PK_TBL_PERMANENCIA_CAMBIO_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PERMANENCIA_CAMBIO_XT] ADD CONSTRAINT [PK_TBL_PERMANENCIA_CAMBIO_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PERSONASCONTACTOS].[PK_TBL_PERSONASCONTACTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PERSONASCONTACTOS] ADD CONSTRAINT [PK_TBL_PERSONASCONTACTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PRESENTATION_TYPES].[PK_TBL_PRESENTATION_TYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PRESENTATION_TYPES] ADD CONSTRAINT [PK_TBL_PRESENTATION_TYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PRESENTATIONS_TEMPLATES].[PK_TBL_PRESENTATIONS_TEMPLATES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PRESENTATIONS_TEMPLATES] ADD CONSTRAINT [PK_TBL_PRESENTATIONS_TEMPLATES] PRIMARY KEY CLUSTERED (
	[PRESENTATIONS_TEMPLATES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PRIORIDADES_XT].[PK_TBL_PRIORIDADES_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PRIORIDADES_XT] ADD CONSTRAINT [PK_TBL_PRIORIDADES_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PRODUCTOS].[PK_TBL_PRODUCTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PRODUCTOS] ADD CONSTRAINT [PK_TBL_PRODUCTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PROVEEDORES].[PK_TBL_PROVEEDORES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PROVEEDORES] ADD CONSTRAINT [PK_TBL_PROVEEDORES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_PROYECTO].[PK_TBL_PROYECTO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_PROYECTO] ADD CONSTRAINT [PK_TBL_PROYECTO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_RESTRICTED_AM_DOCTYPES].[PK_TBL_RESTRICTED_AM_DOCTYPES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_RESTRICTED_AM_DOCTYPES] ADD CONSTRAINT [PK_TBL_RESTRICTED_AM_DOCTYPES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_ROBOT_DOCX_TEMPLATES].[PK_TBL_ROBOT_DOCX_TEMPLATES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_ROBOT_DOCX_TEMPLATES] ADD CONSTRAINT [PK_TBL_ROBOT_DOCX_TEMPLATES] PRIMARY KEY CLUSTERED (
	[TBL_ROBOT_DOCX_TEMPLATES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_RPTFORMATS].[PK_TBL_RPTFORMATS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_RPTFORMATS] ADD CONSTRAINT [PK_TBL_RPTFORMATS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_AUDITORIA].[PK_TBL_TIPO_AUDITORIA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_AUDITORIA] ADD CONSTRAINT [PK_TBL_TIPO_AUDITORIA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_CAMBIO_XT].[PK_TBL_TIPO_CAMBIO_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_CAMBIO_XT] ADD CONSTRAINT [PK_TBL_TIPO_CAMBIO_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_CONTACTO].[PK_TBL_TIPO_CONTACTO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_CONTACTO] ADD CONSTRAINT [PK_TBL_TIPO_CONTACTO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_IMPACTO_XT].[PK_TBL_TIPO_IMPACTO_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_IMPACTO_XT] ADD CONSTRAINT [PK_TBL_TIPO_IMPACTO_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_NC].[PK_TBL_TIPO_NC].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_NC] ADD CONSTRAINT [PK_TBL_TIPO_NC] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_PROYECTO].[PK_TBL_TIPO_PROYECTO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_PROYECTO] ADD CONSTRAINT [PK_TBL_TIPO_PROYECTO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPO_SEGUIMIENTO].[PK_TBL_TIPO_SEGUIMIENTO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPO_SEGUIMIENTO] ADD CONSTRAINT [PK_TBL_TIPO_SEGUIMIENTO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPOS_ACCIDENTE_PERSONAL_SYSO].[PK_TBL_TIPOS_ACCIDENTE_PERSONAL_SYSO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPOS_ACCIDENTE_PERSONAL_SYSO] ADD CONSTRAINT [PK_TBL_TIPOS_ACCIDENTE_PERSONAL_SYSO] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPOS_IKROLES].[PK_TBL_TIPOS_IKROLES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPOS_IKROLES] ADD CONSTRAINT [PK_TBL_TIPOS_IKROLES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_TIPOS_INFORMES_CONTROL_CAMBIOS_XT].[PK_TBL_TIPOS_INFORMES_CONTROL_CAMBIOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_TIPOS_INFORMES_CONTROL_CAMBIOS_XT] ADD CONSTRAINT [PK_TBL_TIPOS_INFORMES_CONTROL_CAMBIOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TBL_UNIDADES].[PK_TBL_UNIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TBL_UNIDADES] ADD CONSTRAINT [PK_TBL_UNIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TIPOSCRITICAS].[PK_TIPOSCRITICAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TIPOSCRITICAS] ADD CONSTRAINT [PK_TIPOSCRITICAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TIPOSDOCUMENTOS].[PK_TIPOSDOCUMENTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TIPOSDOCUMENTOS] ADD CONSTRAINT [PK_TIPOSDOCUMENTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TODO].[PK_TODO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TODO] ADD CONSTRAINT [PK_TODO] PRIMARY KEY CLUSTERED (
	[TODO_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROT_INVOLVED].[PK_TPROT_INVOLVED].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROT_INVOLVED] ADD CONSTRAINT [PK_TPROT_INVOLVED] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROT_RESPONSIBLE].[PK_TPROT_RESPONSIBLE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROT_RESPONSIBLE] ADD CONSTRAINT [PK_TPROT_RESPONSIBLE] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROT_TASK].[PK_TPROT_TASK].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROT_TASK] ADD CONSTRAINT [PK_TPROT_TASK] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROT_TASKSSTEPS].[PK_TPROT_TASKSSTEP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROT_TASKSSTEPS] ADD CONSTRAINT [PK_TPROT_TASKSSTEP] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROT_TASKSSTEPSRESPONSIBLES].[PK_TPROT_TASKSSTEPSRESPONSIBLES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROT_TASKSSTEPSRESPONSIBLES] ADD CONSTRAINT [PK_TPROT_TASKSSTEPSRESPONSIBLES] PRIMARY KEY CLUSTERED (
	[NCTASKSSTEPS_ID] ASC,
	[RESPONSIBLE_RANKID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[TPROTTASK_DEPENDENCIES].[PK_TPROTTASK_DEPENDENCIES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[TPROTTASK_DEPENDENCIES] ADD CONSTRAINT [PK_TPROTTASK_DEPENDENCIES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_ACCIDENTES_XT].[PK_VAR_ACCIDENTES_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_ACCIDENTES_XT] ADD CONSTRAINT [PK_VAR_ACCIDENTES_XT] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_ACCIONESCORRECTIVAS].[PK_VAR_ACCIONESCORRECTIVAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_ACCIONESCORRECTIVAS] ADD CONSTRAINT [PK_VAR_ACCIONESCORRECTIVAS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_ACCIONESMEJORA].[PK_VAR_ACCIONESMEJORA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_ACCIONESMEJORA] ADD CONSTRAINT [PK_VAR_ACCIONESMEJORA] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_ACTIVIDADES].[PK_VAR_ACTIVIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_ACTIVIDADES] ADD CONSTRAINT [PK_VAR_ACTIVIDADES] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_AUDITORIAS].[PK_VAR_AUDITORIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_AUDITORIAS] ADD CONSTRAINT [PK_VAR_AUDITORIAS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_BSSTRATINITIATIVES].[PK_VAR_BSSTRATINITIATIVES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_BSSTRATINITIATIVES] ADD CONSTRAINT [PK_VAR_BSSTRATINITIATIVES] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_CIRCULOS_CALIDAD].[PK_VAR_CIRCULOS_CALIDAD].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_CIRCULOS_CALIDAD] ADD CONSTRAINT [PK_VAR_CIRCULOS_CALIDAD] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_COMPETENCIAS].[PK_VAR_COMPETENCIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_COMPETENCIAS] ADD CONSTRAINT [PK_VAR_COMPETENCIAS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_COMPETENCIAS_CARGO].[PK_VAR_COMPETENCIAS_CARGO].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_COMPETENCIAS_CARGO] ADD CONSTRAINT [PK_VAR_COMPETENCIAS_CARGO] PRIMARY KEY CLUSTERED (
	[CODIGO_CARGO] ASC,
	[CODIGO_COMPETENCIA] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_COMPETENCIAS_PERSONA].[PK_VAR_COMPETENCIAS_PERSONA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_COMPETENCIAS_PERSONA] ADD CONSTRAINT [PK_VAR_COMPETENCIAS_PERSONA] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_CONTACTO_PERSONAS].[PK_VAR_CONTACTO_PERSONAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_CONTACTO_PERSONAS] ADD CONSTRAINT [PK_VAR_CONTACTO_PERSONAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_CONTACTOS].[PK_VAR_CONTACTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_CONTACTOS] ADD CONSTRAINT [PK_VAR_CONTACTOS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_CONTROL_CAMBIOS_XT].[PK_VAR_CONTROL_CAMBIOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_CONTROL_CAMBIOS_XT] ADD CONSTRAINT [PK_VAR_CONTROL_CAMBIOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_DATOS].[PK_VAR_DATOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_DATOS] ADD CONSTRAINT [PK_VAR_DATOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_DISENOPRODUCTOS].[PK_VAR_DISENOPRODUCTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_DISENOPRODUCTOS] ADD CONSTRAINT [PK_VAR_DISENOPRODUCTOS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_FOROS].[PK_VAR_FOROS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_FOROS] ADD CONSTRAINT [PK_VAR_FOROS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_INCIDENTES_AUD].[PK_VAR_INCIDENTES_AUD].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_INCIDENTES_AUD] ADD CONSTRAINT [PK_VAR_INCIDENTES_AUD] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_INCIDENTESINT].[PK_VAR_INCIDENTESINT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_INCIDENTESINT] ADD CONSTRAINT [PK_VAR_INCIDENTESINT] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_NCAUD].[PK_VAR_NCAUD].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_NCAUD] ADD CONSTRAINT [PK_VAR_NCAUD] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_NOCONFORMIDADES].[PK_VAR_NOCONFORMIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_NOCONFORMIDADES] ADD CONSTRAINT [PK_VAR_NOCONFORMIDADES] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_OBJETIVOSCUAL].[PK_VAR_OBJETIVOSCUAL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSCUAL] ADD CONSTRAINT [PK_VAR_OBJETIVOSCUAL] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_OBJETIVOSNUM].[PK_VAR_OBJETIVOSNUM].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_OBJETIVOSNUM] ADD CONSTRAINT [PK_VAR_OBJETIVOSNUM] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_PEOPLE_GROUP].[PK_VAR_PEOPLE_GROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_PEOPLE_GROUP] ADD CONSTRAINT [PK_VAR_PEOPLE_GROUP] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_PRESENTATIONS].[PK_VAR_PANELS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_PRESENTATIONS] ADD CONSTRAINT [PK_VAR_PANELS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_PROYECTOS].[PK_VAR_PROYECTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_PROYECTOS] ADD CONSTRAINT [PK_VAR_PROYECTOS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_QUEJAS].[PK_VAR_QUEJAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_QUEJAS] ADD CONSTRAINT [PK_VAR_QUEJAS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_REGISTRO_CONTACTOS].[PK_VAR_REGISTRO_CONTACTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_REGISTRO_CONTACTOS] ADD CONSTRAINT [PK_VAR_REGISTRO_CONTACTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_REQUISITOS].[PK_VAR_REQUISITOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_REQUISITOS] ADD CONSTRAINT [PK_VAR_REQUISITOS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_REUNIONES].[PK_VAR_REUNIONES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_REUNIONES] ADD CONSTRAINT [PK_VAR_REUNIONES] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_SEGUIMIENTO_PLAZOS].[PK_VAR_SEGUIMIENTO_PLAZOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_SEGUIMIENTO_PLAZOS] ADD CONSTRAINT [PK_VAR_SEGUIMIENTO_PLAZOS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_SUGERENCIAS].[PK_VAR_SUGERENCIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_SUGERENCIAS] ADD CONSTRAINT [PK_VAR_SUGERENCIAS] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_SUGERENCIASINT].[PK_VAR_SUGERENCIASINT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_SUGERENCIASINT] ADD CONSTRAINT [PK_VAR_SUGERENCIASINT] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VAR_TPROT].[PK_VAR_TPROT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VAR_TPROT] ADD CONSTRAINT [PK_VAR_TPROT] PRIMARY KEY CLUSTERED (
	[CODIGONC] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_ACCIDENTADOS_XT].[PK_VARCHILD_ACCIDENTADOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_ACCIDENTADOS_XT] ADD CONSTRAINT [PK_VARCHILD_ACCIDENTADOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_APROBADORES_AP].[PK_VARCHILD_APROBADORES_AP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_APROBADORES_AP] ADD CONSTRAINT [PK_VARCHILD_APROBADORES_AP] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_AUDITEDS].[PK_VARCHILD_AUDITEDS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_AUDITEDS] ADD CONSTRAINT [PK_VARCHILD_AUDITEDS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_AUDITORS].[PK_VARCHILD_AUDITORS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_AUDITORS] ADD CONSTRAINT [PK_VARCHILD_AUDITORS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_COSTOS_CONTROL_CAMBIOS_XT].[PK_VARCHILD_COSTOS_CONTROL_CAMBIOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_COSTOS_CONTROL_CAMBIOS_XT] ADD CONSTRAINT [PK_VARCHILD_COSTOS_CONTROL_CAMBIOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_DOCUMENTOS_AUDITORIAS].[PK_VARCHILD_DOCUMENTOS_AUDITORIAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_DOCUMENTOS_AUDITORIAS] ADD CONSTRAINT [PK_VARCHILD_DOCUMENTOS_AUDITORIAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_EXTERNAL_AUDITORS].[PK_VARCHILD_EXTERNAL_AUDITORS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_EXTERNAL_AUDITORS] ADD CONSTRAINT [PK_VARCHILD_EXTERNAL_AUDITORS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_FROZEN_PRESENTATIONS].[PK_VARCHILD_FROZEN_PANELS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_FROZEN_PRESENTATIONS] ADD CONSTRAINT [PK_VARCHILD_FROZEN_PANELS] PRIMARY KEY CLUSTERED (
	[FROZEN_PRESENTATION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_IMPACTOS].[PK_VARCHILD_IMPACTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_IMPACTOS] ADD CONSTRAINT [PK_VARCHILD_IMPACTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_INFORMES_CONTROL_CAMBIOS_XT].[PK_VARCHILD_INFORMES_CONTROL_CAMBIOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_INFORMES_CONTROL_CAMBIOS_XT] ADD CONSTRAINT [PK_VARCHILD_INFORMES_CONTROL_CAMBIOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NC_CLIENTES].[PK_VARCHILD_NC_CLIENTES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NC_CLIENTES] ADD CONSTRAINT [PK_VARCHILD_NC_CLIENTES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NC_PERSONAS].[PK_VARCHILD_NC_PERSONAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NC_PERSONAS] ADD CONSTRAINT [PK_VARCHILD_NC_PERSONAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NC_PROVEEDORES].[PK_VARCHILD_NC_PROVEEDORES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NC_PROVEEDORES] ADD CONSTRAINT [PK_VARCHILD_NC_PROVEEDORES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_AREAS].[PK_VARCHILD_AREAS_CAUSAS_NOCONFORMIDADES_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_AREAS] ADD CONSTRAINT [PK_VARCHILD_AREAS_CAUSAS_NOCONFORMIDADES_1] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_CAUSAS].[PK_VARCHILD_CAUSAS_NOCONFORMIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_CAUSAS] ADD CONSTRAINT [PK_VARCHILD_CAUSAS_NOCONFORMIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_CONSECUENCIAS].[PK_VARCHILD_REGISTROMATRIZ_NOCONFORMIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_CONSECUENCIAS] ADD CONSTRAINT [PK_VARCHILD_REGISTROMATRIZ_NOCONFORMIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_ESPINA5WHY].[PK_VARCHILD_NCCC_ESPINA5WHY].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_ESPINA5WHY] ADD CONSTRAINT [PK_VARCHILD_NCCC_ESPINA5WHY] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_PROCESOS].[PK_VARCHILD_PROCESOSAFECTADOS_NOCONFORMIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_PROCESOS] ADD CONSTRAINT [PK_VARCHILD_PROCESOSAFECTADOS_NOCONFORMIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_NCCC_REQNORMATIVOS].[PK_VARCHILD_REQUISITOS_NORMATIVOS_NOCONFORMIDADES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_NCCC_REQNORMATIVOS] ADD CONSTRAINT [PK_VARCHILD_REQUISITOS_NORMATIVOS_NOCONFORMIDADES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_OTROSDAÑOS_XT].[PK_VARCHILD_OTROSDAÑOS_XT].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_OTROSDAÑOS_XT] ADD CONSTRAINT [PK_VARCHILD_OTROSDAÑOS_XT] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_PEOPLE_GROUP_CARGOS].[PK_VARCHILD_PEOPLE_GROUP_CARGOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_PEOPLE_GROUP_CARGOS] ADD CONSTRAINT [PK_VARCHILD_PEOPLE_GROUP_CARGOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_PEOPLE_GROUP_PEOPLE].[PK_VARCHILD_PEOPLE_GROUP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_PEOPLE_GROUP_PEOPLE] ADD CONSTRAINT [PK_VARCHILD_PEOPLE_GROUP] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_PRESENTATIONS_SLIDES].[PK_VARCHILD_PANELS_PANEL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_PRESENTATIONS_SLIDES] ADD CONSTRAINT [PK_VARCHILD_PANELS_PANEL] PRIMARY KEY CLUSTERED (
	[SLIDE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_PROCESOS_APROBACION_AP].[PK_VARCHILD_PROCESOS_APROBACION_AP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_PROCESOS_APROBACION_AP] ADD CONSTRAINT [PK_VARCHILD_PROCESOS_APROBACION_AP] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_PRODUCTOS].[PK_VARCHILD_PRODUCTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_PRODUCTOS] ADD CONSTRAINT [PK_VARCHILD_PRODUCTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_REL_SYSO_ACCIDENTE_AGENTE].[PK_VARCHILD_REL_SYSO_ACCIDENTE_AGENTE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_REL_SYSO_ACCIDENTE_AGENTE] ADD CONSTRAINT [PK_VARCHILD_REL_SYSO_ACCIDENTE_AGENTE] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_ASUNTOS].[PK_VAR_SEGUIMIENTO_PLAZOS_ASUNTOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_ASUNTOS] ADD CONSTRAINT [PK_VAR_SEGUIMIENTO_PLAZOS_ASUNTOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_ASUNTOS_EXCL].[PK_VARCHILD_SEGUIMIENTO_PLAZOS_EXCLUIDOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_ASUNTOS_EXCL] ADD CONSTRAINT [PK_VARCHILD_SEGUIMIENTO_PLAZOS_EXCLUIDOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_ASUNTOS_INC].[PK_VARCHILD_SEGUIMIENTO_PLAZOS_INCLUIDOS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_ASUNTOS_INC] ADD CONSTRAINT [PK_VARCHILD_SEGUIMIENTO_PLAZOS_INCLUIDOS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_CLASES].[PK_VAR_SEGUIMIENTO_PLAZOS_CLASES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_CLASES] ADD CONSTRAINT [PK_VAR_SEGUIMIENTO_PLAZOS_CLASES] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_INV_MANUAL].[PK_VARCHILD_SEGUIMIENTO_PLAZOS_INV_MANUAL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_INV_MANUAL] ADD CONSTRAINT [PK_VARCHILD_SEGUIMIENTO_PLAZOS_INV_MANUAL] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_SEG_PLA_TAREAS].[PK_VARCHILD_SEGUIMIENTO_PLAZOS_TAREAS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_SEG_PLA_TAREAS] ADD CONSTRAINT [PK_VARCHILD_SEGUIMIENTO_PLAZOS_TAREAS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[VARCHILD_TAREAS_APROBACION_AP].[PK_VARCHILD_TAREAS_APROBACION_AP].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[VARCHILD_TAREAS_APROBACION_AP] ADD CONSTRAINT [PK_VARCHILD_TAREAS_APROBACION_AP] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WEBGROUPMEMBERS].[PK_WEBGROUPMEMBERS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WEBGROUPMEMBERS] ADD CONSTRAINT [PK_WEBGROUPMEMBERS] PRIMARY KEY CLUSTERED (
	[CODIGO] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF].[PK_WF].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF] ADD CONSTRAINT [PK_WF] PRIMARY KEY CLUSTERED (
	[WF_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_APPROVAL_RECORDS].[PK_WF_APPROVAL_RECORDS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS] ADD CONSTRAINT [PK_WF_APPROVAL_RECORDS] PRIMARY KEY CLUSTERED (
	[WF_NODE_ID] ASC,
	[IKPERSON_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_APPROVAL_RECORDS_HISTORIC].[PK_WF_APPROVAL_RECORDS_HISTORIC].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS_HISTORIC] ADD CONSTRAINT [PK_WF_APPROVAL_RECORDS_HISTORIC] PRIMARY KEY CLUSTERED (
	[WF_APPROVAL_RECORDS_HISTORIC_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_APPROVAL_RECORDS_STATUS].[PK_WF_APPROVAL_REQUIREMENTS_STATUS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_APPROVAL_RECORDS_STATUS] ADD CONSTRAINT [PK_WF_APPROVAL_REQUIREMENTS_STATUS] PRIMARY KEY CLUSTERED (
	[WF_APPROVAL_RECORDS_STATUS_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_APPROVAL_REQUIREMENTS].[PK_WF_APPROVAL_REQUIREMENTS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_APPROVAL_REQUIREMENTS] ADD CONSTRAINT [PK_WF_APPROVAL_REQUIREMENTS] PRIMARY KEY CLUSTERED (
	[WF_NODE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_APPROVAL_REQUIREMENTS_HISTORIC].[PK_WF_APPROVAL_REQUIREMENTS_HISTORIC_1].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_APPROVAL_REQUIREMENTS_HISTORIC] ADD CONSTRAINT [PK_WF_APPROVAL_REQUIREMENTS_HISTORIC_1] PRIMARY KEY CLUSTERED (
	[WF_APPROVAL_REQUIREMENTS_HISTORIC_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_EXTRADATA].[PK_WF_EXTRADATA].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_EXTRADATA] ADD CONSTRAINT [PK_WF_EXTRADATA] PRIMARY KEY CLUSTERED (
	[WF_NODE_ID] ASC,
	[WF_EXTRADATA_VAR_FIELDNAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_FLAGS].[PK_WF_FLAGS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_FLAGS] ADD CONSTRAINT [PK_WF_FLAGS] PRIMARY KEY CLUSTERED (
	[WF_ID] ASC,
	[WF_FLAGS_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_NODE].[PK_WF_NODE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_NODE] ADD CONSTRAINT [PK_WF_NODE] PRIMARY KEY CLUSTERED (
	[WF_NODE_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_NODE_RESPONSIBLE].[PK_WF_NODE_RESPONSIBLE].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_NODE_RESPONSIBLE] ADD CONSTRAINT [PK_WF_NODE_RESPONSIBLE] PRIMARY KEY CLUSTERED (
	[WF_ID] ASC,
	[WF_XMLNODE_ID] ASC,
	[POSITION_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_NODE_ROL].[PK_WF_NODE_ROL].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_NODE_ROL] ADD CONSTRAINT [PK_WF_NODE_ROL] PRIMARY KEY CLUSTERED (
	[WF_NODE_ID] ASC,
	[WF_NODE_ROL_NAME] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_ROLESTEMPLATES].[PK_WF_ROLESTEMPLATES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_ROLESTEMPLATES] ADD CONSTRAINT [PK_WF_ROLESTEMPLATES] PRIMARY KEY CLUSTERED (
	[WF_ROLESTEMPLATES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_SCHEDDATES].[PK_WF_SCHEDDATES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_SCHEDDATES] ADD CONSTRAINT [PK_WF_SCHEDDATES] PRIMARY KEY CLUSTERED (
	[WF_SCHEDDATES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[WF_SCHEDTEMPLATES].[PK_WF_SCHEDTEMPLATES].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[WF_SCHEDTEMPLATES] ADD CONSTRAINT [PK_WF_SCHEDTEMPLATES] PRIMARY KEY CLUSTERED (
	[WF_SCHEDTEMPLATES_ID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[XML_MODULE_DEFINITIONS].[PK_XML_MODULE_DEFINITIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[XML_MODULE_DEFINITIONS] ADD CONSTRAINT [PK_XML_MODULE_DEFINITIONS] PRIMARY KEY CLUSTERED (
	[MODULEID] ASC
) ON [PRIMARY]

GO
--SqlScripter----[dbo].[XML_MODULEGROUP_DEFINITIONS].[PK_XML_MODULEGROUP_DEFINITIONS].sql
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[XML_MODULEGROUP_DEFINITIONS] ADD CONSTRAINT [PK_XML_MODULEGROUP_DEFINITIONS] PRIMARY KEY CLUSTERED (
	[MODULEGROUPID] ASC
) ON [PRIMARY]
