SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CT2TMP](
	[CT2_FILIAL] [varchar](2) NOT NULL,
	[CT2_DATA] [varchar](8) NOT NULL,
	[CT2_LOTE] [varchar](6) NOT NULL,
	[CT2_SBLOTE] [varchar](3) NOT NULL,
	[CT2_DOC] [varchar](6) NOT NULL,
	[CT2_LINHA] [varchar](3) NOT NULL,
	[CT2_MOEDLC] [varchar](2) NOT NULL,
	[CT2_DC] [varchar](1) NOT NULL,
	[CT2_DEBITO] [varchar](20) NOT NULL,
	[CT2_CREDIT] [varchar](20) NOT NULL,
	[CT2_DCD] [varchar](1) NOT NULL,
	[CT2_DCC] [varchar](1) NOT NULL,
	[CT2_VALOR] [float] NOT NULL,
	[CT2_MOEDAS] [varchar](5) NOT NULL,
	[CT2_HP] [varchar](3) NOT NULL,
	[CT2_HIST] [varchar](40) NOT NULL,
	[CT2_CCD] [varchar](9) NOT NULL,
	[CT2_CCC] [varchar](9) NOT NULL,
	[CT2_ITEMD] [varchar](9) NOT NULL,
	[CT2_ITEMC] [varchar](9) NOT NULL,
	[CT2_CLVLDB] [varchar](9) NOT NULL,
	[CT2_CLVLCR] [varchar](9) NOT NULL,
	[CT2_ATIVDE] [varchar](40) NOT NULL,
	[CT2_ATIVCR] [varchar](40) NOT NULL,
	[CT2_EMPORI] [varchar](2) NOT NULL,
	[CT2_FILORI] [varchar](2) NOT NULL,
	[CT2_INTERC] [varchar](1) NOT NULL,
	[CT2_IDENTC] [varchar](16) NOT NULL,
	[CT2_TPSALD] [varchar](1) NOT NULL,
	[CT2_SEQUEN] [varchar](10) NOT NULL,
	[CT2_MANUAL] [varchar](1) NOT NULL,
	[CT2_ORIGEM] [varchar](100) NOT NULL,
	[CT2_ROTINA] [varchar](10) NOT NULL,
	[CT2_AGLUT] [varchar](1) NOT NULL,
	[CT2_LP] [varchar](3) NOT NULL,
	[CT2_SEQHIS] [varchar](3) NOT NULL,
	[CT2_SEQLAN] [varchar](3) NOT NULL,
	[CT2_DTVENC] [varchar](8) NOT NULL,
	[CT2_SLBASE] [varchar](1) NOT NULL,
	[CT2_DTLP] [varchar](8) NOT NULL,
	[CT2_DATATX] [varchar](8) NOT NULL,
	[CT2_TAXA] [float] NOT NULL,
	[CT2_VLR01] [float] NOT NULL,
	[CT2_VLR02] [float] NOT NULL,
	[CT2_VLR03] [float] NOT NULL,
	[CT2_VLR04] [float] NOT NULL,
	[CT2_VLR05] [float] NOT NULL,
	[CT2_CRCONV] [varchar](1) NOT NULL,
	[CT2_CRITER] [varchar](4) NOT NULL,
	[CT2_USERGI] [varchar](17) NOT NULL,
	[CT2_USERGA] [varchar](17) NOT NULL,
	[CT2_KEY2] [varchar](100) NOT NULL,
	[CT2_DTPROC] [varchar](8) NOT NULL,
	[CT2_SW] [varchar](3) NOT NULL,
	[CT2_SEQCOM] [varchar](15) NOT NULL,
	[CT2_KEY] [varchar](100) NOT NULL,
	[CT2_SEGOFI] [varchar](10) NOT NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [bigint] NOT NULL,
	[R_E_C_D_E_L_] [bigint] NOT NULL,
	[TG3_FILIAL] [varchar](2) NOT NULL,
	[TG3_CODAVA] [varchar](3) NOT NULL,
	[TG3_CODOPC] [varchar](3) NOT NULL,
	[TG3_OPCAO] [varchar](30) NOT NULL,
	[TG3_PESO] [float] NOT NULL,
	[TG3_PLANAC] [varchar](1) NOT NULL,
	[TG3_PLANEM] [varchar](1) NOT NULL,
	[TG3_OBJETI] [varchar](1) NOT NULL,
	[TG3_MONITO] [varchar](1) NOT NULL,
	[TG3_MSBLQL] [varchar](1) NOT NULL
)
ON [PRIMARY]
