SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CTKFOF](
	[CTK_FILIAL] [varchar](2) NOT NULL,
	[CTK_SEQUEN] [varchar](10) NOT NULL,
	[CTK_DC] [varchar](1) NOT NULL,
	[CTK_DEBITO] [varchar](20) NOT NULL,
	[CTK_CREDIT] [varchar](20) NOT NULL,
	[CTK_VLR01] [float] NOT NULL,
	[CTK_VLR02] [float] NOT NULL,
	[CTK_VLR03] [float] NOT NULL,
	[CTK_VLR04] [float] NOT NULL,
	[CTK_VLR05] [float] NOT NULL,
	[CTK_MOEDAS] [varchar](5) NOT NULL,
	[CTK_HIST] [varchar](40) NOT NULL,
	[CTK_CCD] [varchar](9) NOT NULL,
	[CTK_CCC] [varchar](9) NOT NULL,
	[CTK_ITEMD] [varchar](9) NOT NULL,
	[CTK_ITEMC] [varchar](9) NOT NULL,
	[CTK_INTERC] [varchar](1) NOT NULL,
	[CTK_LP] [varchar](3) NOT NULL,
	[CTK_LPSEQ] [varchar](3) NOT NULL,
	[CTK_CLVLDB] [varchar](9) NOT NULL,
	[CTK_CLVLCR] [varchar](9) NOT NULL,
	[CTK_ORIGEM] [varchar](100) NOT NULL,
	[CTK_CONTAB] [varchar](1) NOT NULL,
	[CTK_KEY] [varchar](100) NOT NULL,
	[CTK_ATIVDE] [varchar](40) NOT NULL,
	[CTK_ATIVCR] [varchar](40) NOT NULL,
	[CTK_ROTINA] [varchar](10) NOT NULL,
	[CTK_TPSALD] [varchar](1) NOT NULL,
	[CTK_MOEDLC] [varchar](2) NOT NULL,
	[CTK_SBLOTE] [varchar](3) NOT NULL,
	[CTK_DATA] [varchar](8) NOT NULL,
	[CTK_DTVENC] [varchar](8) NOT NULL,
	[CTK_LOTE] [varchar](6) NOT NULL,
	[CTK_USERGI] [varchar](17) NOT NULL,
	[CTK_USERGA] [varchar](17) NOT NULL,
	[CTK_KEY2] [varchar](100) NOT NULL,
	[CTK_SW] [varchar](3) NOT NULL,
	[CTK_SEQCOM] [varchar](15) NOT NULL,
	[CTK_TABORI] [varchar](3) NOT NULL,
	[CTK_RECORI] [varchar](17) NOT NULL,
	[CTK_RECDES] [varchar](17) NOT NULL,
	[CTK_RECCV3] [varchar](17) NOT NULL,
	[CTK_HAGLUT] [varchar](40) NOT NULL,
	[CTK_MLTSLD] [varchar](20) NOT NULL,
	[CTK_CODCLI] [varchar](14) NOT NULL,
	[CTK_CODFOR] [varchar](6) NOT NULL,
	[CTK_NODIA] [varchar](10) NOT NULL,
	[CTK_CODPAR] [varchar](6) NOT NULL,
	[CTK_DIACTB] [varchar](2) NOT NULL,
	[CTK_AT01DB] [varchar](20) NOT NULL,
	[CTK_AT01CR] [varchar](20) NOT NULL,
	[CTK_AT02DB] [varchar](20) NOT NULL,
	[CTK_AT02CR] [varchar](20) NOT NULL,
	[CTK_AT03DB] [varchar](20) NOT NULL,
	[CTK_AT03CR] [varchar](20) NOT NULL,
	[CTK_AT04DB] [varchar](20) NOT NULL,
	[CTK_AT04CR] [varchar](20) NOT NULL,
	[D_E_L_E_T_] [varchar](1) NOT NULL,
	[R_E_C_N_O_] [bigint] NOT NULL,
	[R_E_C_D_E_L_] [bigint] NOT NULL
)
ON [PRIMARY]
