SET ANSI_NULLS OFF
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[fn_usr_getDocsDistrib]') IS NULL EXEC('CREATE FUNCTION [dbo].[fn_usr_getDocsDistrib] () RETURNS @Ret TABLE (c1 int) AS BEGIN /*TEMPORARY OBJECT, DELETE AFTER ALL OBJECTS ARE CREATED*/ RETURN END')
GO
ALTER FUNCTION [dbo].[fn_usr_getDocsDistrib]
(
		@IKCDU int,
		@L_INCLUDE_RUNNING_DISTRIBUTIONS tinyint
	)
RETURNS @DOC_TBL TABLE (CODIGO int , NOMBRE nvarchar(120), CODIGOISO nvarchar(25), REVISION int , C_REVISION nvarchar(20), TIPO_DISTRIBUCION tinyint,CODIGODISTRIBUCION INT) 
AS
	BEGIN
DECLARE @DISTRI TABLE 
(CODIGOUSUARIOCARGOMULTIPLE INT,
CODDIS INT,
CODIGODOC INT,
CODIGOCARGO INT,
CODIGODISTRIBUIDOR INT,
L_SUBDISTRIBUIDOR TINYINT,
INSTRUCCIONES ntext,
ARCHIVOINSTRUCCIONES nvarchar(100),
ORGANIGRAMA_CODIGO INT,
DESCRIPCION nvarchar(100),
TIPO INT,
TIPO_DISTRIBUCION TINYINT,
TIPO_ORG_IMG nvarchar(50),
TIPO_DISTRIBUCIONLOC nvarchar(50)
)		

INSERT INTO @DISTRI
SELECT * FROM dbo.fn_usr_getDocsDistribPolicies(@IKCDU)



DELETE FROM @DOC_TBL

INSERT INTO @DOC_TBL (CODIGO, NOMBRE, CODIGOISO, REVISION,C_REVISION,CODIGODISTRIBUCION,TIPO_DISTRIBUCION )
SELECT  
CODIGO, 
NOMBRE, 
CODIGOISO, 
REVISION,
C_REVISION ,
CODIGODISTRIBUCION, 
MIN(TIPO_DISTRIBUCION)

FROM (

SELECT  CODIGO, NOMBRE, CODIGOISO, REVISION,C_REVISION ,CODIGODISTRIBUCION, DIS.TIPO_DISTRIBUCION
FROM DOCUMENTOS DOC 
JOIN @DISTRI DIS ON (DOC.CODIGO=DIS.CODIGODOC )
WHERE  
	L_ISSURVEY=0 
AND ESTADO=2 
AND DIS.TIPO_DISTRIBUCION<10
AND(
	@L_INCLUDE_RUNNING_DISTRIBUTIONS=1  
	OR (
		@L_INCLUDE_RUNNING_DISTRIBUTIONS=0 AND 
		CODIGO NOT IN (
				SELECT CODIGODOCUMENTO FROM VISTA_CONDOCTAREASUSUARIOS 
				WHERE CODIGOUSUARIO=@IKCDU 
				)  
		)
)


UNION

SELECT  CODIGO, NOMBRE, CODIGOISO, REVISION,C_REVISION ,CODIGODISTRIBUCION, DIS.TIPO_DISTRIBUCION
FROM DOCUMENTOS DOC 
JOIN @DISTRI DIS ON (DOC.CODIGODISTRIBUCION=DIS.CODIGODOC )
WHERE  
	L_ISSURVEY=0 
AND ESTADO=2 
AND DIS.TIPO_DISTRIBUCION<10
AND(
	@L_INCLUDE_RUNNING_DISTRIBUTIONS=1  
	OR (
		@L_INCLUDE_RUNNING_DISTRIBUTIONS=0 AND 
		CODIGO NOT IN (
				SELECT CODIGODOCUMENTO FROM VISTA_CONDOCTAREASUSUARIOS 
				WHERE CODIGOUSUARIO=@IKCDU 
				)  
		)
)

)DATA
GROUP BY
CODIGO, NOMBRE, CODIGOISO, REVISION,C_REVISION ,CODIGODISTRIBUCION

ORDER BY NOMBRE


		

RETURN
END
GO
